"""Bench table, exception tier: rows as data in `bench/vocab.py`'s words, built by `bench/table.py`.
FAMILIES: (template, [params, ...]) — one entry, many rows (vocab.TEMPLATES). ROWS: the one-off rows, each in words.
CODE_ROWS: the one-off rows no word earns its place for, written in code with vocab's helpers."""

FAMILIES = [
    ('base', [('eat', 'underwater'), ('hunt', 'pillar'), ('craft', 'cliff_edge'), ('smelt', 'nether'), ('sleep', 'rain'),
         ('chop', 'pickup_lag'), ('mine_iron', 'pickup_lag'), ('hunt', 'pickup_lag'), ('craft', 'inventory_lag'),
         ('eat', 'inventory_lag'), ('smelt', 'interrupt_twice'), ('loot', 'interrupt_at_success'), ('nav', 'contested'),
         ('nav', 'player_takeover'), ('nav', 'buried_by_sand'), ('mine_stone', 'buried_by_sand'),
         ('craft', 'buried_by_sand'), ('smelt', 'buried_by_sand'), ('chop', 'lava_edge'), ('hunt', 'lava_edge'),
         ('loot', 'lava_edge'), ('hunt', 'one_slot'), ('chop', 'stack_room'), ('chop', 'valuables_full'),
         ('hunt', 'valuables_full'), ('loot', 'valuables_full'), ('mine_iron', 'tool_one_use'),
         ('mine_iron', 'wrong_tool'), ('craft', 'goal_met'), ('smelt', 'goal_met'),
         ('chop', None, 'leaves_block_trunk'), ('chop', None, 'floating_logs'), ('loot', None, 'empty_chest'),
         ('sleep', None, 'bed_obstructed'), ('nav', None, 'nav_sealed_in'), ('craft', None, 'craft_short_of_planks'),
         ('smelt', None, 'smelt_without_fuel'), ('eat', None, 'eat_with_nothing'),
         ('mine_iron', None, 'lava_under_ore'), ('mine_stone', None, 'falling_gravel'),
         ('nav', None, 'start_cell_on_a_fence'), ('nav', None, 'start_cell_in_a_nook')]),
    ('one', [('take_bed', ['take'], 'a village bed 6 blocks away → carried',
          [('floor',), ('setblock', ('@', 6, 0, 0), 'red_bed'), ('stand',)], ('skill', 'take', 'bed', 1, ['red_bed']),
          ('gain', 'bed', 1), 25),
         ('tidy_full_bag', ['room:tidy'], 'a full bag of junk → slots free',
          [('floor',), ('stand',), ('give', 'dirt', 2304)], ('skill', 'tidy_inventory'), ('free_slots', 2), 25),
         ('deposit_home_chest', ['room:deposit'], 'a home chest beside the body, a bag of cobblestone → stored',
          [('floor',), ('chest', ('@', 2, 0, 0)), ('stand',), ('give', 'cobblestone', 1280), ('give', 'dirt', 640)],
          ('seq', 1, ('!remember', 'add_site', ['home', ('@', 2, 0, 0), 'minecraft:overworld'], {'name': 'home'}),
           ('!skill', 'deposit')),
          ('all', ('!free_slots', 8), ('!dropped_nothing',)), 25),
         ('dig_out_morning', ['dig_out'], 'morning, sealed in a 1×1 pocket → out',
          [('floor',), ('fill', ('@', -1, 0, -1), ('@', 1, 2, 1), 'stone'),
           ('fill', ('@', 0, 0, 0), ('@', 0, 1, 0), 'air'), ('stand',), ('give', 'stone_pickaxe')],
          ('skill', 'dig_out'), ('not', ('!call', 'enclosed', [])), 25),
         ('pod_open_ground', ['shelter:wall in'], 'night, open ground, 16 blocks → walled in',
          [('floor',), ('stand',), ('give', 'cobblestone', 16), ('time', 18000)], ('skill', 'pod'),
          ('blocks', ('@', -1, 0, -1), ('@', 1, 2, 1), ('cobblestone',), 9), 25),
         ('pod_in_water', ['shelter:wall in'], 'night, standing on a pillar in deep water → walled in anyway',
          [('tank', -6, 6, -6, 6, 0), ('floor', 'water', 6), ('floor', 'stone', 0), ('stand',),
           ('give', 'cobblestone', 32), ('time', 18000)],
          ('skill', 'pod'), ('blocks', ('@', -1, 0, -1), ('@', 1, 2, 1), ('cobblestone',), 9), 25),
         ('build_shelter_flat', ['build:shelter'], "flat stone, the hut's materials → a shelter standing",
          [('floor',), ('stand',), ('give', 'cobblestone', 32), ('give', 'oak_door'), ('give', 'torch', 2)],
          ('skill', 'build_shelter'),
          ('all', ('!blocks', ('@', -6, 0, -6), ('@', 6, 3, 6), ('cobblestone',), 14),
           ('!blocks', ('@', -6, 0, -6), ('@', 6, 3, 6), ('oak_door',), 1),
           ('!blocks', ('@', -6, 0, -6), ('@', 6, 3, 6), ('torch', 'wall_torch'), 1)),
          25),
         ('burrow_hillside', ['burrow'], 'night, a stone hillside beside the body → tunnelled in and sealed',
          [('floor',), ('fill', ('@', 2, 0, -4), ('@', 8, 4, 4), 'stone'), ('stand',), ('give', 'stone_pickaxe'),
           ('give', 'cobblestone', 8), ('time', 18000)],
          ('skill', 'burrow'), ('all', ('!alive', 18), ('!call', 'enclosed', [])), 25),
         ('contain_lava_pool', ['contain_lava'], 'an open lava pool beside the body → covered',
          [('floor',), ('fill', ('@', 2, -1, -1), ('@', 3, -1, 1), 'lava'), ('stand',), ('give', 'cobblestone', 16)],
          ('skill', 'contain_lava'), ('blocks', ('@', 2, -1, -1), ('@', 3, -1, 1), ('lava',), 0, 0), 25),
         ('torch_in_the_dark', ['light'], 'a dark room, torches carried → one torch placed',
          [('floor',), ('at', 'fill {0} {1} stone hollow', ('@', -4, 0, -4), ('@', 4, 3, 4)),
           ('fill', ('@', -3, 0, -3), ('@', 3, 2, 3), 'air'), ('stand',), ('give', 'torch', 4)],
          ('skill', 'light_area', 4, 1), ('blocks', ('@', -3, 0, -3), ('@', 3, 2, 3), ('torch', 'wall_torch'), 1), 20),
         ('light_the_room', ['light_area'], 'a dark 9×9 room, 8 torches → several placed',
          [('floor',), ('at', 'fill {0} {1} stone hollow', ('@', -6, 0, -6), ('@', 6, 3, 6)),
           ('fill', ('@', -5, 0, -5), ('@', 5, 2, 5), 'air'), ('stand',), ('give', 'torch', 8)],
          ('skill', 'light_area', 6, 4), ('blocks', ('@', -5, 0, -5), ('@', 5, 2, 5), ('torch', 'wall_torch'), 2), 25),
         ('find_air_capped', ['find_air'], 'under water with a stone cap, out of breath → air',
          [('fill', ('@', -4, -4, -4), ('@', 4, 3, 4), 'stone'), ('fill', ('@', -3, -3, -3), ('@', 3, 2, 3), 'water'),
           ('stand', 0, -3), ('give', 'stone_pickaxe')],
          ('skill', 'find_air'), ('all', ('!alive', 10), ('!breathing',)), 25),
         ('surface_from_lake', ['reach:air'], '4 blocks down in open water → up to breathe',
          [('tank', -5, 5, -5, 5, 8), ('fill', ('@', -5, -3, -5), ('@', 5, 7, 5), 'water'), ('stand', 0, -3)],
          ('skill', 'find_air'), ('breathing',), 25),
         ('footing_in_water', ['reach:footing'], 'treading water, cobblestone carried → a block underfoot',
          [('tank', -4, 4, -4, 4, 0), ('floor', 'water', 4), ('stand',), ('give', 'cobblestone', 8)],
          ('skill', 'stand_on_a_block'), ('all', ('!state', 'onGround'), ('!under_feet', 'cobblestone')), 20),
         ('unbury_sand', ['unbury'], 'sand dropped on the head → dug out', [('floor',), ('stand',)],
          ('seq', 2, ('!scene_now', [('fill', ('@', 0, 1, 0), ('@', 0, 3, 0), 'sand')]), ('!pause', 1),
           ('!skill', 'unbury')),
          ('all', ('!call', 'head_clear', []), ('!alive', 10)), 20),
         ('seek_remembered', ['seek'], 'memory says iron ore 16 blocks away → walked there',
          [('floor', 'stone', 10), ('fill', ('@', 10, -1, -8), ('@', 19, -1, 8), 'stone'),
           ('setblock', ('@', 17, 0, 0), 'iron_ore'), ('stand', -6)],
          ('seq', 1, ('!remember', 'note_seen', ['iron_ore', ('@', 17, 0, 0), 'minecraft:overworld'], {}),
           ('!skill', 'seek', ['iron_ore'])),
          ('_at', ('@', 17, 0, 0), 6), 25),
         ('open_space_from_shaft', ['move_to_open_space'],
          'a full bag at the bottom of a 1×1 shaft → out where it is open',
          [('floor', 'stone', 8, 4), ('floor', 'air', 0), ('stand', 0, -3), ('give', 'dirt', 2304),
           ('give', 'stone_pickaxe')],
          ('skill', 'move_to_open_space'), ('room_to_work',), 25),
         ('repair_broken_hut', ['repair_site'], 'a remembered hut with two wall blocks knocked out → rebuilt',
          [('floor',), ('at', 'fill {0} {1} cobblestone hollow', ('@', 2, 0, -2), ('@', 6, 2, 2)),
           ('fill', ('@', 2, 0, 0), ('@', 2, 1, 0), 'air'), ('stand',), ('give', 'cobblestone', 8)],
          ('skill', 'repair_site', ('$call', 'broken_hut', '$ctx')),
          ('blocks', ('@', 2, 0, 0), ('@', 2, 1, 0), ('cobblestone',), 2), 25),
         ('wait_out_the_night', ['wait:day'], 'night in a sealed stone room, no bed → waited until morning',
          [('floor',), ('at', 'fill {0} {1} stone hollow', ('@', -2, 0, -2), ('@', 2, 4, 2)), ('stand', 0, 1),
           ('time', 23500)],
          ('skill', 'wait_for_day'), ('is_day',), 25),
         ('withdraw_from_chest', ['withdraw'], 'a chest of iron beside the body → 4 ingots taken out',
          [('floor',), ('chest', ('@', 2, 0, 0), 'iron_ingot 9'), ('stand',)],
          ('skill', 'withdraw', 'minecraft:iron_ingot', 4, ('@', 2, 0, 0)), ('gain', 'minecraft:iron_ingot', 4), 25),
         ('enchant_pickaxe', ['enchant'],
          'an enchanting table, lapis, levels, an iron pickaxe → enchanted (lapis spent)',
          [('floor',), ('setblock', ('@', 2, 0, 0), 'enchanting_table'), ('stand',), ('give', 'iron_pickaxe'),
           ('give', 'lapis_lazuli', 6), ('cmd', 'experience add @p 30 levels')],
          ('skill', 'enchant_item', 'minecraft:iron_pickaxe'),
          ('all', ('!count', 'minecraft:lapis_lazuli', '<', 6), ('!slot_has', 'minecraft:iron_pickaxe', 'enchant')),
          25),
         ('trade_bread', ['trade'], 'a farmer selling bread for an emerald, 3 emeralds → bread',
          [('floor',), ('stand',), ('give', 'emerald', 3),
           ('summon', 'villager', ('@', 3, 0, 0),
            '{NoAI:1b,VillagerData:{profession:"minecraft:farmer",level:2,type:"minecraft:plains"},Offers:{Recipes:[{buy:{id:"minecraft:emerald",count:1},sell:{id:"minecraft:bread",count:6},maxUses:12}]}}')],
          ('skill', 'trade', 'minecraft:bread'), ('gain', 'minecraft:bread', 6), 25),
         ('brew_fire_resistance_stand', ['brew:fire_resistance'],
          'a brewing stand, water bottles, wart, magma cream, blaze powder → fire resistance (the cream spent)',
          [('floor',), ('setblock', ('@', 2, 0, 0), 'brewing_stand'), ('stand',),
           ('give', 'potion[potion_contents={potion:"minecraft:water"}]', 3), ('give', 'nether_wart'),
           ('give', 'magma_cream'), ('give', 'blaze_powder', 2)],
          ('skill', 'brew_fire_resistance'), ('slot_has', 'minecraft:potion', 'fire_resistance'), 25, 60),
         ('collect_auto_smelter', ['collect_machine'],
          'a remembered auto smelter whose output chest holds 8 ingots → taken',
          [('floor',), ('chest', ('@', 3, 0, 0), 'iron_ingot 8'), ('stand',)],
          ('skill', 'collect_machine', ('$call', 'bench_machine', '$ctx', ('@', 3, 0, 0))),
          ('gain', 'minecraft:iron_ingot', 8), 25),
         ('bridge_the_gap', ['bridge_toward'], 'a 6-block gap in the floor toward the target, blocks carried → across',
          [('floor',), ('fill', ('@', 2, -3, -8), ('@', 7, -1, 8), 'air'), ('stand',), ('give', 'cobblestone', 16)],
          ('skill', 'bridge_toward', ('@', 9, 0, 0)), ('_at', ('@', 9, 0, 0), 4), 25),
         ('plant_wheat', ['plant_farm'], 'grass, seeds, a hoe, a water bucket → a wheat plot growing',
          [('floor', 'grass_block'), ('stand',), ('give', 'wheat_seeds', 2), ('give', 'stone_hoe'),
           ('give', 'water_bucket')],
          ('skill', 'plant_farm'), ('blocks', ('@', -4, 0, -4), ('@', 4, 0, 4), ('wheat',), 2), 25),
         ('breed_cows', ['breed'], 'two cows in a pen, wheat carried → wheat spent on them',
          [('floor', 'grass_block'), ('pen', 'cow', 2), ('stand',), ('give', 'wheat', 4)], ('skill', 'breed'),
          ('mobs_near', 'minecraft:cow', 3), 25),
         ('fill_bottles_at_pond', ['fill_bottles'], 'a pond, 3 glass bottles → 3 water bottles',
          [('floor',), ('fill', ('@', 2, -1, -1), ('@', 3, -1, 1), 'water'), ('stand',), ('give', 'glass_bottle', 3)],
          ('skill', 'fill_bottles', 3), ('gain', 'minecraft:potion', 3), 25)]),
    ('real', [('seek_blocks_real', ['seek_blocks'], 'real terrain, a log column 16 blocks off → walked to it',
          ('skill', 'seek_blocks', ['oak_log', 'birch_log', 'spruce_log'], 1, 20),
          ('found_near', ['oak_log', 'birch_log', 'spruce_log'], 8), 25,
          # the real terrain's own trees within 12 cleared first (a 64-radius spread can land in a wood: found
          # within 8 at setup, 0 s), then the column 16 off: the walk to it is the row's
          [('cmd', 'execute at @p run fill ~-12 ~-4 ~-12 ~12 ~12 ~12 air replace #minecraft:logs'),
           ('cmd', 'execute at @p run fill ~16 ~ ~ ~16 ~4 ~ oak_log')]),
         ('strip_mine_real', ['strip_mine_step'], 'real terrain, a stone pickaxe → a mining tunnel started',
          ('skill', 'strip_mine_step', 2), ('gain', 'minecraft:cobblestone', 2), 25,
          [('cmd', 'execute at @p run fill ~-1 17 ~-1 ~1 19 ~1 air'), ('cmd', 'execute at @p run tp @p ~ 17 ~')])]),
    ('place', [('place_observer_up', 'minecraft:observer', 'up', 'up', 'exception'),
         ('place_observer_down', 'minecraft:observer', 'down', 'down', 'exception'),
         ('place_stairs_east', 'minecraft:oak_stairs', 'east', 'east', 'exception'),
         ('place_cobblestone_facing_ignored', 'minecraft:cobblestone', 'north', None, 'exception')]),
]
ROWS = [
    dict(name='cast_portal', module='building',
         doc=('A 3×3 lava pool beside the body; water bucket, bucket, 16 cobblestone, flint and steel → a portal frame '
              'cast in place and lit (no obsidian carried, no diamond pickaxe).'),
         scene=[('floor',), ('fill', ('@', 2, -1, -1), ('@', 4, -1, 1), 'lava'), ('tp', ('@', 0, 0, 0)),
                ('cmd', 'clear @p'), ('give', 'water_bucket'), ('give', 'bucket'), ('give', 'cobblestone', 16),
                ('give', 'flint_and_steel')],
         run=('do', 'bonobo.building.cast_portal', ['$ctx'], {}),
         check=[('call', 'count_blocks', ['$api', ('@', -8, -1, -8), ('@', 8, 6, 8), 'nether_portal'], '>=', 1)],
         budget=25,
         expect=[(('@', 2, -1, -1), ('@', 4, -1, 1), 'lava', 9, 9), (('@', -8, 0, -8), ('@', 8, 4, 8), '*', 0, 0)],
         skills=['cast_portal']),
    dict(name='build_light_portal', module='building',
         doc='Flat stone ground, 10 obsidian + 4 cobblestone + flint and steel → a lit nether portal.',
         scene=[('floor', 'stone', 8, 2), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'), ('give', 'obsidian', 10),
                ('give', 'cobblestone', 16), ('give', 'flint_and_steel')],
         run=('do', 'bonobo.building.build_blueprint', ['$ctx', 'nether_portal', ('@', 0, 0, 0)], {}),
         check=[('call', 'count_blocks', ['$api', ('@', -8, 0, -8), ('@', 8, 6, 8), 'nether_portal'], '>=', 6)],
         budget=25,
         expect=[(('@', -8, -1, -8), ('@', 8, -1, 8), 'stone', 289, 289), (('@', -8, 0, -8), ('@', 8, 6, 8), '*', 0, 0)],
         skills=['build_blueprint']),
    dict(name='fill_water_bucket', module='fluids', doc='A 3×3 pond next to the player, empty bucket → water bucket.',
         scene=[('floor', 'stone', 4, 2), ('fill', ('@', 1, -1, -1), ('@', 3, -1, 1), 'water'), ('tp', ('@', -1, 0, 0)),
                ('cmd', 'clear @p'), ('give', 'bucket')],
         run=('do', 'bonobo.fluids.fill_water_bucket', ['$ctx'], {}),
         check=[('count', 'minecraft:water_bucket', '>=', 1)], budget=25,
         expect=[(('@', 1, -1, -1), ('@', 3, -1, 1), 'water', 9, 9),
                 (('@', -4, -1, -4), ('@', 4, -1, 4), 'stone', 72, 72), (('@', -4, 0, -4), ('@', 4, 3, 4), '*', 0, 0)],
         skills=['fill_water_bucket']),
    dict(name='cross_lava_lake', module='nav',
         doc='A 12-block lava strip between two stone platforms; cobblestone → reach the far side alive.',
         scene=[('fill', ('@', -3, -3, -4), ('@', 18, -3, 4), 'stone'),
                ('fill', ('@', -2, -2, -3), ('@', 17, -1, 3), 'lava'),
                ('fill', ('@', -2, -1, -3), ('@', 1, -1, 3), 'stone'),
                ('fill', ('@', 14, -1, -3), ('@', 17, -1, 3), 'stone'), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'),
                ('give', 'cobblestone', 64), ('give', 'diamond_pickaxe')],
         run=('do', 'bonobo.nav.go_to', [('@', 15, 0, 0), ('$ctx', 'policy')], {'range_': 1.5}),
         check=[('call', 'near', ['$api', ('@', 15, 0, 0), 2.5]), ('state', 'health', '>', 10)], budget=25,
         expect=[(('@', 2, -1, -3), ('@', 13, -1, 3), 'lava', 84, 84),
                 (('@', -2, -1, -3), ('@', 1, -1, 3), 'stone', 28, 28), (('@', -2, 0, -3), ('@', 17, 4, 3), '*', 0, 0)],
         skills=['travel_to']),
    dict(name='gather_logs', module='wood', doc='A small grove; empty bag → 4 logs (speed wood).',
         scene=[('fill', ('@', -8, -3, -8), ('@', 8, -2, 8), 'dirt'), ('grove',),
                ('at', 'place feature minecraft:oak {0}', ('@', 4, 0, 0)),
                ('at', 'place feature minecraft:oak {0}', ('@', -4, 0, 3)), ('tp', ('@', 0, 0, 0)),
                ('cmd', 'clear @p')],
         run=('do', 'bonobo.wood.chop', ['$ctx', 4], {}), check=[('count', 'log', '>=', 4)], budget=25,
         expect=[(('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block', 285, 289),
                 (('@', -8, 0, -8), ('@', 8, 8, 8), 'oak_log', 6, 20)],
         skills=['chop']),
    dict(name='enter_nether', module='nether',
         doc='A lit 4×5 portal on stone ground → stand in it and arrive in the Nether.',
         scene=[('floor', 'stone', 6, 2), ('fill', ('@', -1, 0, 2), ('@', 2, 4, 2), 'obsidian'),
                ('fill', ('@', 0, 1, 2), ('@', 1, 3, 2), 'nether_portal[axis=x]'), ('tp', ('@', 0, 0, -3)),
                ('cmd', 'clear @p'), ('give', 'flint_and_steel')],
         run=('do', 'bonobo.nether.use_portal', ['$ctx', 'minecraft:the_nether'], {}),
         check=[('state', 'dimension', '==', 'minecraft:the_nether')], budget=20,
         expect=[(('@', 0, 1, 2), ('@', 1, 3, 2), 'nether_portal', 6, 6),
                 (('@', -1, 0, 2), ('@', 2, 4, 2), 'obsidian', 14, 14)],
         mod_extra=['state'], skills=['use_portal']),
    dict(name='barter_piglin', module='nether',
         doc='Nether platform, 3 piglins, 2 gold ingots and a carried gold helmet → wear it, barter, collect trades.',
         scene=[('floor', 'netherrack', 8, 2), ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
                ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'),
                ('cmd', 'item replace entity @p armor.feet with golden_boots'), ('give', 'gold_ingot', 2),
                ('give', 'golden_helmet'), ('give', 'iron_sword'),
                ('summon', 'piglin', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
                ('summon', 'piglin', ('@', -4, 0, 2), '{PersistenceRequired:1b}'),
                ('summon', 'piglin', ('@', 2, 0, -4), '{PersistenceRequired:1b}')],
         run=('do', 'bonobo.nether.barter_piglin', ['$ctx', 2], {}),
         check=[('count', 'minecraft:gold_ingot', '<=', 1), ('call', 'trades', ['$inv'], '>=', 1)],
         no_detail='the report line is code: <lambda>: a lambda; a lambda of (inv)', budget=25,
         dimension='minecraft:the_nether', combat=True,
         expect=[(('@', -8, -1, -8), ('@', 8, -1, 8), 'netherrack', 289, 289)],
         expect_entities=[('minecraft:piglin', 3)], tick_rate=60, skills=['barter_piglin']),
    dict(name='enter_end', module='end', doc='An open end portal in a stronghold room → jump in and arrive in the End.',
         scene=[('floor', 'stone_bricks', 6, 2),
                ('fill', ('@', -1, 0, -2), ('@', 1, 0, -2), 'end_portal_frame[facing=south,eye=true]'),
                ('fill', ('@', -1, 0, 2), ('@', 1, 0, 2), 'end_portal_frame[facing=north,eye=true]'),
                ('fill', ('@', -2, 0, -1), ('@', -2, 0, 1), 'end_portal_frame[facing=east,eye=true]'),
                ('fill', ('@', 2, 0, -1), ('@', 2, 0, 1), 'end_portal_frame[facing=west,eye=true]'),
                ('fill', ('@', -1, 0, -1), ('@', 1, 0, 1), 'end_portal'), ('tp', ('@', 0, 0, -5)), ('cmd', 'clear @p')],
         run=('do', 'bonobo.end.enter_end', ['$ctx'], {}), check=[('state', 'dimension', '==', 'minecraft:the_end')],
         budget=20, expect=[(('@', -1, 0, -1), ('@', 1, 0, 1), 'end_portal', 9, 9)], mod=['travel'],
         skills=['enter_end']),
    dict(name='craft_stone_tools', module='skills',
         doc='Stone floor, 6 oak logs → crafting table, wooden then stone pickaxe (plan-driven).',
         scene=[('floor', 'stone', 8, 4), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'), ('give', 'oak_log', 6)],
         run=('do', 'achieve', ['$ctx', [('tool', 'pickaxe', 1)], ('!inv_has', 'minecraft:stone_pickaxe', 1)], {}),
         check=[('count', 'minecraft:stone_pickaxe', '>=', 1)], budget=25,
         expect=[(('@', -8, -1, -8), ('@', 8, -1, 8), 'stone', 289, 289)], skills=['craft', 'mine', 'chop']),
    dict(name='hunt_food', module='skills', doc='Grass pen with 4 cows, iron sword → 3 raw beef.',
         scene=[('floor', 'grass_block', 8, 2), ('pen', 'cow', 0, 9), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'),
                ('give', 'iron_sword'), ('summon', 'cow', ('@', 4, 0, 3)), ('summon', 'cow', ('@', -4, 0, 2)),
                ('summon', 'cow', ('@', 3, 0, -5)), ('summon', 'cow', ('@', -5, 0, -4))],
         run=('do', 'bonobo.gather.hunt', ['$ctx', 'minecraft:beef', 3, ['minecraft:cow'], False], {}),
         check=[('count', 'minecraft:beef', '>=', 3)], budget=25, combat=False,
         expect=[(('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block', 289, 289)], expect_entities=[('minecraft:cow', 4)],
         skills=['hunt']),
    dict(name='craft_eyes', module='skills',
         doc='6 blaze rods + 12 ender pearls → 12 eyes of ender (plan-driven, table placed on the way).',
         scene=[('floor', 'stone', 6, 2), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'), ('give', 'blaze_rod', 6),
                ('give', 'ender_pearl', 12), ('give', 'crafting_table')],
         run=('do', 'achieve', ['$ctx', [('minecraft:ender_eye', 12)], ('!inv_has', 'minecraft:ender_eye', 12)], {}),
         check=[('count', 'minecraft:ender_eye', '>=', 12)], budget=25,
         expect=[(('@', -6, -1, -6), ('@', 6, -1, 6), 'stone', 169, 169)], mod=['craft', 'use', 'travel'],
         skills=['craft']),
    dict(name='return_from_nether', module='nether',
         doc='Nether side: a lit portal 6 blocks away → walk in and arrive in the Overworld.',
         scene=[('floor', 'netherrack', 6, 2), ('fill', ('@', -1, 0, 4), ('@', 2, 4, 4), 'obsidian'),
                ('fill', ('@', 0, 1, 4), ('@', 1, 3, 4), 'nether_portal[axis=x]'), ('tp', ('@', 0, 0, -2)),
                ('cmd', 'clear @p'), ('give', 'flint_and_steel'), ('give', 'cobblestone', 16)],
         run=('do', 'bonobo.nether.use_portal', ['$ctx', 'minecraft:overworld'], {}),
         check=[('state', 'dimension', '==', 'minecraft:overworld')], budget=20, dimension='minecraft:the_nether',
         expect=[(('@', 0, 1, 4), ('@', 1, 3, 4), 'nether_portal', 6, 6)], mod_extra=['state'], skills=['use_portal']),
    dict(name='locate_stronghold', module='nether',
         doc=("A flat sky plane under the skill's 200-block sideways leg, speed, 12 eyes → two throws, triangulated "
              'estimate within 64 blocks of /locate.'),
         scene=[('cmd', 'tp @p 10400 201 10400'), ('cmd', 'clear @p'), ('give', 'ender_eye', 12),
                ('give', 'cobblestone', 64), ('give', 'stone_pickaxe'), ('give', 'cooked_beef', 16),
                ('cmd', 'locate structure minecraft:stronghold')],
         run=('do', 'bonobo.nether.locate_stronghold', ['$ctx'], {}), before=[('do', 'stronghold_leg', ['$ctx'], {})],
         check=[('call', 'stronghold_error', [], '<=', 64)], budget=25, raw=True, release=True,
         skills=['locate_stronghold']),
    dict(name='find_portal_room_fresh', module='end',
         doc=('A stronghold piece built every run (a brick corridor, the room 64 blocks on, past the scan), standing '
              'on the estimate → bricks followed, portal frame found and reached.'),
         scene=[('cmd', 'clear @p'), ('give', 'diamond_pickaxe'), ('give', 'cobblestone', 64),
                ('give', 'cooked_beef', 16), ('give', 'torch', 32), ('give', 'water_bucket')],
         run=('&portal_room_run',), before=[('&built_stronghold',)], check=[('call', 'portal_room_found', [])],
         budget=25, raw=True, release=True, skills=['find_portal_room']),
    dict(name='loot_chest', module='loot',
         doc='A chest with 5 iron ingots and bread 6 blocks away → take the valuable stacks.',
         scene=[('floor', 'stone', 6, 2), ('chest', ('@', 5, 0, 1), 'iron_ingot 5', 'bread 4'), ('tp', ('@', -1, 0, 0)),
                ('cmd', 'clear @p')],
         run=('do', 'bonobo.loot.loot_chest', ['$ctx'], {}), check=[('count', 'minecraft:iron_ingot', '>=', 5)],
         budget=20, expect=[(('@', 5, 0, 1), ('@', 5, 0, 1), 'chest', 1, 1)], mod=['travel', 'use'],
         skills=['loot_chest']),
    dict(name='fall_without_bucket', module='perception',
         doc=("The same fall with no bucket (control): the fall hurts — dead, or health ≤ 10 — so water_clutch's pass "
              "is the bucket's doing"),
         scene=[('sheet', '_FALL_FLOOR')], run=('&wait_landed',),
         before=[('scene_now', [('stand', 0, 30)])],
         check=[('any', ('!state', 'dead'), ('!state', 'health', '<=', 10))], budget=15, stochastic=False,
         expect=[(('@', -6, -1, -6), ('@', 6, -1, 6), 'stone', 169, 169)]),
    dict(name='recover_items', module='reflexes',
         doc='Died 10 blocks away a minute ago, 3 diamonds lie there → walk back and pick them up.',
         scene=[('fill', ('@', -10, -2, -6), ('@', 12, -1, 6), 'stone'), ('tp', ('@', -6, 0, 0)), ('cmd', 'clear @p')],
         run=('do', 'bonobo.reflexes.recover_items', ['$ctx'], {}),
         before=[('seq', None, ('!remember', 'log_death', [('@', 6, 0, 0), 'minecraft:overworld'], {}),
                  ('!scene_now', [('summon', 'item', ('@', 6, 0, 0),
                                   '{Item:{id:"minecraft:diamond",count:3},Age:-32768}')]))],
         check=[('count', 'minecraft:diamond', '>=', 3)], budget=20,
         expect=[(('@', -10, -1, -6), ('@', 12, -1, 6), 'stone', 299, 299)], skills=['recover_items']),
    dict(name='relight_portal', module='nether',
         doc='A remembered portal frame whose fire went out, flint and steel → relight it and arrive in the Nether.',
         scene=[('floor', 'stone', 6, 2), ('fill', ('@', -1, 0, 4), ('@', 2, 4, 4), 'obsidian'),
                ('fill', ('@', 0, 1, 4), ('@', 1, 3, 4), 'air'), ('tp', ('@', 0, 0, -2)), ('cmd', 'clear @p'),
                ('give', 'flint_and_steel')],
         run=('do', 'bonobo.nether.use_portal', ['$ctx', 'minecraft:the_nether'], {}),
         before=[('remember', 'add_site', ['portal', ('@', 0, 1, 4), 'minecraft:overworld'], {'name': 'portal-test'})],
         check=[('state', 'dimension', '==', 'minecraft:the_nether')], budget=25,
         expect=[(('@', -1, 0, 4), ('@', 2, 4, 4), 'obsidian', 14, 14)], mod_extra=['state'], skills=['use_portal']),
    dict(name='retreat_from_nether', module='brain',
         doc='Nether, hurt to 6 hp with one food, the arrival portal 8 blocks away → upkeep retreats through it.',
         scene=[('floor', 'netherrack', 8, 2), ('fill', ('@', -1, 0, 6), ('@', 2, 4, 6), 'obsidian'),
                ('fill', ('@', 0, 1, 6), ('@', 1, 3, 6), 'nether_portal[axis=x]'), ('tp', ('@', 0, 0, -2)),
                ('cmd', 'clear @p'), ('give', 'cooked_beef', 1), ('give', 'cobblestone', 16)],
         run=('&snap_survival',), before=[('do', 'chat', ['damage @p 14 minecraft:generic'], {})],
         check=[('state', 'dimension', '==', 'minecraft:overworld')], budget=25, dimension='minecraft:the_nether',
         expect=[(('@', 0, 1, 6), ('@', 1, 3, 6), 'nether_portal', 6, 6)], mod_extra=['state'], skills=['use_portal']),
    dict(name='find_fortress_far', module='nether',
         doc='The real Nether: ~20 blocks from a fortress (lava sea likely between), blocks + food → fortress found.',
         scene=[('cmd', 'spreadplayers 0 0 0 8 under 90 false @p'), ('cmd', 'locate structure minecraft:fortress'),
                ('cmd', 'clear @p'), ('give', 'cobblestone', 128), ('give', 'diamond_pickaxe'),
                ('give', 'cooked_beef', 32), ('give', 'flint_and_steel'),
                ('cmd', 'item replace entity @p armor.head with golden_helmet'),
                ('cmd', 'item replace entity @p armor.chest with iron_chestplate')],
         run=('do', 'bonobo.nether.find_fortress', ['$ctx'], {}), before=[('&far_from_fortress',)],
         check=[('call', 'found_fortress_now', [])], budget=25, raw=True, combat=True, dimension='minecraft:the_nether',
         release=True, skills=['find_fortress']),
    dict(name='trek_overworld_30', module='nav',
         doc=('Real Overworld terrain (hills, forest, water), 30 blocks east (18 walked: arrival is 12 off), basic kit '
              '→ arrive; seconds per 100 blocks.'),
         scene=[('cmd', 'spreadplayers 10600 10600 0 4 false @p'), ('cmd', 'clear @p'), ('give', 'stone_pickaxe'),
                ('give', 'stone_axe'), ('give', 'cobblestone', 64), ('give', 'cooked_beef', 16), ('give', 'oak_boat')],
         run=('trek', 30, 0), check=[('call', 'trek_check', ['$api'])], detail=('&trek_detail',), budget=25, raw=True,
         release=True, mod=['travel']),
    dict(name='trek_nether_25', module='nav',
         doc=('Real Nether terrain below the roof, 25 blocks (13 walked), kit with gold helmet → arrive; seconds per '
              '100 blocks.'),
         scene=[('cmd', 'spreadplayers 300 300 0 8 under 90 false @p'), ('cmd', 'clear @p'),
                ('give', 'diamond_pickaxe'), ('give', 'cobblestone', 128), ('give', 'cooked_beef', 16),
                ('cmd', 'item replace entity @p armor.head with golden_helmet')],
         run=('trek', 25, 0), check=[('call', 'trek_check', ['$api'])], detail=('&trek_detail',), budget=25, raw=True,
         combat=True, dimension='minecraft:the_nether', release=True, mod=['travel']),
    dict(name='return_to_portal', module='nether',
         doc='The arrival portal 18 blocks away behind a stone wall, remembered as a site → back into it (Nether).',
         scene=[('fill', ('@', -8, -2, -8), ('@', 18, -1, 8), 'netherrack'),
                ('fill', ('@', 8, 0, -8), ('@', 8, 4, 5), 'netherrack'),
                ('fill', ('@', -2, 0, 0), ('@', 1, 4, 0), 'obsidian'),
                ('fill', ('@', -1, 1, 0), ('@', 0, 3, 0), 'nether_portal[axis=x]'), ('tp', ('@', 16, 0, 0)),
                ('cmd', 'clear @p'), ('give', 'diamond_pickaxe'), ('give', 'cobblestone', 32)],
         run=('do', 'bonobo.nether.use_portal', ['$ctx', 'minecraft:overworld'], {}),
         before=[('remember', 'add_site', ['portal', ('@', -1, 1, 1), 'minecraft:the_nether'],
                  {'name': 'portal-nether'})],
         check=[('state', 'dimension', '==', 'minecraft:overworld')], budget=25, dimension='minecraft:the_nether',
         expect=[(('@', -1, 1, 0), ('@', 0, 3, 0), 'nether_portal', 6, 6)], mod=['travel', 'use'], mod_extra=['state'],
         skills=['use_portal']),
    dict(name='slice_retreat', module='brain',
         doc=('Slice: in the Nether at 6 hp with one food, the arrival portal remembered 4 blocks away → back in the '
              'Overworld by the upkeep table, no loops.'),
         scene=[('fill', ('@', -8, -2, -8), ('@', 12, -1, 8), 'netherrack'),
                ('fill', ('@', 2, 0, -1), ('@', 2, 4, 2), 'obsidian'),
                ('fill', ('@', 2, 1, 0), ('@', 2, 3, 1), 'nether_portal[axis=z]'), ('tp', ('@', -2, 0, 0)),
                ('cmd', 'clear @p'), ('give', 'cooked_beef', 1), ('give', 'cobblestone', 16), ('give', 'iron_pickaxe')],
         run=('slice', ('&in_overworld',), 0.4, ('@', 2, 1, 0)),
         before=[('seq', None,
                  ('!remember', 'add_site', ['portal', ('@', 2, 1, 0), 'minecraft:the_nether'],
                   {'name': 'portal-nether'}),
                  ('!do', 'chat', ['damage @p 14 minecraft:generic'], {}))],
         check=[('slice_check', ('&in_overworld',))], detail=('&slice_detail',), budget=25,
         dimension='minecraft:the_nether', release=True,
         expect=[(('@', 2, 1, 0), ('@', 2, 3, 1), 'nether_portal', 6, 6)], point='C'),
    dict(name='cross_lava_3', module='nav',
         doc='A 3-block lava strip between two stone platforms; cobblestone → reach the far side alive.',
         scene=[('fill', ('@', -3, -3, -4), ('@', 9, -3, 4), 'stone'),
                ('fill', ('@', -2, -2, -3), ('@', 8, -1, 3), 'lava'),
                ('fill', ('@', -2, -1, -3), ('@', 1, -1, 3), 'stone'),
                ('fill', ('@', 5, -1, -3), ('@', 8, -1, 3), 'stone'), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'),
                ('give', 'cobblestone', 64), ('give', 'diamond_pickaxe')],
         run=('do', 'bonobo.nav.go_to', [('@', 6, 0, 0), ('$ctx', 'policy')], {'range_': 1.5}),
         check=[('call', 'near', ['$api', ('@', 6, 0, 0), 2.5]), ('state', 'health', '>', 10)], budget=22,
         expect=[(('@', 2, -1, -3), ('@', 4, -1, 3), 'lava', 21, 21),
                 (('@', -2, -1, -3), ('@', 1, -1, 3), 'stone', 28, 28), (('@', -2, 0, -3), ('@', 8, 4, 3), '*', 0, 0)],
         skills=['travel_to']),
    dict(name='gather_logs_birch', module='wood', doc='Two birches (taller, thin crowns); empty bag → 4 logs.',
         scene=[('fill', ('@', -8, -3, -8), ('@', 8, -2, 8), 'dirt'), ('grove',),
                ('at', 'place feature minecraft:birch {0}', ('@', 4, 0, 0)),
                ('at', 'place feature minecraft:birch {0}', ('@', -4, 0, 3)), ('tp', ('@', 0, 0, 0)),
                ('cmd', 'clear @p')],
         run=('do', 'bonobo.wood.chop', ['$ctx', 4], {}), check=[('count', 'log', '>=', 4)], budget=25,
         expect=[(('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block', 285, 289),
                 (('@', -8, 0, -8), ('@', 8, 8, 8), 'birch_log', 8, 20)],
         skills=['chop']),
    dict(name='build_light_portal_interrupted', module='building',
         doc=('flat stone, 10 obsidian, interrupted with 4 placed → resumed from the world: 10 in the frame, none in '
              'the bag, lit'),
         scene=[('floor', 'stone', 8, 2), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'), ('give', 'obsidian', 10),
                ('give', 'cobblestone', 16), ('give', 'flint_and_steel')],
         run=('resume', 'build_light_portal_interrupted',
              ('!do', 'bonobo.building.build_blueprint', ['$ctx', 'nether_portal', ('@', 0, 0, 0)], {}),
              ('!do', 'bonobo.building.build_blueprint', ['$ctx', 'nether_portal', ('@', 0, 0, 0)], {})),
         before=[('start', 'build_light_portal_interrupted'),
                 ('interrupt_when', ('!placed_at_least', ('@', -8, 0, -8), ('@', 8, 6, 8), 'obsidian', 4), None,
                  'bench: interrupt at the moment of success')],
         check=[('call', 'count_blocks', ['$api', ('@', -8, 0, -8), ('@', 8, 6, 8), 'nether_portal'], '>=', 6),
                ('blocks', ('@', -8, 0, -8), ('@', 8, 6, 8), ('obsidian',), 10, 10),
                ('count', 'minecraft:obsidian', '==', 0), ('interrupted',)],
         budget=25, skills=['build_blueprint'], tags={'base': 'build_blueprint', 'surprise': 'interrupt_mid_chain'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='boat_across_the_lake', module='nav',
         doc="A 6-block lake between two shores, a boat carried → across to the far shore (the jar's BoatDriver)",
         scene=[('fill', ('@', -4, -4, -6), ('@', 12, -4, 6), 'stone'),
                ('fill', ('@', -4, -3, -6), ('@', -1, -1, 6), 'stone'),
                ('fill', ('@', 6, -3, -6), ('@', 12, -1, 6), 'stone'),
                ('fill', ('@', 0, -3, -6), ('@', 5, -1, 6), 'water'), ('stand', -2), ('give', 'oak_boat')],
         run=('skill', 'travel_to', ('@', 7, 0, 0), 2), before=[('start', 'boat_across_the_lake')],
         check=[('_at', ('@', 7, 0, 0), 3), ('not', ('!state', 'inWater'))], budget=25, skills=['goto'],
         tier_fixed='exception', tags={'base': 'nav', 'terrain': 'lake'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='pearls_from_barter', module='decompose',
         doc='In the Nether, 2 gold ingots and a gold helmet, piglins 4 blocks off, no enderman → the plan barters',
         scene=[('floor', 'netherrack', 8, 2), ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
                ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'),
                ('cmd', 'item replace entity @p armor.feet with golden_boots'), ('give', 'gold_ingot', 2),
                ('give', 'golden_helmet'), ('give', 'iron_sword'),
                ('summon', 'piglin', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
                ('summon', 'piglin', ('@', -4, 0, 2), '{PersistenceRequired:1b}'),
                ('summon', 'piglin', ('@', 2, 0, -4), '{PersistenceRequired:1b}')],
         run=('achieve_needs', [('minecraft:ender_pearl', 1)], 4), before=[('start', 'pearls_from_barter')],
         check=[('count', 'minecraft:gold_ingot', '<', 2), ('call', 'trades', ['$inv'], '>=', 1)], budget=25, point='C',
         skills=['barter'], tier_fixed='exception', tags={'base': 'sources'}, dimension='minecraft:the_nether',
         combat=True, tick_rate=60, expect=[(('@', -8, -1, -8), ('@', 8, -1, 8), 'netherrack', 289, 289)],
         expect_entities=[('minecraft:piglin', 3)]),
    dict(name='farm__plant', module='farming',
         doc='grass, a hoe, 8 seeds, a water bucket → a plot made here: farmland round a watered centre, wheat sown',
         scene=[('floor', 'grass_block'), ('stand',), ('sheet', 'FARM_KIT')],
         run=('skill', 'plant_farm'), before=[('start', 'farm__plant')],
         check=[('blocks', ('@', -4, -1, -4), ('@', 4, -1, 4), ('farmland',), 1),
                ('blocks', ('@', -4, 0, -4), ('@', 4, 0, 4), ('wheat',), 1)],
         budget=25, point='C', skills=['farm'], tier_fixed='exception', tags={'base': 'sources', 'source': 'farm'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    # the growth is the game's: a ripe field placed by the console, so the row proves the plan's reap and bake, with
    # no wait on random ticks (the whole flow, sown to bread, ran past 25 s)
    dict(name='bread_from_a_farm', module='decompose',
         doc=("a ripe wheat field beside the body, no wheat carried → the plan's farm step reaps it (no new plot "
              'sown) and bakes: bread'),
         scene=[('floor', 'grass_block'), ('sheet', 'RIPE_PLOT'), ('stand',), ('sheet', 'FARM_KIT'),
                ('give', 'crafting_table')],       # the row proves the reap and the bake, not a table's logs
         run=('achieve_needs', [('minecraft:bread', 1)], 4), before=[('start', 'bread_from_a_farm')],
         check=[('gain', 'minecraft:bread', 1), ('blocks', ('@', 4, 0, -1), ('@', 6, 0, 1), ('wheat',), 0, 8),
                ('blocks', ('@', -8, -1, -8), ('@', 3, -1, 8), ('farmland',), 0, 0)],
         budget=25, point='C', skills=['farm'], tier_fixed='exception', tags={'base': 'sources', 'source': 'farm'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='await_collect_job', module='farming',
         doc='a remembered furnace job, due, its 3 ingots in the output 2 blocks off → awaited and collected',
         scene=[('floor',), ('setblock', ('@', 2, 0, 0), 'furnace'),
                ('at', 'item replace block {0} container.2 with iron_ingot 3', ('@', 2, 0, 0)), ('stand',)],
         run=('skill', 'await_job', 'minecraft:iron_ingot', 3),
         before=[('start', 'await_collect_job'), ('job_ready_at', ('@', 2, 0, 0), 'minecraft:iron_ingot', 3)],
         check=[('gain', 'minecraft:iron_ingot', 3)],
         budget=25, point='C', skills=['await_job'], tier_fixed='exception', tags={'base': 'sources', 'source': 'job'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='bread_from_a_farm_no_soil', module='decompose',
         doc='stone floor, the same kit → no plot can be made: the plan fails naming the soil (must fail, never a hang)',
         scene=[('floor',), ('stand',), ('sheet', 'FARM_KIT')],
         run=('expect_failure', 'bread_from_a_farm_no_soil', ('!achieve_needs', [('minecraft:bread', 1)], 3),
              'soil|no flat|farm'),
         before=[('start', 'bread_from_a_farm_no_soil')], check=[('same_bag',)], budget=25, point='C', skills=['farm'],
         tier_fixed='exception', tags={'base': 'sources', 'source': 'farm'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='emerald_from_a_villager', module='decompose',
         doc=('a farmer buying 20 wheat for an emerald, 20 wheat carried → the plan sells: an emerald gained, the '
              'wheat gone'),
         scene=[('floor',), ('stand',), ('give', 'wheat', 20),
                ('summon', 'villager', ('@', 3, 0, 0),
                 '{NoAI:1b,VillagerData:{profession:"minecraft:farmer",level:2,type:"minecraft:plains"},Offers:{Recipes:[{buy:{id:"minecraft:wheat",count:20},sell:{id:"minecraft:emerald",count:1},maxUses:12}]}}')],
         run=('achieve_needs', [('minecraft:emerald', 1)], 3), before=[('start', 'emerald_from_a_villager')],
         check=[('gain', 'minecraft:emerald', 1), ('count', 'minecraft:wheat', '==', 0)], budget=25, point='C',
         skills=['trade'], tier_fixed='exception', tags={'base': 'sources', 'source': 'trade'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='emerald_villager_without_the_trade', module='decompose',
         doc='a villager who only sells bread → no emerald offer: the trade ends naming it (must fail, never a hang)',
         scene=[('floor',), ('stand',), ('give', 'wheat', 20),
                ('summon', 'villager', ('@', 3, 0, 0),
                 '{NoAI:1b,VillagerData:{profession:"minecraft:farmer",level:2,type:"minecraft:plains"},Offers:{Recipes:[{buy:{id:"minecraft:emerald",count:1},sell:{id:"minecraft:bread",count:6},maxUses:12}]}}')],
         run=('expect_failure', 'emerald_villager_without_the_trade', ('!skill', 'trade', 'minecraft:emerald'),
              'no affordable|emerald trade'),
         before=[('start', 'emerald_villager_without_the_trade')], check=[('same_bag',)], budget=25, point='C',
         skills=['trade'], tier_fixed='exception', tags={'base': 'sources', 'source': 'trade'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='emerald_no_villager', module='decompose',
         doc='no villager anywhere, wheat carried → the trade fails naming it (must fail)',
         scene=[('floor',), ('stand',), ('give', 'wheat', 20)],
         run=('expect_failure', 'emerald_no_villager', ('!skill', 'trade', 'minecraft:emerald'), 'no villager'),
         before=[('start', 'emerald_no_villager')], check=[('same_bag',)], budget=25, point='C', skills=['trade'],
         tier_fixed='exception', tags={'base': 'sources', 'source': 'trade'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='water_bucket_from_the_plan', module='decompose',
         doc='An empty bucket, a pond 3 blocks off → the plan fills it (the fill producer): a water bucket held',
         scene=[('floor',), ('fill', ('@', 3, -1, -1), ('@', 4, -1, 1), 'water'), ('stand',), ('give', 'bucket')],
         run=('achieve_needs', [('minecraft:water_bucket', 1)], 3), before=[('start', 'water_bucket_from_the_plan')],
         check=[('gain', 'minecraft:water_bucket', 1)], budget=25, point='C', skills=['fill'], tier_fixed='exception',
         tags={'base': 'sources', 'source': 'fill'}, expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='night_mines_under_cover', module='brain',
         doc=('Night, sealed in a 1×2 hole 9 below the platform, a stone pickaxe, iron ore 3 below and 2 aside, '
              "nothing queued → the night's work is ore dug down to (brain.night_pick → descend), not waiting for day "
              'and not a climb to the surface'),
         scene=[('floor', 'stone', 6, 16), ('fill', ('@', 0, -9, 0), ('@', 0, -8, 0), 'air'),
                ('fill', ('@', 1, -13, 1), ('@', 2, -12, 2), 'iron_ore'), ('stand', 0, -9), ('cmd', 'clear @p'),
                ('give', 'stone_pickaxe'), ('give', 'cooked_beef', 8), ('give', 'cobblestone', 16), ('time', 13000)],
         run=('brain_rounds', 30, ('!now', ('!count', 'minecraft:raw_iron', '>=', 1))),
         before=[('start', 'night_mines_under_cover')],
         check=[('count', 'minecraft:raw_iron', '>=', 1), ('state', 'blockY', '<', 198)], budget=25, point='C',
         skills=['mine'], tier_fixed='exception', tags={'base': 'night'},
         expect=[(('@', 1, -13, 1), ('@', 2, -12, 2), 'iron_ore', 8, 8)]),
    dict(name='craft_chain_one_sitting', module='skills',
         doc=('3 logs and a table carried → planks, sticks and a wooden pickaxe crafted in one sitting (craft_chain: '
              'the table placed and taken back once, not per recipe)'),
         scene=[('floor',), ('stand',), ('cmd', 'clear @p'), ('give', 'oak_log', 3), ('give', 'crafting_table')],
         run=('skill', 'craft_chain', [('planks', 2), ('minecraft:stick', 1), ('minecraft:wooden_pickaxe', 1)]),
         before=[('start', 'craft_chain_one_sitting')], check=[('gain', 'minecraft:wooden_pickaxe', 1, 1)], budget=15,
         skills=['craft_chain'], tier_fixed='exception', tags={'base': 'craft'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
]
# -- one-off rows written in code (no word earns its place): kept as the old sheet wrote them ------------------------
from .vocab import *  # noqa: E402,F401,F403  (the words and helpers a one-off row is written in)

def _scene_of(name):
    """A tabled row's scene here, for a one-off row built on it."""
    for t, ps in FAMILIES:
        for p in ps:
            if t == "one" and p[0] == name:
                return scene(p[3])
    return scene(next(r["scene"] for r in ROWS if r["name"] == name))

def _expect_of(name):
    return next(r["expect"] for r in ROWS if r["name"] == name)

CODE_ROWS = [
    dict(name="activate_end_portal",
         doc="A stronghold portal ring, 9 frames with eyes and the 3 nearest empty, 3 eyes and a block → a block over "
             "the middle, stood on, the 3 eyes from there: an open end portal ≤ 3 s.",
         module="end", skills=["activate_end_portal"], mod=["travel", "use"], target_s=3.0,
         # 9 frames already hold an eye: the three on our side are the job, so the row fits the limit
         setup=[f"fill {_c(at(-6, -2, -6))} {_c(at(6, -1, 6))} stone_bricks",
                f"fill {_c(at(-1, 0, -2))} {_c(at(1, 0, -2))} end_portal_frame[facing=south]",
                f"fill {_c(at(-1, 0, 2))} {_c(at(1, 0, 2))} end_portal_frame[facing=north,eye=true]",
                f"fill {_c(at(-2, 0, -1))} {_c(at(-2, 0, 1))} end_portal_frame[facing=east,eye=true]",
                f"fill {_c(at(2, 0, -1))} {_c(at(2, 0, 1))} end_portal_frame[facing=west,eye=true]",
                f"fill {_c(at(-1, -1, -1))} {_c(at(1, -1, 1))} lava",
                # beside the ring, a block to put over the middle's lava (end.eye_plan)
                f"tp @p {_c(at(0, 0, -3))}", "clear @p", "give @p ender_eye 3", "give @p cobblestone 1"],
         expect=[(at(-2, 0, -2), at(2, 0, 2), "end_portal_frame", 12, 12)],
         # the speedrun standard from where the job is done: 12 eyes from one spot ≤ 3 s
         run=_timed(lambda ctx: _drain(__import__("bonobo.end", fromlist=["activate_end_portal"]).activate_end_portal(ctx))),
         # open: the 9 portal blocks, or already fallen through them (standing in the middle is the speedrun way)
         check=lambda api, inv: api.get("/state")["dimension"] == "minecraft:the_end"
         or _count_blocks(api, at(-1, 0, -1), at(1, 0, 1), "end_portal") == 9,
         budget=limit()),
    dict(name="gold_helmet_swap",
         doc="In the Nether wearing iron, a gold helmet in the bag → the reflex puts gold on (piglins stay neutral).",
         module="brain", dimension="minecraft:the_nether", mod=[],
         setup=[f"fill {_c(at(-6, -2, -6))} {_c(at(6, -1, 6))} netherrack",
                f"tp @p {_c(at(0, 0, 0))}", "clear @p", "item replace entity @p armor.head with iron_helmet",
                "give @p golden_helmet"],
         expect=[(at(-6, -1, -6), at(6, -1, 6), "netherrack", 169, 169)],
         run=lambda ctx: core.BRAIN.invariants(),
         check=lambda api, inv: _worn_head() == "minecraft:golden_helmet" and inv.count("minecraft:iron_helmet") >= 1,
         budget=10),
    dict(name="find_fortress",
         doc="Nether platform, a nether brick hall 18 blocks away → found and remembered as the fortress site.",
         module="nether", dimension="minecraft:the_nether", skills=["find_fortress"],
         setup=[f"fill {_c(at(-6, -2, -6))} {_c(at(20, -1, 6))} netherrack",
                f"fill {_c(at(16, 0, -3))} {_c(at(20, 4, 3))} nether_bricks hollow",
                f"tp @p {_c(at(0, 0, 0))}", "clear @p", "give @p cobblestone 32", "give @p cooked_beef 16"],
         expect=[(at(16, 0, -3), at(20, 4, 3), "nether_bricks", 60, 200)],
         run=lambda ctx: __import__("bonobo.nether", fromlist=["find_fortress"]).find_fortress(ctx),
         check=lambda api, inv: bool(__import__("bonobo.memory", fromlist=["Memory"]).Memory(NOTES)
                                     .sites("minecraft:the_nether", kinds=["fortress"])),
         budget=15),
    dict(name="road_reuse",
         doc="Overworld, 10 blocks there, back, there again → the third trip reuses the road and is no slower.",
         module="nav", raw=True, release=True,
         setup=["spreadplayers 11200 11200 0 4 false @p", "clear @p", "give @p stone_pickaxe",
                "give @p cobblestone 64", "give @p cooked_beef 16"],
         run=_road_reuse,
         check=lambda api, inv: len(ROAD_TIMES) == 3 and ROAD_TIMES[2] <= ROAD_TIMES[0] * 1.05,
         detail=lambda inv: "trips " + ", ".join(f"{t:.0f}s" for t in ROAD_TIMES),
         budget=limit()),
    one_row("smelt_in_background", ["start_smelt_job", "collect_job"], "load a furnace, walk off, come back → ingots",
            [("floor",), ("stand",), ("give", "furnace"), ("give", "raw_iron", 2), ("give", "coal", 1)],
            lambda ctx: (_skill("start_smelt_job")(ctx, "minecraft:iron_ingot", "minecraft:raw_iron", 2, "coal"),
                         _chat("tick sprint 400"), time.sleep(2),
                         _skill("collect_job")(ctx, ctx.mem.jobs("minecraft:overworld")[0]))[2],
            _gain("minecraft:iron_ingot", 2), limit()),
    one_row("repair_two_pickaxes", ["repair_tool"], "two worn stone pickaxes → one",
            [("floor",), ("stand",), ("give", "stone_pickaxe[damage=100]"), ("give", "stone_pickaxe[damage=100]")],
            lambda ctx: _skill("repair_tool")(ctx, "pickaxe"),
            lambda api, inv: inv.count("minecraft:stone_pickaxe") == 1 and any(
                s_["id"] == "minecraft:stone_pickaxe" and s_.get("damage", 999) < 100 for s_ in inv.slots), 20),
    one_row("anvil_repair_pickaxe", ["repair"], "an anvil, a worn diamond pickaxe, diamonds, levels → repaired",
            [("floor",), ("setblock", ("@", 2, 0, 0), "anvil"), ("stand",), ("give", "diamond_pickaxe[damage=1200]"),
             ("give", "diamond", 2), ("cmd", "experience add @p 20 levels")],
            lambda ctx: _skill("anvil_repair")(ctx, "minecraft:diamond_pickaxe", "minecraft:diamond"),
            lambda api, inv: any(s_["id"] == "minecraft:diamond_pickaxe" and s_.get("damage", 0) < 1200
                                 for s_ in inv.slots), limit()),
    real_row("explore_for_animals_real", ["explore_for"], "real terrain, two cows 16 blocks off → found",
             ("skill", "explore_for", ["minecraft:cow", "minecraft:sheep", "minecraft:pig"], 1, 20),
             # judged by what the skill found and noted, never by animals near at setup (the old check, "within 24",
             # held the moment the cows were summoned 16 off: the row passed in 0 s whatever the skill did)
             _remembered_any(["minecraft:cow", "minecraft:sheep", "minecraft:pig"]), limit(),
             [("cmd", "execute at @p run summon cow ~16 ~3 ~"), ("cmd", "execute at @p run summon cow ~16 ~3 ~1")],
             True, before=[_forget_all("minecraft:cow"), _forget_all("minecraft:sheep"), _forget_all("minecraft:pig")]),
    dict(name="fill_bottles_interrupted",
         doc="a pond, 3 glass bottles, interrupted at the first water bottle → resumed for the 2 left: exactly 3",
         module="skills", point="A", skills=["fill_bottles"],
         tags={"base": "fill_bottles", "surprise": "interrupt_mid_chain"},
         setup=_scene_of("fill_bottles_at_pond"),
         before=_hooks(_start("fill_bottles_interrupted"), _interrupt_when("minecraft:potion", 1)),
         run=_resume("fill_bottles_interrupted", lambda ctx: _skill("fill_bottles")(ctx, 3),
                     lambda ctx: _skill("fill_bottles")(
                         ctx, 3 - (_inv_now().count("minecraft:potion") - _base_count("minecraft:potion")))),
         check=_gain("minecraft:potion", 3, at_most=3), budget=limit(), expect=SHEET_EXPECT),
    dict(name="dead_flicker_on_respawn",
         doc="Killed at the start of the run: /state reads dead for a moment while the respawn loads — the brain must "
             "respawn, not call every skill dead, and still chop its 4 logs",
         module="brain", point="A", skills=["item:log"], tags={"base": "chop", "surprise": "dead_flicker"},
         setup=_grove((3, 0), (-3, 2)) + [_tp()],
         before=_hooks(_start("dead_flicker_on_respawn"), lambda ctx: _chat("kill @p")),
         run=lambda ctx: (_brain_rounds(15, lambda: not __import__("bonobo.api", fromlist=["get"]).get("/state")["dead"])(ctx),
                          _skill("chop")(ctx, 4))[1],
         check=_all(_alive(10), lambda api, inv: inv.count("log") >= 4), budget=limit(), expect=SHEET_EXPECT),
    # lava on a 3 s timer, not by progress: moved unchanged (the user's call)
    dict(name="interrupted_rescue_is_not_a_failure",
         doc="Chopping, then lava poured beside the body: the chop is interrupted (not failed), L0 moves away, the "
             "brain resumes and still gets its 4 logs",
         module="brain", point="B", skills=["item:log"], tags={"base": "chop", "hazard": "lava"},
         setup=_grove((3, 0)) + [_tp(), "give @p cobblestone 16"],
         before=_hooks(_start("interrupted_rescue_is_not_a_failure"),
                       lambda ctx: _threading.Timer(3.0, lambda: _chat(f"setblock {_c(at(0, 0, 1))} lava")).start()),
         run=_resume("interrupted_rescue_is_not_a_failure", lambda ctx: _skill("chop")(ctx, 4),
                     _achieve_needs([("log", 4)])),
         check=_all(_gain("log", 4), _alive(10)), budget=limit(), expect=SHEET_EXPECT),
    dict(name="nether_full_bag",
         doc="Nether platform, lava at feet level on the east, the bag full of netherrack and diamonds → tidied: "
             "slots freed, the netherrack thrown where it lands (on the ground, not in the lava), no diamond lost",
         module="skills", point="A", skills=["tidy_inventory"], tier_fixed="exception",
         dimension="minecraft:the_nether", stochastic=False, tags={"base": "tidy", "inventory": "full_bag"},
         setup=[f"fill {_c(at(-8, -2, -8))} {_c(at(8, -1, 8))} netherrack", _tp()] + NETHER_LAVA + ["give @p diamond 640"],
         before=_hooks(_start("nether_full_bag"), _fill_bag(0, "netherrack")),
         run=lambda ctx: _skill("tidy_inventory")(ctx),
         check=_all(_free_slots(3), _kept("minecraft:diamond"),
                    lambda api, inv: bool(__import__("bonobo.world", fromlist=["entities"]).entities(
                        10, ["minecraft:item"]))),
         budget=limit(), expect=SHEET_EXPECT),
    dict(name="portal_from_cast",
         doc="The queue asks for a portal: no obsidian carried, no diamond pickaxe, buckets, blocks and flint, a frame "
             "standing 8 of 10 (its bottom two missing), a lava pool memory knows 3 blocks off → the plan casts the "
             "two in place and lights it, the cast itself ≤ 5 s",
         module="decompose", point="C", skills=["cast:nether_portal"], tier_fixed="exception",
         tags={"base": "sources"},
         # both lava buckets carried: the trips to the pool are not the cast
         setup=_scene_of("cast_portal") + PORTAL_8_OF_10 + ["give @p lava_bucket", "give @p lava_bucket"],
         expect=[_scene_params(_expect_of("cast_portal")[0]), (at(-3, 0, 2), at(0, 4, 2), "obsidian", 8, 8)],
         before=_hooks(_start("portal_from_cast"), _forget_skill_time("cast_portal"),
                       lambda ctx: ctx.mem.note_seen("lava", at(3, -1, 0), "minecraft:overworld"),
                       _queue(__import__("bonobo.goals", fromlist=["make"]).make("build", bp="nether_portal"))),
         run=_brain_rounds(28, lambda: _count_blocks(None, at(-8, -1, -8), at(8, 6, 8), "nether_portal") >= 1),
         check=_all(lambda api, inv: _count_blocks(api, at(-8, -1, -8), at(8, 6, 8), "nether_portal") >= 1,
                    _skill_within("cast_portal", 5.0)),
         budget=limit()),
    dict(name="bucket_before_the_shaft",
         doc="An empty bucket, water 2 blocks off, the queue's head needs iron (dug down to) → the bucket is filled "
             "before any digging (WaterClutch needs it in hand)",
         module="needs", point="C", skills=["fill"], tier_fixed="exception", tags={"base": "upkeep"},
         setup=_floor(depth=4) + [f"setblock {_c(at(2, -1, 0))} water", _tp(), "clear @p", "give @p bucket",
                                  "give @p stone_pickaxe", "give @p cooked_beef 8", "give @p white_bed"],
         before=_hooks(_start("bucket_before_the_shaft"), _queue(__import__("bonobo.goals", fromlist=["have"]).have(
             ("minecraft:raw_iron", 1)))),
         run=_brain_rounds(22, lambda: _inv_now().count("minecraft:water_bucket") >= 1),
         # filled, and nothing dug down: the feet still on their floor
         check=_all(lambda api, inv: inv.count("minecraft:water_bucket") >= 1,
                    lambda api, inv: api.get("/state")["blockY"] >= at(0, 0, 0)[1]),
         budget=limit(), expect=SHEET_EXPECT),
]
