"""Bench table, core tier: every row as plain data in `bench/vocab.py`'s words, run through `bench/table.py`.
Written from the old sheet (scenarios.SCENARIOS) by `bench/tabulate.py`; tests/test_bench_tables.py proves each row
builds back to the old one (setup, queue, budget, tier, and the same words for run, check and hooks). Not wired to
the runner yet. NOT_EXPRESSED: the old rows whose code has no words here yet, with the reason."""


ROWS = [
    {'name': 'iron_ingots',
     'module': 'skills',
     'doc': 'Stone room, 3 furnaces placed side by side, 3 raw iron + 3 coal carried → 3 iron ingots, one per '
            'furnace in parallel (load, start, wait, collect).',
     'scene': [('fill', ('@', -8, -4, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, 0, -1), ('@', 2, 0, 1), 'furnace'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'raw_iron', 3),
               ('give', 'coal', 3)],
     'run': ('do',
             'achieve',
             ['$ctx', [('minecraft:iron_ingot', 3)], ('!inv_has', 'minecraft:iron_ingot', 3)],
             {'rounds': 10}),
     'before': [('start', 'iron_ingots'), ('sprint_after', 4, 700), ('sprint_after', 10, 700)],
     'check': [('count', 'minecraft:iron_ingot', '>=', 3), ('count', 'minecraft:raw_iron', '==', 0)],
     'budget': 25,
     'expect': [(('@', 2, 0, -1), ('@', 2, 0, 1), 'furnace', 3, 3)],
     'tick_rate': 60,
     'point': 'C',
     'chain': 1,
     'skills': ['load_smelter', 'start_smelt_job', 'smelt']},
    {'name': 'water_clutch',
     'module': 'perception',
     'doc': 'Dropped 30 blocks above stone, a water bucket in the main bag (not the hotbar) → water poured in time '
            '(health ≥ 16) and scooped back (the bucket full again)',
     'scene': [('fill', ('@', -6, -2, -6), ('@', 6, -1, 6), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'dirt', 576),
               ('give', 'water_bucket')],
     'run': ('&wait_landed',),
     'before': [('do', 'chat', ['tp @p 10000.5 230 10000.5'], {})],
     'check': [('state', 'health', '>=', 16),
               ('not', ('!state', 'dead')),
               ('count', 'minecraft:water_bucket', '>=', 1)],
     'budget': 15,
     'stochastic': False,
     'expect': [(('@', -6, -1, -6), ('@', 6, -1, 6), 'stone', 169, 169)],
     'mod': ['nets', 'use'],
     'point': 'B',
     'skills': []},
    {'name': 'slice_start_tools',
     'module': 'brain',
     'doc': 'Slice: the whole cerebellum, a crafting table beside it, planks, sticks and 3 cobblestone carried, a '
            'pickaxe asked → the wooden-then-stone chain by crafting alone, a stone pickaxe in the bag, no loops '
            "(core: what gathering costs is the other rows' job).",
     'scene': [('fill', ('@', -6, -2, -6), ('@', 6, -1, 6), 'stone'),
               ('setblock', ('@', 1, 0, 1), 'crafting_table'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('cmd', 'time set day'),
               ('give', 'oak_planks', 6),
               ('give', 'stick', 4),
               ('give', 'cobblestone', 3)],
     'run': ('slice',
             ('&has_stone_pickaxe',),
             0.5,
             None,
             [{'goal': 'have', 'args': {'needs': [['tool', 'pickaxe', 1]]}}]),
     'check': [('slice_check', ('&has_stone_pickaxe',))],
     'detail': ('&slice_detail',),
     'budget': 25,
     'expect': [(('@', 1, 0, 1), ('@', 1, 0, 1), 'crafting_table', 1, 1)],
     'point': 'C',
     'chain': 0,
     'skills': []},
    {'name': 'nav__base',
     'module': 'skills',
     'doc': 'walk 8 blocks east over the arena — as is',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 10, -1, 3), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('skill', 'travel_to', ('@', 8, 0, 0), 2),
     'before': [('start', 'nav__base')],
     'check': [('_at', ('@', 8, 0, 0), 3.5)],
     'budget': 15,
     'skills': ['goto'],
     'point': 'A',
     'tags': {'base': 'nav'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'chop__base',
     'module': 'skills',
     'doc': 'one oak beside the body → 2 logs — as is',
     'scene': [('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 2, 0),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'diamond_axe')],
     'run': ('timed', ('!skill', 'chop', 2)),
     'before': [('start', 'chop__base')],
     'check': [('gain', 'log', 2)],
     'budget': 15,
     'target_s': 15.0,
     'skills': ['item:log'],
     'point': 'A',
     'tags': {'base': 'chop'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'mine_stone__base',
     'module': 'skills',
     'doc': 'stone floor, a wooden pickaxe → 3 cobblestone — as is',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wooden_pickaxe'),
               ('give', 'diamond_pickaxe')],
     'run': ('timed', ('!skill', 'mine', 'minecraft:cobblestone', 3, ['stone'], 0)),
     'before': [('start', 'mine_stone__base')],
     'check': [('gain', 'minecraft:cobblestone', 3)],
     'budget': 15,
     'target_s': 12.0,
     'skills': ['mine'],
     'point': 'A',
     'tags': {'base': 'mine_stone'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'mine_iron__base',
     'module': 'skills',
     'doc': "one iron ore in a stone wall at arm's length, a stone pickaxe → 1 raw iron — as is",
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, 0, -1), ('@', 3, 2, 1), 'stone'),
               ('setblock', ('@', 2, 0, 0), 'iron_ore'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'mine', 'minecraft:raw_iron', 1, ['iron_ore'], 1),
     'before': [('start', 'mine_iron__base')],
     'check': [('gain', 'minecraft:raw_iron', 1)],
     'budget': 15,
     'skills': ['mine'],
     'point': 'A',
     'tags': {'base': 'mine_iron'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'craft__base',
     'module': 'skills',
     'doc': 'planks, sticks, a table carried → a wooden pickaxe — as is',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_planks', 8),
               ('give', 'stick', 4),
               ('give', 'crafting_table')],
     'run': ('timed', ('!skill', 'craft', 'minecraft:wooden_pickaxe', 1)),
     'before': [('start', 'craft__base')],
     'check': [('gain', 'minecraft:wooden_pickaxe', 1, 1)],
     'budget': 15,
     'target_s': 12.0,
     'skills': ['craft'],
     'point': 'A',
     'tags': {'base': 'craft'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'smelt__base',
     'module': 'skills',
     'doc': 'a furnace, 1 raw iron, coal → 1 iron ingot — as is',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'furnace'),
               ('give', 'raw_iron', 1),
               ('give', 'coal', 1)],
     'run': ('skill', 'smelt', 'minecraft:iron_ingot', 'minecraft:raw_iron', 1, 'coal'),
     'before': [('start', 'smelt__base'), ('sprint_after', 3, 400)],
     'check': [('gain', 'minecraft:iron_ingot', 1, 1)],
     'budget': 15,
     'skills': ['smelt'],
     'point': 'A',
     'tags': {'base': 'smelt'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'hunt__base',
     'module': 'skills',
     'doc': 'a pen of three cows, a sword → 1 beef — as is',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', -5, 0, -5), ('@', 5, 0, -5), 'oak_fence'),
               ('fill', ('@', -5, 0, 5), ('@', 5, 0, 5), 'oak_fence'),
               ('fill', ('@', -5, 0, -4), ('@', -5, 0, 4), 'oak_fence'),
               ('fill', ('@', 5, 0, -4), ('@', 5, 0, 4), 'oak_fence'),
               ('summon', 'cow', ('@', 3, 0, 2)),
               ('summon', 'cow', ('@', -3, 0, 2)),
               ('summon', 'cow', ('@', 2, 0, -4)),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'iron_sword')],
     'run': ('skill', 'hunt', 'minecraft:beef', 1, ['minecraft:cow'], False),
     'before': [('start', 'hunt__base')],
     'check': [('gain', 'minecraft:beef', 1)],
     'budget': 15,
     'skills': ['hunt'],
     'point': 'A',
     'tags': {'base': 'hunt'},
     'expect_entities': [('minecraft:cow', 3)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'sleep__base',
     'module': 'skills',
     'doc': 'night, a bed carried → morning — as is',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'white_bed'),
               ('time', 18000)],
     'run': ('skill', 'sleep', ('$ctx', 'policy')),
     'before': [('start', 'sleep__base')],
     'check': [('is_day',)],
     'budget': 15,
     'skills': ['sleep'],
     'point': 'A',
     'tags': {'base': 'sleep'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'loot__base',
     'module': 'skills',
     'doc': 'a chest of iron and bread 2 blocks away → the iron — as is',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 2, 0, 1), 'chest'),
               ('at', 'item replace block {0} container.0 with iron_ingot 5', ('@', 2, 0, 1)),
               ('at', 'item replace block {0} container.1 with bread 4', ('@', 2, 0, 1)),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('skill', 'loot_chest'),
     'before': [('start', 'loot__base')],
     'check': [('gain', 'minecraft:iron_ingot', 5)],
     'budget': 15,
     'skills': ['loot_chest'],
     'point': 'A',
     'tags': {'base': 'loot'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'bed_in_nether',
     'module': 'skills',
     'doc': 'night, a bed carried → morning — night in the Nether, a bed carried: must refuse (it explodes)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'netherrack'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'white_bed'),
               ('time', 18000)],
     'run': ('expect_failure', 'bed_in_nether', ('!skill', 'sleep', ('$ctx', 'policy')), 'nether|dimension|explod'),
     'before': [('start', 'bed_in_nether')],
     'check': [('failed_as_expected',),
               ('alive',),
               ('all', ('!alive', 18), ('!no_block_suffix', ('@', -4, -1, -4), ('@', 4, 2, 4), '_bed'))],
     'budget': 15,
     'skills': ['sleep'],
     'point': 'A',
     'tags': {'base': 'sleep', 'surprise': 'bed_in_nether'},
     'fails': 'nether|dimension|explod',
     'dimension': 'minecraft:the_nether',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'lava_edge_walk',
     'module': 'nav',
     'doc': 'A 1-wide stone path between two lava pools to a target 12 blocks on → there, not burnt',
     'scene': [('fill', ('@', -3, -3, -4), ('@', 15, -1, 4), 'stone'),
               ('fill', ('@', 0, -1, -3), ('@', 13, -1, -1), 'lava'),
               ('fill', ('@', 0, -1, 1), ('@', 13, -1, 3), 'lava'),
               ('tp', ('@', -0.5, 0, 0.5)),
               ('give', 'cobblestone', 32)],
     'run': ('skill', 'travel_to', ('@', 14, 0, 0), 1.5),
     'before': [('start', 'lava_edge_walk')],
     'check': [('_at', ('@', 14, 0, 0), 2.5), ('alive', 16)],
     'budget': 25,
     'point': 'B',
     'skills': ['goto'],
     'tags': {'base': 'nav', 'hazard': 'lava'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'buried_by_sand',
     'module': 'brain',
     'doc': "Sand dropped on the body mid-task → L0 rescues (unbury) through the brain's own round, then alive",
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('give', 'diamond_shovel')],
     'run': ('brain_rounds', 15, ('&head_clear',)),
     'before': [('start', 'buried_by_sand'), ('do', 'chat', ['fill 10000 200 10000 10000 203 10000 sand'], {})],
     'check': [('call', 'head_clear', []), ('alive', 10)],
     'budget': 20,
     'point': 'B',
     'skills': ['unbury'],
     'tags': {'base': 'l0', 'hazard': 'suffocating'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'drowning_in_a_pit',
     'module': 'brain',
     'doc': 'Deep in a flooded shaft with little air → L0 surfaces (find_air / surface) before anything else: on '
            'the rim, or breathing with the head out for 2 s',
     'scene': [('fill', ('@', -2, -4, -2), ('@', 2, -4, 2), 'stone'),
               ('fill', ('@', -2, -3, -2), ('@', 2, 3, -2), 'stone'),
               ('fill', ('@', -2, -3, 2), ('@', 2, 3, 2), 'stone'),
               ('fill', ('@', -2, -3, -2), ('@', -2, 3, 2), 'stone'),
               ('fill', ('@', 2, -3, -2), ('@', 2, 3, 2), 'stone'),
               ('fill', ('@', -1, -3, -1), ('@', 1, 3, 1), 'water'),
               ('fill', ('@', -4, 4, -4), ('@', 4, 4, 4), 'stone'),
               ('fill', ('@', -1, 4, -1), ('@', 1, 4, 1), 'water'),
               ('fill', ('@', -4, 5, -4), ('@', 4, 7, 4), 'air'),
               ('tp', ('@', 0.5, -3, 0.5))],
     'run': ('brain_rounds', 28, ('!now_api', ('!surfaced', 4, 0))),
     'before': [('start', 'drowning_in_a_pit')],
     'check': [('alive', 8), ('surfaced', 4)],
     'budget': 25,
     'point': 'B',
     'skills': ['reach:air'],
     'tags': {'base': 'l0', 'hazard': 'drowning'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
]

NOT_EXPRESSED = {
    'eat__base': "<lambda>: a lambda; a run that is not one call: (_chat('effect give @p minecraft:hunger 5 255 true'), time.s",
}
