"""Bench table, brain tier: every row as plain data in `bench/vocab.py`'s words, run through `bench/table.py`.
Written from the old sheet (scenarios.SCENARIOS) by `bench/tabulate.py`; tests/test_bench_tables.py proves each row
builds back to the old one (setup, queue, budget, tier, and the same words for run, check and hooks). Not wired to
the runner yet. NOT_EXPRESSED: the old rows whose code has no words here yet, with the reason."""


ROWS = [
    {'name': 'plan_repair_on_event',
     'module': 'brain',
     'doc': 'Planks + cobblestone + a wooden pickaxe carried (upkeep quiet), a stone pickaxe asked; the table the '
            'plan puts down is taken away → that step is redone, the plan is not started over (≤ 2 plans)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_planks', 12),
               ('give', 'cobblestone', 3),
               ('give', 'wooden_pickaxe')],
     'queue': [{'goal': 'have', 'args': {'needs': [['tool', 'pickaxe', 1]]}}],
     'run': ('slice',
             ('!now', ('!count', 'minecraft:stone_pickaxe', '>=', 1)),
             0.4,
             None,
             [{'goal': 'have', 'args': {'needs': [['tool', 'pickaxe', 1]]}}]),
     'before': [('start', 'plan_repair_on_event'), ('&count_replans',), ('&remove_table_when_placed',)],
     'check': [('all', ('!count', 'minecraft:stone_pickaxe', '>=', 1), ('!replans_at_most', 2)),
               ('slice_check', None)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'brain'},
     'variant': ['_count_replans', '_remove_table_when_placed'],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'plan_without_events',
     'module': 'brain',
     'doc': 'The same with nothing taken away → one plan (control)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_planks', 12),
               ('give', 'cobblestone', 3),
               ('give', 'wooden_pickaxe')],
     'queue': [{'goal': 'have', 'args': {'needs': [['tool', 'pickaxe', 1]]}}],
     'run': ('slice',
             ('!now', ('!count', 'minecraft:stone_pickaxe', '>=', 1)),
             0.4,
             None,
             [{'goal': 'have', 'args': {'needs': [['tool', 'pickaxe', 1]]}}]),
     'before': [('start', 'plan_without_events'), ('&count_replans',)],
     'check': [('all', ('!count', 'minecraft:stone_pickaxe', '>=', 1), ('!replans_at_most', 1)),
               ('slice_check', None)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'brain'},
     'variant': ['_count_replans'],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'ban_then_other_source',
     'module': 'brain',
     'doc': 'Two iron ores, one sealed in barrier → that cell is banned, the other is mined',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', -5, -1, -1), ('@', -3, 1, 1), 'barrier'),
               ('setblock', ('@', -4, 0, 0), 'iron_ore'),
               ('setblock', ('@', 4, 0, 0), 'iron_ore'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('give', 'diamond_pickaxe')],
     'queue': [{'goal': 'have', 'args': {'needs': [['minecraft:raw_iron', 1]]}}],
     'run': ('slice',
             ('!_count', 'minecraft:raw_iron', 1),
             0.4,
             None,
             [{'goal': 'have', 'args': {'needs': [['minecraft:raw_iron', 1]]}}]),
     'before': [('start', 'ban_then_other_source'), ('&clear_bans',)],
     'check': [('all',
                ('!gain', 'minecraft:raw_iron', 1),
                ('!blocks', ('@', -4, 0, 0), ('@', -4, 0, 0), ('iron_ore',), 1, 1),
                ('!blocks', ('@', 4, 0, 0), ('@', 4, 0, 0), ('iron_ore',), 0, 0)),
               ('slice_check', None)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'brain'},
     'variant': ['_clear_bans'],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'chop_without_interrupt',
     'module': 'brain',
     'doc': 'The same with no zombie → no fight is logged, the same 4 logs (control)',
     'scene': [('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 3, 0),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'diamond_axe'),
               ('give', 'oak_log', 2),
               ('give', 'diamond_axe')],
     'queue': [{'goal': 'have', 'args': {'needs': [['log', 4]]}}],
     'run': ('slice',
             ('!now', ('!count', 'log', '>=', 4)),
             0.4,
             None,
             [{'goal': 'have', 'args': {'needs': [['log', 4]]}}]),
     'before': [('start', 'chop_without_interrupt')],
     'check': [('all', ('!count', 'log', '>=', 4), ('!hp_kept', 20), ('!gone', ['minecraft:zombie'])),
               ('slice_check', None)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'brain'},
     'variant': [],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'brain__tight',
     'module': 'brain',
     'doc': 'night_first+night_under: dusk tight, food full, tool fresh, head surface, seen none, bag room → dusk '
            'or night on the surface, no bed: the night first; dusk or night on the surface: a bed first',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'grass_block'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -8, -12, -8), ('@', 8, -3, 8), 'stone'),
               ('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 3, 3),
               ('fill', ('@', 0, -9, 0), ('@', 0, -8, 0), 'air'),
               ('fill', ('@', 1, -11, 1), ('@', 2, -10, 2), 'iron_ore'),
               ('fill', ('@', 5, 0, -1), ('@', 7, 2, 1), 'stone'),
               ('fill', ('@', 1, 0, -3), ('@', 3, 2, -1), 'stone'),
               ('setblock', ('@', 2, 0, -2), 'diamond_ore'),
               ('setblock', ('@', 4, -9, 0), 'diamond_ore'),
               ('setblock', ('@', -2, 0, 0), 'furnace'),
               ('give', 'white_wool', 3),
               ('give', 'oak_planks', 8),
               ('give', 'crafting_table'),
               ('give', 'stick', 4),
               ('give', 'iron_ingot', 3),
               ('give', 'beef', 2),
               ('give', 'coal', 2),
               ('give', 'cobblestone', 16),
               ('give', 'diamond_axe'),
               ('time', 11930),
               ('give', 'iron_pickaxe'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'diamond_axe')],
     'queue': [{'goal': 'have', 'args': {'needs': [['log', 2]]}}],
     'run': ('slice', None, 0.4, None, [{'goal': 'have', 'args': {'needs': [['log', 2]]}}]),
     'before': [('start', 'brain__tight'),
                ('&clear_bans',),
                ('forget_all', 'diamond_ore'),
                ('&first_times',),
                ('&count_finds',)],
     'check': [('before_in_bag', 'bed', 'log'),
               ('before_in_bag', 'bed', 'minecraft:raw_iron', True),
               ('slice_check', None)],
     'why': ['dusk or night on the surface, no bed: the night first',
             'dusk or night on the surface: a bed first',
             'the slice'],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'brain',
              'family': 'night_first+night_under',
              'dusk': 'tight',
              'food': 'full',
              'tool': 'fresh',
              'head': 'surface',
              'seen': 'none',
              'bag': 'room'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'brain__night',
     'module': 'brain',
     'doc': 'night_first+night_under: dusk night, food full, tool fresh, head surface, seen none, bag room → dusk '
            'or night on the surface, no bed: the night first; dusk or night on the surface: a bed first',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'grass_block'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -8, -12, -8), ('@', 8, -3, 8), 'stone'),
               ('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 3, 3),
               ('fill', ('@', 0, -9, 0), ('@', 0, -8, 0), 'air'),
               ('fill', ('@', 1, -11, 1), ('@', 2, -10, 2), 'iron_ore'),
               ('fill', ('@', 5, 0, -1), ('@', 7, 2, 1), 'stone'),
               ('fill', ('@', 1, 0, -3), ('@', 3, 2, -1), 'stone'),
               ('setblock', ('@', 2, 0, -2), 'diamond_ore'),
               ('setblock', ('@', 4, -9, 0), 'diamond_ore'),
               ('setblock', ('@', -2, 0, 0), 'furnace'),
               ('give', 'white_wool', 3),
               ('give', 'oak_planks', 8),
               ('give', 'crafting_table'),
               ('give', 'stick', 4),
               ('give', 'iron_ingot', 3),
               ('give', 'beef', 2),
               ('give', 'coal', 2),
               ('give', 'cobblestone', 16),
               ('give', 'diamond_axe'),
               ('time', 18000),
               ('give', 'iron_pickaxe'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'diamond_axe')],
     'queue': [{'goal': 'have', 'args': {'needs': [['log', 2]]}}],
     'run': ('slice', None, 0.4, None, [{'goal': 'have', 'args': {'needs': [['log', 2]]}}]),
     'before': [('start', 'brain__night'),
                ('&clear_bans',),
                ('forget_all', 'diamond_ore'),
                ('&first_times',),
                ('&count_finds',)],
     'check': [('before_in_bag', 'bed', 'log'),
               ('before_in_bag', 'bed', 'minecraft:raw_iron', True),
               ('slice_check', None)],
     'why': ['dusk or night on the surface, no bed: the night first',
             'dusk or night on the surface: a bed first',
             'the slice'],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'brain',
              'family': 'night_first+night_under',
              'dusk': 'night',
              'food': 'full',
              'tool': 'fresh',
              'head': 'surface',
              'seen': 'none',
              'bag': 'room'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'tidy_then_task__junk_full',
     'module': 'brain',
     'doc': 'tidy_then_task: dusk plenty, food full, tool fresh, head surface, seen none, bag junk_full → a bag '
            'past BAG_FULL, junk: junk thrown, then the task done',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'grass_block'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -8, -12, -8), ('@', 8, -3, 8), 'stone'),
               ('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 3, 3),
               ('fill', ('@', 0, -9, 0), ('@', 0, -8, 0), 'air'),
               ('fill', ('@', 1, -11, 1), ('@', 2, -10, 2), 'iron_ore'),
               ('fill', ('@', 5, 0, -1), ('@', 7, 2, 1), 'stone'),
               ('fill', ('@', 1, 0, -3), ('@', 3, 2, -1), 'stone'),
               ('setblock', ('@', 2, 0, -2), 'diamond_ore'),
               ('setblock', ('@', 4, -9, 0), 'diamond_ore'),
               ('setblock', ('@', -2, 0, 0), 'furnace'),
               ('give', 'white_wool', 3),
               ('give', 'oak_planks', 8),
               ('give', 'crafting_table'),
               ('give', 'stick', 4),
               ('give', 'iron_ingot', 3),
               ('give', 'beef', 2),
               ('give', 'coal', 2),
               ('give', 'cobblestone', 16),
               ('give', 'diamond_axe'),
               ('time', 1000),
               ('give', 'iron_pickaxe'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('tp', ('@', 6.5, 0, 3.5)),
               ('give', 'diamond_axe')],
     'queue': [{'goal': 'have', 'args': {'needs': [['log', 2]]}}],
     'run': ('slice', None, 0.4, None, [{'goal': 'have', 'args': {'needs': [['log', 2]]}}]),
     'before': [('fill_bag', 0),
                ('start', 'tidy_then_task__junk_full'),
                ('&clear_bans',),
                ('forget_all', 'diamond_ore'),
                ('&first_times',),
                ('&count_finds',)],
     'check': [('all', ('!gain', 'log', 2), ('!count', 'minecraft:dirt', '<', 0)), ('slice_check', None)],
     'why': ['a bag past BAG_FULL, junk: junk thrown, then the task done', 'the slice'],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'brain',
              'family': 'tidy_then_task',
              'dusk': 'plenty',
              'food': 'full',
              'tool': 'fresh',
              'head': 'surface',
              'seen': 'none',
              'bag': 'junk_full'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'tidy_then_task__valuables_full',
     'module': 'brain',
     'doc': 'tidy_then_task: dusk plenty, food full, tool fresh, head surface, seen none, bag valuables_full → a '
            'bag of diamonds: not one thrown to make room (must not)',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'grass_block'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -8, -12, -8), ('@', 8, -3, 8), 'stone'),
               ('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 3, 3),
               ('fill', ('@', 0, -9, 0), ('@', 0, -8, 0), 'air'),
               ('fill', ('@', 1, -11, 1), ('@', 2, -10, 2), 'iron_ore'),
               ('fill', ('@', 5, 0, -1), ('@', 7, 2, 1), 'stone'),
               ('fill', ('@', 1, 0, -3), ('@', 3, 2, -1), 'stone'),
               ('setblock', ('@', 2, 0, -2), 'diamond_ore'),
               ('setblock', ('@', 4, -9, 0), 'diamond_ore'),
               ('setblock', ('@', -2, 0, 0), 'furnace'),
               ('give', 'white_wool', 3),
               ('give', 'oak_planks', 8),
               ('give', 'crafting_table'),
               ('give', 'stick', 4),
               ('give', 'iron_ingot', 3),
               ('give', 'beef', 2),
               ('give', 'coal', 2),
               ('give', 'cobblestone', 16),
               ('give', 'diamond_axe'),
               ('time', 1000),
               ('give', 'iron_pickaxe'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'diamond_axe')],
     'queue': [{'goal': 'have', 'args': {'needs': [['log', 2]]}}],
     'run': ('slice', None, 0.4, None, [{'goal': 'have', 'args': {'needs': [['log', 2]]}}]),
     'before': [('fill_bag', 0, 'diamond'),
                ('start', 'tidy_then_task__valuables_full'),
                ('&clear_bans',),
                ('forget_all', 'diamond_ore'),
                ('&first_times',),
                ('&count_finds',)],
     'check': [('kept', 'minecraft:diamond'), ('slice_check', None)],
     'why': ['a bag of diamonds: not one thrown to make room (must not)', 'the slice'],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'brain',
              'family': 'tidy_then_task',
              'dusk': 'plenty',
              'food': 'full',
              'tool': 'fresh',
              'head': 'surface',
              'seen': 'none',
              'bag': 'valuables_full'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'seen_store__noted',
     'module': 'brain',
     'doc': 'seen_store: dusk plenty, food full, tool fresh, head surface, seen noted, bag room → noted: straight '
            'there without a scan (must not scan), the note retired',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'grass_block'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -8, -12, -8), ('@', 8, -3, 8), 'stone'),
               ('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 3, 3),
               ('fill', ('@', 0, -9, 0), ('@', 0, -8, 0), 'air'),
               ('fill', ('@', 1, -11, 1), ('@', 2, -10, 2), 'iron_ore'),
               ('fill', ('@', 5, 0, -1), ('@', 7, 2, 1), 'stone'),
               ('fill', ('@', 1, 0, -3), ('@', 3, 2, -1), 'stone'),
               ('setblock', ('@', 2, 0, -2), 'diamond_ore'),
               ('setblock', ('@', 4, -9, 0), 'diamond_ore'),
               ('setblock', ('@', -2, 0, 0), 'furnace'),
               ('give', 'white_wool', 3),
               ('give', 'oak_planks', 8),
               ('give', 'crafting_table'),
               ('give', 'stick', 4),
               ('give', 'iron_ingot', 3),
               ('give', 'beef', 2),
               ('give', 'coal', 2),
               ('give', 'cobblestone', 16),
               ('give', 'diamond_axe'),
               ('time', 1000),
               ('give', 'iron_pickaxe'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'diamond_pickaxe')],
     'queue': [{'goal': 'have', 'args': {'needs': [['minecraft:diamond', 1]]}}],
     'run': ('slice', None, 0.4, None, [{'goal': 'have', 'args': {'needs': [['minecraft:diamond', 1]]}}]),
     'before': [('start', 'seen_store__noted'),
                ('&clear_bans',),
                ('forget_all', 'diamond_ore'),
                ('&first_times',),
                ('seen', 'diamond_ore', ('@', 2, 0, -2)),
                ('&count_finds',)],
     'check': [('all', ('!gain', 'minecraft:diamond', 1), ('!not_remembered', 'diamond_ore'), ('!no_scan',)),
               ('slice_check', None)],
     'why': ['noted: straight there without a scan (must not scan), the note retired', 'the slice'],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'brain',
              'family': 'seen_store',
              'dusk': 'plenty',
              'food': 'full',
              'tool': 'fresh',
              'head': 'surface',
              'seen': 'noted',
              'bag': 'room'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__dig_out',
     'module': 'reflexes',
     'doc': 'upkeep, daytime, sealed in stone with a pickaxe → out, not enclosed',
     'scene': [('fill', ('@', -4, -2, -4), ('@', 4, 3, 4), 'stone'),
               ('fill', ('@', 0, 0, 0), ('@', 0, 1, 0), 'air'),
               ('tp', ('@', 1.0, 0, 1.0)),
               ('give', 'stone_pickaxe')],
     'run': ('brain_rounds', 22, ('!now', ('!not', ('!call', 'enclosed', [])))),
     'before': [('start', 'upkeep__dig_out')],
     'check': [('not', ('!call', 'enclosed', []))],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'dig_out'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__collect_job',
     'module': 'reflexes',
     'doc': 'upkeep, a finished background smelt remembered at a furnace 2 blocks off → the ingots in the bag',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 2, 0, 0), 'furnace'),
               ('at', 'item replace block {0} container.2 with iron_ingot 3', ('@', 2, 0, 0)),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('brain_rounds', 22, ('!_count', 'minecraft:iron_ingot', 3)),
     'before': [('start', 'upkeep__collect_job'), ('job_ready_at', ('@', 2, 0, 0), 'minecraft:iron_ingot', 3)],
     'check': [('gain', 'minecraft:iron_ingot', 3)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'collect_job'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__empty_the_bag',
     'module': 'reflexes',
     'doc': 'upkeep, a full bag (dirt in every slot) → room made',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'dirt', 2304),
               ('give', 'stone_pickaxe')],
     'run': ('brain_rounds', 22, ('!now', ('!bag', 'used_slots', [], '<', 34))),
     'before': [('start', 'upkeep__empty_the_bag')],
     'check': [('bag', 'used_slots', [], '<', 34)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'empty_the_bag'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__no_pickaxe',
     'module': 'reflexes',
     'doc': 'upkeep, no pickaxe, planks + sticks + a table carried → a pickaxe made',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_planks', 6),
               ('give', 'stick', 4),
               ('give', 'crafting_table')],
     'run': ('brain_rounds', 22, ('!now', ('!bag', 'tools', ['pickaxe']))),
     'before': [('start', 'upkeep__no_pickaxe')],
     'check': [('bag', 'tools', ['pickaxe'])],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'no_pickaxe'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__path_blocked',
     'module': 'reflexes',
     'doc': 'upkeep, the last walk failed toward the far side of a 6-block gap, 16 blocks carried → bridged across',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, -3, -8), ('@', 7, -1, 8), 'air'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 16)],
     'run': ('brain_rounds', 22, ('!now_api', ('!_at', ('@', 9, 0, 0), 4))),
     'before': [('start', 'upkeep__path_blocked'), ('blocked_toward', ('@', 9, 0, 0))],
     'check': [('_at', ('@', 9, 0, 0), 4)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'path_blocked'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__collect_machine',
     'module': 'reflexes',
     'doc': 'upkeep, a remembered auto smelter whose order is due, 8 ingots in its output chest → taken',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 3, 0, 0), 'chest'),
               ('at', 'item replace block {0} container.0 with iron_ingot 8', ('@', 3, 0, 0)),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('brain_rounds', 22, ('!_count', 'minecraft:iron_ingot', 8)),
     'before': [('start', 'upkeep__collect_machine'), ('machine_due', ('@', 3, 0, 0), 8)],
     'check': [('gain', 'minecraft:iron_ingot', 8)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'collect_machine'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__eat_when_full',
     'module': 'reflexes',
     'doc': 'upkeep, fed (food 20), bread carried → not eaten: the bread count unchanged (must not)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'bread', 4)],
     'run': ('brain_rounds', 10, ('!now', ('!constant', False))),
     'before': [('start', 'upkeep__eat_when_full')],
     'check': [('count', 'minecraft:bread', '==', 4)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'eat_when_full'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__shelter_dig_in',
     'module': 'reflexes',
     'doc': 'upkeep, night, a pickaxe → dug in: below the floor, enclosed',
     'scene': [('fill', ('@', -8, -6, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('time', 18000),
               ('give', 'stone_pickaxe'),
               ('give', 'cobblestone', 8)],
     'run': ('brain_rounds', 22, ('&enclosed',)),
     'before': [('start', 'upkeep__shelter_dig_in')],
     'check': [('call', 'enclosed', []), ('state', 'y', '<', 199.5)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'shelter_dig_in'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__shelter_hut',
     'module': 'reflexes',
     'doc': "upkeep, night, no pickaxe, the hut's materials (cobblestone, a door, a torch) → sheltered by the way "
            "the night's pricing chose",
     'scene': [('fill', ('@', -8, -6, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('time', 18000),
               ('give', 'cobblestone', 32),
               ('give', 'oak_door'),
               ('give', 'torch', 2)],
     'run': ('brain_rounds', 22, ('&enclosed',)),
     'before': [('start', 'upkeep__shelter_hut')],
     'check': [('call', 'enclosed', [])],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'shelter_hut'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__shelter_wall_in',
     'module': 'reflexes',
     'doc': 'upkeep, night, no pickaxe, cobblestone only → walled in where it stands',
     'scene': [('fill', ('@', -8, -6, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('time', 18000),
               ('give', 'cobblestone', 16)],
     'run': ('brain_rounds', 22, ('&enclosed',)),
     'before': [('start', 'upkeep__shelter_wall_in')],
     'check': [('call', 'enclosed', []), ('blocks', ('@', -1, 0, -1), ('@', 1, 2, 1), ('cobblestone',), 9)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'shelter_wall_in'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'upkeep__shelter_not_with_a_bed',
     'module': 'reflexes',
     'doc': 'upkeep, night, a bed and cobblestone carried → slept, no shelter built (must not)',
     'scene': [('fill', ('@', -8, -6, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('time', 18000),
               ('give', 'white_bed'),
               ('give', 'cobblestone', 16)],
     'run': ('brain_rounds', 22, ('&is_day_now',)),
     'before': [('start', 'upkeep__shelter_not_with_a_bed')],
     'check': [('is_day',), ('blocks', ('@', -3, 0, -3), ('@', 3, 2, 3), ('cobblestone',), 0, 0)],
     'budget': 25,
     'point': 'C',
     'skills': [],
     'tier_fixed': 'brain',
     'combat': False,
     'tags': {'base': 'upkeep', 'line': 'shelter_not_with_a_bed'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'night_dig_in_dirt_unreachable',
     'module': 'brain',
     'doc': "the same dirt across a drop to nothing, a pod's blocks carried → never walked to (must not): walled "
            'in on its own side of the gap',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 7, -3, -1), ('@', 8, -1, 1), 'dirt'),
               ('fill', ('@', 7, -4, -1), ('@', 8, -4, 1), 'stone'),
               ('fill', ('@', 4, -3, -8), ('@', 5, -1, 8), 'air'),
               ('give', 'cobblestone', 10),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('time', 12500)],
     'run': ('brain_rounds', 25, ('&enclosed',)),
     'before': [('start', 'night_dig_in_dirt_unreachable')],
     'check': [('state', 'blockX', '<', 10004)],
     'budget': 25,
     'point': 'C',
     'skills': ['shelter:dig in'],
     'tier_fixed': 'brain',
     'tags': {'base': 'brain', 'family': 'night_dirt'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
]

NOT_EXPRESSED = {
    'ban_needs_a_failure': "<lambda>: a lambda; no run target in _threading.Timer(2.0, lambda: _chat(f'summon zombi",
    'resume_after_combat': "<lambda>: a lambda; no run target in _threading.Timer(1.5, lambda: _chat(f'summon zombi",
    'l3_two_goals_in_order': "_slice.<locals>.run: <lambda>: a lambda; no predicate for _count('log', 2)()",
    'l3_order_swapped': "_slice.<locals>.run: <lambda>: a lambda; no predicate for _count('log', 2)()",
    'brain__base': "_night_rule.<locals>.<lambda>: _night_rule: cell not kept in its closure; no comparison for int(api.get('/state')['timeOfDay']) % 24 … 13000",
    'night_first__low': '_bed_then_log.<locals>.<lambda>: _bed_then_log: cell not kept in its closure; lambda source not parsed: \'lambda api, inv: (_before_in_bag("furnace_beef", "log")(api,\'',
    'tool_tier__one_use': "_tool_rule.<locals>.<lambda>: _tool_rule: cell not kept in its closure; no comparison for inv.count('minecraft:stone_pickaxe') + i … 0",
    'brain__underground': "_night_rule.<locals>.<lambda>: _night_rule: cell not kept in its closure; no comparison for int(api.get('/state')['timeOfDay']) % 24 … 13000",
    'upkeep__reach_land': "_brain_rounds.<locals>.run: <lambda>: a lambda; no predicate for _st(__import__('bonobo.api', fromlist=['get']))['onGround']",
    'upkeep__eat': "<lambda>: a lambda; a run that is not one call: (time.sleep(5.5), BASE.update(food_before=__import__('bonobo",
    'upkeep__eat_to_regen': '_brain_rounds.<locals>.run: <lambda>: a lambda; a module value',
    'upkeep__bridge_stock': "_brain_rounds.<locals>.run: <lambda>: a lambda; no predicate for _at(at(9, 0, 0), 4)(__import__('bonobo.api', fromlist=['get'",
    'upkeep__unstuck': '_brain_rounds.<locals>.run: <lambda>: a lambda; a module value',
    'night_dig_in_dirt': '_brain_rounds.<locals>.run: <lambda>: a lambda; a module value',
    'search_night_resume': '_when.<locals>.hook: <lambda>: a lambda; no predicate for (SEARCH_FLAGS.update(sheltered=True), _set_time(0)())',
}
