"""Bench table, combat tier: every row as plain data in `bench/vocab.py`'s words, run through `bench/table.py`.
Written from the old sheet (scenarios.SCENARIOS) by `bench/tabulate.py`; tests/test_bench_tables.py proves each row
builds back to the old one (setup, queue, budget, tier, and the same words for run, check and hooks). Not wired to
the runner yet. NOT_EXPRESSED: the old rows whose code has no words here yet, with the reason."""


ROWS = [
    {'name': 'collect_blaze_rods',
     'module': 'combat',
     'doc': 'Nether platform, 3 blazes, sword + shield + iron armor → fight_loop fights them, the step picks up at '
            'least one rod.',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'nether_bricks'),
               ('at', 'fill {0} {1} nether_bricks hollow', ('@', -9, 0, -9), ('@', 9, 5, 9)),
               ('fill', ('@', -8, 0, -8), ('@', 8, 4, 8), 'air'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'diamond_sword'),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 32),
               ('summon', 'blaze', ('@', 3, 1, 0), '{PersistenceRequired:1b,Health:4f}'),
               ('summon', 'blaze', ('@', -3, 1, 2), '{PersistenceRequired:1b,Health:4f}'),
               ('summon', 'blaze', ('@', 0, 1, -3), '{PersistenceRequired:1b,Health:4f}')],
     'run': ('do', 'bonobo.combat.collect_blaze_rods', ['$ctx', 1], {}),
     'check': [('count', 'minecraft:blaze_rod', '>=', 1), ('state', 'health', '>', 0)],
     'budget': 25,
     'dimension': 'minecraft:the_nether',
     'combat': True,
     'expect': [(('@', -8, -1, -8), ('@', 8, -1, 8), 'nether_bricks', 289, 289)],
     'expect_entities': [('minecraft:blaze', 3)],
     'skills': ['collect_blaze_rods'],
     'point': 'A'},
    {'name': 'ghast_fireball',
     'module': 'brain',
     'doc': 'Nether hall open to one side, a ghast 20 blocks out, sword + armor → 30 s of reflexes, still healthy.',
     'scene': [('fill', ('@', -6, -2, -6), ('@', 6, -1, 6), 'netherrack'),
               ('at', 'fill {0} {1} netherrack hollow', ('@', -6, 0, -6), ('@', 6, 0, 6)),
               ('fill', ('@', -5, 0, -5), ('@', 5, 0, 5), 'air'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'diamond_sword'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with golden_helmet'),
               ('give', 'cooked_beef', 16)],
     'run': ('reflex_for', 30),
     'before': [('do',
                 'chat',
                 ['execute in minecraft:the_nether run summon ghast 10018 206 10000 {PersistenceRequired:1b}'],
                 {})],
     'check': [('state', 'health', '>=', 10), ('not', ('!state', 'dead'))],
     'budget': 25,
     'dimension': 'minecraft:the_nether',
     'combat': True,
     'expect': [(('@', -6, -1, -6), ('@', 6, -1, 6), 'netherrack', 169, 169)],
     'skills': [],
     'point': 'A'},
    {'name': 'bed_bomb_kill',
     'module': 'end',
     'doc': 'Speedrun End kit, the dragon perched and worn (crystals gone, 8 hp) → dead by a bed bomb.',
     'scene': [('cmd', 'clear @p'),
               ('give', 'stone_sword'),
               ('give', 'stone_pickaxe'),
               ('give', 'white_bed', 6),
               ('give', 'cobblestone', 64),
               ('give', 'cooked_beef', 16),
               ('give', 'water_bucket'),
               ('give', 'diamond_sword')],
     'run': ('do', 'bonobo.end.slay_dragon', ['$ctx'], {}),
     'before': [('&worn_perched_dragon',)],
     'check': [('call', 'dragon_health', [], 'is', None), ('not', ('!state', 'dead'))],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:the_end',
     'release': True,
     'skills': ['slay_dragon'],
     'point': 'A'},
    {'name': 'siege__w1',
     'module': 'combat',
     'doc': 'Siege wave 1 of 7 (one walker), sword, pickaxe, full iron, shield, food and blocks: every answer the '
            'model offers is available → the wave cleared alive.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]'),
               ('cmd', 'effect give @p minecraft:instant_health 3 10 true'),
               ('give', 'iron_sword'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'diamond_pickaxe'),
               ('give', 'cobblestone', 64),
               ('give', 'dirt', 64),
               ('give', 'cooked_beef', 8),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('cmd', 'item replace entity @p armor.legs with iron_leggings'),
               ('cmd', 'item replace entity @p armor.feet with iron_boots'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 128),
               ('give', 'iron_sword')],
     'run': ('bonobo.bench.core:_sweep',
             'siege__w1',
             ('!iter', [{'wave': 1, 'line_up': 'one walker'}]),
             ('&bonobo.bench.fight:_siege_build',),
             ('!bonobo.bench.fight:_siege_record', 24.0),
             ('$data', 'bench/siege.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'siege__w1',
                ('$data', 'bench/siege.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',), ('&bonobo.bench.fight:_wave_cleared',)],
                1)],
     'no_detail': 'the report line is code: <lambda>: a lambda; a lambda of (inv, w)',
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'skills': [],
     'point': 'A'},
    {'name': 'siege__w2',
     'module': 'combat',
     'doc': 'Siege wave 2 of 7 (three walkers), sword, pickaxe, full iron, shield, food and blocks: every answer '
            'the model offers is available → the wave cleared alive.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]'),
               ('cmd', 'effect give @p minecraft:instant_health 3 10 true'),
               ('give', 'iron_sword'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'diamond_pickaxe'),
               ('give', 'cobblestone', 64),
               ('give', 'dirt', 64),
               ('give', 'cooked_beef', 8),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('cmd', 'item replace entity @p armor.legs with iron_leggings'),
               ('cmd', 'item replace entity @p armor.feet with iron_boots'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 128),
               ('cmd', 'damage @p 2 minecraft:magic'),
               ('cmd', 'clear @p cooked_beef 1'),
               ('cmd', 'clear @p cobblestone 4'),
               ('give', 'iron_sword')],
     'run': ('bonobo.bench.core:_sweep',
             'siege__w2',
             ('!iter', [{'wave': 2, 'line_up': 'three walkers'}]),
             ('&bonobo.bench.fight:_siege_build',),
             ('!bonobo.bench.fight:_siege_record', 24.0),
             ('$data', 'bench/siege.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'siege__w2',
                ('$data', 'bench/siege.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',), ('&bonobo.bench.fight:_wave_cleared',)],
                1)],
     'no_detail': 'the report line is code: <lambda>: a lambda; a lambda of (inv, w)',
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'skills': [],
     'point': 'A'},
    {'name': 'siege__w3',
     'module': 'combat',
     'doc': 'Siege wave 3 of 7 (two archers), sword, pickaxe, full iron, shield, food and blocks: every answer the '
            'model offers is available → the wave cleared alive.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]'),
               ('cmd', 'effect give @p minecraft:instant_health 3 10 true'),
               ('give', 'iron_sword'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'diamond_pickaxe'),
               ('give', 'cobblestone', 64),
               ('give', 'dirt', 64),
               ('give', 'cooked_beef', 8),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('cmd', 'item replace entity @p armor.legs with iron_leggings'),
               ('cmd', 'item replace entity @p armor.feet with iron_boots'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 128),
               ('cmd', 'damage @p 4 minecraft:magic'),
               ('cmd', 'clear @p cooked_beef 2'),
               ('cmd', 'clear @p cobblestone 10'),
               ('give', 'iron_sword')],
     'run': ('bonobo.bench.core:_sweep',
             'siege__w3',
             ('!iter', [{'wave': 3, 'line_up': 'two archers'}]),
             ('&bonobo.bench.fight:_siege_build',),
             ('!bonobo.bench.fight:_siege_record', 24.0),
             ('$data', 'bench/siege.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'siege__w3',
                ('$data', 'bench/siege.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',), ('&bonobo.bench.fight:_wave_cleared',)],
                1)],
     'no_detail': 'the report line is code: <lambda>: a lambda; a lambda of (inv, w)',
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'skills': [],
     'point': 'A'},
    {'name': 'siege__w4',
     'module': 'combat',
     'doc': 'Siege wave 4 of 7 (walkers and climbers), sword, pickaxe, full iron, shield, food and blocks: every '
            'answer the model offers is available → the wave cleared alive.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]'),
               ('cmd', 'effect give @p minecraft:instant_health 3 10 true'),
               ('give', 'iron_sword'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'diamond_pickaxe'),
               ('give', 'cobblestone', 64),
               ('give', 'dirt', 64),
               ('give', 'cooked_beef', 8),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('cmd', 'item replace entity @p armor.legs with iron_leggings'),
               ('cmd', 'item replace entity @p armor.feet with iron_boots'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 128),
               ('cmd', 'damage @p 6 minecraft:magic'),
               ('cmd', 'clear @p cooked_beef 3'),
               ('cmd', 'clear @p cobblestone 18'),
               ('give', 'iron_sword')],
     'run': ('bonobo.bench.core:_sweep',
             'siege__w4',
             ('!iter', [{'wave': 4, 'line_up': 'walkers and climbers'}]),
             ('&bonobo.bench.fight:_siege_build',),
             ('!bonobo.bench.fight:_siege_record', 24.0),
             ('$data', 'bench/siege.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'siege__w4',
                ('$data', 'bench/siege.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',), ('&bonobo.bench.fight:_wave_cleared',)],
                1)],
     'no_detail': 'the report line is code: <lambda>: a lambda; a lambda of (inv, w)',
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'skills': [],
     'point': 'A'},
    {'name': 'siege__w5',
     'module': 'combat',
     'doc': 'Siege wave 5 of 7 (two bombs), sword, pickaxe, full iron, shield, food and blocks: every answer the '
            'model offers is available → the wave cleared alive.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]'),
               ('cmd', 'effect give @p minecraft:instant_health 3 10 true'),
               ('give', 'iron_sword'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'diamond_pickaxe'),
               ('give', 'cobblestone', 64),
               ('give', 'dirt', 64),
               ('give', 'cooked_beef', 8),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('cmd', 'item replace entity @p armor.legs with iron_leggings'),
               ('cmd', 'item replace entity @p armor.feet with iron_boots'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 128),
               ('cmd', 'damage @p 7 minecraft:magic'),
               ('cmd', 'clear @p cooked_beef 4'),
               ('cmd', 'clear @p cobblestone 28'),
               ('give', 'iron_sword')],
     'run': ('bonobo.bench.core:_sweep',
             'siege__w5',
             ('!iter', [{'wave': 5, 'line_up': 'two bombs'}]),
             ('&bonobo.bench.fight:_siege_build',),
             ('!bonobo.bench.fight:_siege_record', 24.0),
             ('$data', 'bench/siege.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'siege__w5',
                ('$data', 'bench/siege.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',), ('&bonobo.bench.fight:_wave_cleared',)],
                1)],
     'no_detail': 'the report line is code: <lambda>: a lambda; a lambda of (inv, w)',
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'skills': [],
     'point': 'A'},
    {'name': 'siege__w6',
     'module': 'combat',
     'doc': 'Siege wave 6 of 7 (three teleporters), sword, pickaxe, full iron, shield, food and blocks: every '
            'answer the model offers is available → the wave cleared alive.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]'),
               ('cmd', 'effect give @p minecraft:instant_health 3 10 true'),
               ('give', 'iron_sword'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'diamond_pickaxe'),
               ('give', 'cobblestone', 64),
               ('give', 'dirt', 64),
               ('give', 'cooked_beef', 8),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('cmd', 'item replace entity @p armor.legs with iron_leggings'),
               ('cmd', 'item replace entity @p armor.feet with iron_boots'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 128),
               ('cmd', 'damage @p 8 minecraft:magic'),
               ('cmd', 'clear @p cooked_beef 5'),
               ('cmd', 'clear @p cobblestone 34'),
               ('give', 'iron_sword')],
     'run': ('bonobo.bench.core:_sweep',
             'siege__w6',
             ('!iter', [{'wave': 6, 'line_up': 'three teleporters'}]),
             ('&bonobo.bench.fight:_siege_build',),
             ('!bonobo.bench.fight:_siege_record', 24.0),
             ('$data', 'bench/siege.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'siege__w6',
                ('$data', 'bench/siege.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',), ('&bonobo.bench.fight:_wave_cleared',)],
                1)],
     'no_detail': 'the report line is code: <lambda>: a lambda; a lambda of (inv, w)',
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'skills': [],
     'point': 'A'},
    {'name': 'siege__w7',
     'module': 'combat',
     'doc': 'Siege wave 7 of 7 (everything), sword, pickaxe, full iron, shield, food and blocks: every answer the '
            'model offers is available → the wave cleared alive.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]'),
               ('cmd', 'effect give @p minecraft:instant_health 3 10 true'),
               ('give', 'iron_sword'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'diamond_pickaxe'),
               ('give', 'cobblestone', 64),
               ('give', 'dirt', 64),
               ('give', 'cooked_beef', 8),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('cmd', 'item replace entity @p armor.legs with iron_leggings'),
               ('cmd', 'item replace entity @p armor.feet with iron_boots'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 128),
               ('cmd', 'damage @p 9 minecraft:magic'),
               ('cmd', 'clear @p cooked_beef 6'),
               ('cmd', 'clear @p cobblestone 38'),
               ('give', 'iron_sword')],
     'run': ('bonobo.bench.core:_sweep',
             'siege__w7',
             ('!iter', [{'wave': 7, 'line_up': 'everything'}]),
             ('&bonobo.bench.fight:_siege_build',),
             ('!bonobo.bench.fight:_siege_record', 24.0),
             ('$data', 'bench/siege.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'siege__w7',
                ('$data', 'bench/siege.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',), ('&bonobo.bench.fight:_wave_cleared',)],
                1)],
     'no_detail': 'the report line is code: <lambda>: a lambda; a lambda of (inv, w)',
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__1',
     'module': 'threat',
     'doc': 'combat_arena shard none/open/full/whole: each cell writes the whole decision into bench/combat.jsonl; '
            'the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__1',
             ('!iter',
              [{'enemy': 'none',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__1',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'none'),
                  ('ground', 'open'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__2',
     'module': 'threat',
     'doc': 'combat_arena shard walker/open/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__2',
             ('!iter',
              [{'enemy': 'walker',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__2',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'walker'),
                  ('ground', 'open'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__3',
     'module': 'threat',
     'doc': 'combat_arena shard walker/corridor/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__3',
             ('!iter',
              [{'enemy': 'walker',
                'count': 'one',
                'ground': 'corridor',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__3',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'walker'),
                  ('ground', 'corridor'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__4',
     'module': 'threat',
     'doc': 'combat_arena shard walker/roofed/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__4',
             ('!iter',
              [{'enemy': 'walker',
                'count': 'one',
                'ground': 'roofed',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__4',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'walker'),
                  ('ground', 'roofed'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__5',
     'module': 'threat',
     'doc': 'combat_arena shard archer/open/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__5',
             ('!iter',
              [{'enemy': 'archer',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__5',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'archer'),
                  ('ground', 'open'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__6',
     'module': 'threat',
     'doc': 'combat_arena shard archer/corridor/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__6',
             ('!iter',
              [{'enemy': 'archer',
                'count': 'one',
                'ground': 'corridor',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__6',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'archer'),
                  ('ground', 'corridor'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__7',
     'module': 'threat',
     'doc': 'combat_arena shard archer/roofed/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__7',
             ('!iter',
              [{'enemy': 'archer',
                'count': 'one',
                'ground': 'roofed',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__7',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'archer'),
                  ('ground', 'roofed'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__8',
     'module': 'threat',
     'doc': 'combat_arena shard climber/open/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__8',
             ('!iter',
              [{'enemy': 'climber',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__8',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'climber'),
                  ('ground', 'open'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__9',
     'module': 'threat',
     'doc': 'combat_arena shard climber/corridor/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__9',
             ('!iter',
              [{'enemy': 'climber',
                'count': 'one',
                'ground': 'corridor',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__9',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'climber'),
                  ('ground', 'corridor'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__10',
     'module': 'threat',
     'doc': 'combat_arena shard climber/roofed/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__10',
             ('!iter',
              [{'enemy': 'climber',
                'count': 'one',
                'ground': 'roofed',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__10',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'climber'),
                  ('ground', 'roofed'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__11',
     'module': 'threat',
     'doc': 'combat_arena shard bomb/open/full/whole: each cell writes the whole decision into bench/combat.jsonl; '
            'the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__11',
             ('!iter',
              [{'enemy': 'bomb',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__11',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'bomb'),
                  ('ground', 'open'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__12',
     'module': 'threat',
     'doc': 'combat_arena shard bomb/corridor/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__12',
             ('!iter',
              [{'enemy': 'bomb',
                'count': 'one',
                'ground': 'corridor',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__12',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'bomb'),
                  ('ground', 'corridor'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__13',
     'module': 'threat',
     'doc': 'combat_arena shard bomb/roofed/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__13',
             ('!iter',
              [{'enemy': 'bomb',
                'count': 'one',
                'ground': 'roofed',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__13',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'bomb'),
                  ('ground', 'roofed'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__14',
     'module': 'threat',
     'doc': 'combat_arena shard teleporter/open/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__14',
             ('!iter',
              [{'enemy': 'teleporter',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__14',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'teleporter'),
                  ('ground', 'open'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__15',
     'module': 'threat',
     'doc': 'combat_arena shard teleporter/corridor/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__15',
             ('!iter',
              [{'enemy': 'teleporter',
                'count': 'one',
                'ground': 'corridor',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__15',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'teleporter'),
                  ('ground', 'corridor'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__16',
     'module': 'threat',
     'doc': 'combat_arena shard teleporter/roofed/full/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__16',
             ('!iter',
              [{'enemy': 'teleporter',
                'count': 'one',
                'ground': 'roofed',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__16',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'teleporter'),
                  ('ground', 'roofed'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__17',
     'module': 'threat',
     'doc': 'combat_arena shard walker/open/nothing/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__17',
             ('!iter',
              [{'enemy': 'walker',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'nothing',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__17',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'walker'),
                  ('ground', 'open'),
                  ('kit', 'nothing'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__18',
     'module': 'threat',
     'doc': 'combat_arena shard walker/open/blocks/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__18',
             ('!iter',
              [{'enemy': 'walker',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'blocks',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__18',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'walker'),
                  ('ground', 'open'),
                  ('kit', 'blocks'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__19',
     'module': 'threat',
     'doc': 'combat_arena shard walker/open/food/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__19',
             ('!iter',
              [{'enemy': 'walker',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'food',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__19',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'walker'),
                  ('ground', 'open'),
                  ('kit', 'food'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__20',
     'module': 'threat',
     'doc': 'combat_arena shard walker/open/shield/whole: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__20',
             ('!iter',
              [{'enemy': 'walker',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'whole',
                'kit': 'shield',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__20',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'whole'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'walker'),
                  ('ground', 'open'),
                  ('kit', 'shield'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'combat_arena__21',
     'module': 'threat',
     'doc': 'combat_arena shard walker/open/full/hurt: each cell writes the whole decision into '
            'bench/combat.jsonl; the rules are relations between rows.',
     'scene': [('cmd', 'gamemode survival @p'),
               ('cmd', 'difficulty normal'),
               ('cmd', 'time set day'),
               ('cmd', 'clear @p'),
               ('fill', ('@', -24, -2, -24), ('@', 27, 6, 24), 'air'),
               ('fill', ('@', -24, -2, -24), ('@', 27, -1, 24), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'kill @e[type=!player,distance=..40]'),
               ('fill', ('@', -24, 0, -24), ('@', 27, 2, -24), 'stone'),
               ('fill', ('@', -24, 0, 24), ('@', 27, 2, 24), 'stone'),
               ('fill', ('@', -24, 0, -24), ('@', -24, 2, 24), 'stone'),
               ('fill', ('@', 27, 0, -24), ('@', 27, 2, 24), 'stone'),
               ('cmd', 'kill @e[type=!player,type=!item,distance=..48]')],
     'run': ('bonobo.bench.core:_sweep',
             'combat_arena__21',
             ('!iter',
              [{'enemy': 'walker',
                'count': 'one',
                'ground': 'open',
                'weapon': 'iron',
                'armour': 'iron',
                'blood': 'hurt',
                'kit': 'full',
                'distance': 'near',
                'run': 0}]),
             ('&bonobo.bench.fight:_build',),
             ('!bonobo.bench.fight:_fought', ('&bonobo.bench.fight:_kinds_of',), 15.0),
             ('$data', 'bench/combat.jsonl'),
             0.6),
     'check': [('bonobo.bench.core:_sweep_check',
                'combat_arena__21',
                ('$data', 'bench/combat.jsonl'),
                [('&bonobo.bench.fight:_answers_are_closed',),
                 ('&bonobo.bench.fight:_shapes_fit_the_enemy',),
                 ('&bonobo.bench.fight:_more_of_them_costs_more',)],
                1)],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:overworld',
     'sweep': True,
     'variant': [[('armour', 'iron'),
                  ('blood', 'hurt'),
                  ('count', 'one'),
                  ('distance', 'near'),
                  ('enemy', 'walker'),
                  ('ground', 'open'),
                  ('kit', 'full'),
                  ('run', 0),
                  ('weapon', 'iron')]],
     'expect': [(('@', -9, -1, -9), ('@', 12, -1, 9), 'stone', 418, 418)],
     'tick_rate': 60,
     'skills': [],
     'point': 'A'},
    {'name': 'fight_zombie_1',
     'module': 'fight_loop',
     'doc': 'Walled platform, iron kit: 1 zombie → all dead, health ≥ 12, a threat decision every ≤ 1.5 × '
            'FIGHT_POLL_S while engaged',
     'scene': [('fill', ('@', -9, -2, -9), ('@', 9, -1, 9), 'stone'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -9, 4, -9), ('@', 9, 4, 9), 'stone'),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('fill', ('@', -9, -1, -9), ('@', 9, -1, 9), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 64),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('summon', 'zombie', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
               ('give', 'iron_sword')],
     'run': ('fight_until', ['minecraft:zombie'], 23),
     'before': [('start', 'fight_zombie_1'), ('&record_bids',)],
     'check': [('hp_kept', 12), ('gone', ['minecraft:zombie']), ('decision_gaps_ok',)],
     'budget': 25,
     'combat': True,
     'point': 'B',
     'skills': [],
     'tier_fixed': 'common',
     'tags': {'base': 'fight', 'enemy': 'zombie', 'count': 1},
     'expect_entities': [('minecraft:zombie', 1)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'fight_zombie_3',
     'module': 'fight_loop',
     'doc': 'Walled platform, iron kit: 3 zombie → all dead, health ≥ 6, a threat decision every ≤ 1.5 × '
            'FIGHT_POLL_S while engaged',
     'scene': [('fill', ('@', -9, -2, -9), ('@', 9, -1, 9), 'stone'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -9, 4, -9), ('@', 9, 4, 9), 'stone'),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('fill', ('@', -9, -1, -9), ('@', 9, -1, 9), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 64),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('summon', 'zombie', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
               ('summon', 'zombie', ('@', -3, 0, 3), '{PersistenceRequired:1b}'),
               ('summon', 'zombie', ('@', 1, 0, -4), '{PersistenceRequired:1b}'),
               ('give', 'iron_sword')],
     'run': ('fight_until', ['minecraft:zombie'], 23),
     'before': [('start', 'fight_zombie_3'), ('&record_bids',)],
     'check': [('hp_kept', 6), ('gone', ['minecraft:zombie']), ('decision_gaps_ok',)],
     'budget': 25,
     'combat': True,
     'point': 'B',
     'skills': [],
     'tier_fixed': 'exception',
     'tags': {'base': 'fight', 'enemy': 'zombie', 'count': 3},
     'expect_entities': [('minecraft:zombie', 3)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'fight_skeleton_1',
     'module': 'fight_loop',
     'doc': 'Walled platform, iron kit: 1 skeleton → all dead, health ≥ 10, a threat decision every ≤ 1.5 × '
            'FIGHT_POLL_S while engaged',
     'scene': [('fill', ('@', -9, -2, -9), ('@', 9, -1, 9), 'stone'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -9, 4, -9), ('@', 9, 4, 9), 'stone'),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('fill', ('@', -9, -1, -9), ('@', 9, -1, 9), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 64),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('summon', 'skeleton', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
               ('give', 'iron_sword')],
     'run': ('fight_until', ['minecraft:skeleton'], 23),
     'before': [('start', 'fight_skeleton_1'), ('&record_bids',)],
     'check': [('hp_kept', 10), ('gone', ['minecraft:skeleton']), ('decision_gaps_ok',)],
     'budget': 25,
     'combat': True,
     'point': 'B',
     'skills': [],
     'tier_fixed': 'common',
     'tags': {'base': 'fight', 'enemy': 'skeleton', 'count': 1},
     'expect_entities': [('minecraft:skeleton', 1)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'fight_creeper_1',
     'module': 'fight_loop',
     'doc': 'Walled platform, iron kit: 1 creeper → dead, or kept off and not following for 5 s, health ≥ 14, a '
            'threat decision every ≤ 1.5 × FIGHT_POLL_S while engaged',
     'scene': [('fill', ('@', -9, -2, -9), ('@', 9, -1, 9), 'stone'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -9, 4, -9), ('@', 9, 4, 9), 'stone'),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('fill', ('@', -9, -1, -9), ('@', 9, -1, 9), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 64),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('summon', 'creeper', ('@', 7, 0, 0), '{PersistenceRequired:1b}'),
               ('give', 'iron_sword')],
     'run': ('fight_until', ['minecraft:creeper'], 18.0),
     'before': [('start', 'fight_creeper_1'), ('&record_bids',)],
     'check': [('threat_resolved', ['minecraft:creeper']), ('decision_gaps_ok',)],
     'budget': 25,
     'combat': True,
     'point': 'B',
     'skills': [],
     'tier_fixed': 'common',
     'tags': {'base': 'fight', 'enemy': 'creeper', 'count': 1},
     'expect_entities': [('minecraft:creeper', 1)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'fight_blaze_3',
     'module': 'fight_loop',
     'doc': 'Walled platform, iron kit: 3 blaze → all dead, health ≥ 6, a threat decision every ≤ 1.5 × '
            'FIGHT_POLL_S while engaged',
     'scene': [('fill', ('@', -9, -2, -9), ('@', 9, -1, 9), 'stone'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -9, 4, -9), ('@', 9, 4, 9), 'stone'),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('fill', ('@', -9, -1, -9), ('@', 9, -1, 9), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 64),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('summon', 'blaze', ('@', 4, 0, 0), '{PersistenceRequired:1b,Health:10f}'),
               ('summon', 'blaze', ('@', -3, 0, 3), '{PersistenceRequired:1b,Health:10f}'),
               ('summon', 'blaze', ('@', 1, 0, -4), '{PersistenceRequired:1b,Health:10f}'),
               ('give', 'diamond_sword')],
     'run': ('fight_until', ['minecraft:blaze'], 23),
     'before': [('start', 'fight_blaze_3'), ('&record_bids',)],
     'check': [('hp_kept', 6), ('gone', ['minecraft:blaze']), ('decision_gaps_ok',)],
     'budget': 25,
     'combat': True,
     'point': 'B',
     'skills': [],
     'tier_fixed': 'exception',
     'tags': {'base': 'fight', 'enemy': 'blaze', 'count': 3},
     'expect_entities': [('minecraft:blaze', 3)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'fight_zombie_1_full_bag',
     'module': 'fight_loop',
     'doc': 'Walled platform, iron kit, the bag full of dirt: 1 zombie → dead, health ≥ 12, decisions as often as '
            'ever: the drop it cannot pick up changes nothing',
     'scene': [('fill', ('@', -9, -2, -9), ('@', 9, -1, 9), 'stone'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -9, 4, -9), ('@', 9, 4, 9), 'stone'),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('fill', ('@', -9, -1, -9), ('@', 9, -1, 9), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 64),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('summon', 'zombie', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
               ('give', 'iron_sword')],
     'run': ('fight_until', ['minecraft:zombie'], 23),
     'before': [('hooks', ('!start', 'fight_zombie_1'), ('&record_bids',)), ('fill_bag', 0)],
     'check': [('hp_kept', 12), ('gone', ['minecraft:zombie']), ('decision_gaps_ok',)],
     'budget': 25,
     'combat': True,
     'point': 'B',
     'skills': [],
     'tier_fixed': 'exception',
     'tags': {'base': 'fight', 'enemy': 'zombie', 'count': 1, 'inventory': 'full_bag'},
     'expect_entities': [('minecraft:zombie', 1)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'combat__low_hp_eat',
     'module': 'fight_loop',
     'doc': '6 hp, one zombie 2 blocks off, blocks and cooked beef → away from it or walled in first, then fed: '
            'health ends above 6',
     'scene': [('fill', ('@', -9, -2, -9), ('@', 9, -1, 9), 'stone'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -9, 4, -9), ('@', 9, 4, 9), 'stone'),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('fill', ('@', -9, -1, -9), ('@', 9, -1, 9), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 64),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('cmd', 'damage @p 14 minecraft:magic'),
               ('summon', 'zombie', ('@', 2, 0, 0), '{PersistenceRequired:1b}'),
               ('give', 'iron_sword')],
     'run': ('fight_until', ['minecraft:zombie'], 22, False),
     'before': [('start', 'combat__low_hp_eat'), ('&record_bids',)],
     'check': [('state', 'health', '>', 6), ('alive',)],
     'budget': 25,
     'point': 'B',
     'skills': [],
     'combat': True,
     'stochastic': True,
     'tags': {'base': 'fight', 'enemy': 'zombie', 'blood': 'low'},
     'expect_entities': [('minecraft:zombie', 1)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'fight_creeper_sword',
     'module': 'fight_loop',
     'doc': 'Iron sword, a creeper 4 blocks off → the creeper gone (dead or blown up in the air), health ≥ 16',
     'scene': [('fill', ('@', -9, -2, -9), ('@', 9, -1, 9), 'stone'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -9, 4, -9), ('@', 9, 4, 9), 'stone'),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('fill', ('@', -9, -1, -9), ('@', 9, -1, 9), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 64),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('summon', 'creeper', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
               ('give', 'iron_sword')],
     'run': ('fight_until', ['minecraft:creeper'], 25),
     'before': [('start', 'fight_creeper_sword'), ('&record_bids',)],
     'check': [('gone', ['minecraft:creeper']), ('hp_kept', 16)],
     'budget': 25,
     'point': 'B',
     'skills': [],
     'combat': True,
     'stochastic': True,
     'tags': {'base': 'fight', 'enemy': 'creeper', 'ground': 'open'},
     'expect_entities': [('minecraft:creeper', 1)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'fight_creeper_by_home',
     'module': 'fight_loop',
     'doc': 'Iron sword, a creeper 4 blocks off, a bed and a furnace of ours within 3 of it → the creeper gone '
            '(dead or blown up in the air), health ≥ 16, the bed and the furnace still standing',
     'scene': [('fill', ('@', -9, -2, -9), ('@', 9, -1, 9), 'stone'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -9, 4, -9), ('@', 9, 4, 9), 'stone'),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('fill', ('@', -9, -1, -9), ('@', 9, -1, 9), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
               ('cmd', 'item replace entity @p armor.head with iron_helmet'),
               ('give', 'cooked_beef', 16),
               ('give', 'cobblestone', 64),
               ('cmd', 'item replace entity @p weapon.offhand with shield'),
               ('setblock', ('@', 4, 0, 2), 'red_bed[facing=east,part=foot]'),
               ('setblock', ('@', 5, 0, 2), 'red_bed[facing=east,part=head]'),
               ('setblock', ('@', 4, 0, -2), 'furnace'),
               ('summon', 'creeper', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
               ('give', 'iron_sword')],
     'run': ('fight_until', ['minecraft:creeper'], 25),
     'before': [('start', 'fight_creeper_by_home'), ('&record_bids',), ('&home_is_ours',)],
     'check': [('gone', ['minecraft:creeper']),
               ('hp_kept', 16),
               ('blocks', ('@', 4, 0, 2), ('@', 5, 0, 2), ('red_bed',), 2),
               ('blocks', ('@', 4, 0, -2), ('@', 4, 0, -2), ('furnace',), 1)],
     'budget': 25,
     'point': 'B',
     'skills': [],
     'combat': True,
     'stochastic': True,
     'tags': {'base': 'fight', 'enemy': 'creeper', 'ground': 'home'},
     'expect_entities': [('minecraft:creeper', 1)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
]

NOT_EXPRESSED = {
    'fight_dragon': "<lambda>: a lambda; no predicate for any((e['type'] == 'minecraft:ender_dragon' for e in __import",
    'escape__walker_open_blocks': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__none_open_blocks': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__archer_open_blocks': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__climber_open_blocks': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__bomb_open_blocks': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__teleporter_open_blocks': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__walker_corridor_blocks': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__walker_roofed_blocks': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__walker_open_nothing': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__walker_open_food': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__walker_open_shield': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'escape__walker_open_full': 'scene drawn at random at import (bench.fight._seed_of): no fixed table equals it',
    'combat__block_gap': '_behaviour_check.<locals>.check: <lambda>: a lambda; a lambda of (r, api)',
    'combat__dig_in': '_behaviour_check.<locals>.check: <lambda>: a lambda; a lambda of (r, api)',
    'combat__pillar': '_behaviour_check.<locals>.check: <lambda>: a lambda; a lambda of (r, api)',
    'combat__shield_arrows': '_behaviour_check.<locals>.check: <lambda>: a lambda; a lambda of (r, api)',
    'combat__fight_without_shield': '_behaviour_check.<locals>.check: <lambda>: a lambda; a lambda of (r, api)',
    'combat__fight_and_block': '_behaviour_check.<locals>.check: <lambda>: a lambda; a lambda of (r, api)',
    'combat__wall_in': '_behaviour_check.<locals>.check: <lambda>: a lambda; a lambda of (r, api)',
    'combat__surrounded_low': '_behaviour_check.<locals>.check: <lambda>: a lambda; a lambda of (r, api)',
    'fight_enderman_1': '<lambda>: a lambda; a set value',
    'fight_before_upkeep': '_brain_rounds.<locals>.run: <lambda>: a lambda; a set value',
    'combat__knocked_off_edge': "<lambda>: a lambda; not evaluable offline: BASE['state']['health'] - 4 (KeyError)",
}
