"""Bench table, common tier: rows as data in `bench/vocab.py`'s words, built by `bench/table.py`.
FAMILIES: (template, [params, ...]) — one entry, many rows (vocab.TEMPLATES). ROWS: the one-off rows, each in words.
NOT_EXPRESSED: old rows kept in the old sheet, with the reason. Not wired to the runner yet."""


FAMILIES = [
    ('base', [('nav', 'canopy'), ('loot', 'canopy'), ('mine_stone', 'cave'), ('chop', 'night'),
         ('mine_stone', 'interrupt_mid_work'), ('mine_stone', 'full_bag')]),
    ('one', [('dig_in_night', ['shelter:dig in'], 'night on stone, a pickaxe → three down, sealed',
          [('floor', 'stone', 8, 4), ('stand',), ('give', 'stone_pickaxe'), ('give', 'cobblestone', 8),
           ('time', 18000)],
          ('skill', 'dig_in'), ('all', ('!state', 'blockY', '<', 200), ('!call', 'enclosed', [])), 25),
         ('reach_land_swim', ['reach:land'], 'night, treading water 10 blocks from shore → on dry land',
          [('tank', -8, 9, -8, 8, 1, -1, -4, 'glass', 'east'),
           ('fill', ('@', 10, -3, -8), ('@', 14, -1, 8), 'stone'), ('stand',), ('time', 18000)],
          ('skill', 'reach_land'), ('all', ('!state', 'onGround'), ('!not', ('!state', 'inWater'))), 25)]),
    ('place', [('place_furnace_north', 'minecraft:furnace', 'north', 'north', 'common'),
         ('place_furnace_south', 'minecraft:furnace', 'south', 'south', 'common'),
         ('place_furnace_east', 'minecraft:furnace', 'east', 'east', 'common'),
         ('place_furnace_west', 'minecraft:furnace', 'west', 'west', 'common')]),
    ('start', [('nav_from_stairs', 'a stair step', [('setblock', ('@', 0, 0, 0), 'oak_stairs[facing=east]')], (0, 0.5)),
         ('nav_from_slab', 'a bottom slab', [('setblock', ('@', 0, 0, 0), 'stone_slab')], (0, 0.5)),
         ('nav_from_farmland', 'farmland', [('setblock', ('@', 0, -1, 0), 'farmland')], ()),
         ('nav_from_ladder', 'a ladder on a wall',
          [('fill', ('@', 1, 0, 0), ('@', 1, 3, 0), 'stone'),
           ('fill', ('@', 0, 0, 0), ('@', 0, 3, 0), 'ladder[facing=west]')],
          (0, 2)),
         ('nav_from_water', 'a pool one deep', [('fill', ('@', -1, 0, -1), ('@', 1, 0, 1), 'water')], ())]),
]

ROWS = [
    dict(name='cave_escape', module='nav',
         doc=('Sealed in a dark 1×2 pocket 4 blocks under the platform, pickaxe + blocks → back on the surface '
              'platform.'),
         scene=[('floor', 'stone', 6, 12), ('fill', ('@', 0, -5, 0), ('@', 0, -4, 0), 'air'), ('stand', 0, -5),
                ('cmd', 'clear @p'), ('give', 'stone_pickaxe'), ('give', 'cobblestone', 32)],
         run=('do', 'bonobo.nav.go_to', [('@', 3, 0, 3), ('$ctx', 'policy')], {'range_': 0.6}),
         check=[('state', 'y', '>=', 199.5), ('state', 'onGround')], budget=25,
         expect=[(('@', -6, -1, -6), ('@', 6, -1, 6), 'stone', 169, 169)], mod=['travel'], point='B',
         skills=['travel_to']),
    dict(name='slice_nether_kit', module='brain',
         doc=('Slice: at a lit portal, the kit two steps short (one block, the gold helmet) → kit complete (food, '
              'blocks, gold helmet) without stepping into the Nether early, no loops, idle ≤ 15 s.'),
         scene=[('floor', 'grass_block', 8, 2), ('fill', ('@', 1, 0, -1), ('@', 1, 1, 1), 'stone'),
                ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'), ('cmd', 'time set day'), ('give', 'iron_pickaxe'),
                ('give', 'iron_sword'), ('give', 'bucket'), ('give', 'flint_and_steel'), ('give', 'gold_ingot', 5),
                ('give', 'crafting_table'), ('give', 'cooked_beef', 8), ('give', 'cobblestone', 31),
                ('summon', 'cow', ('@', -2, 0, 1))],
         run=('slice',
              ('!now', ('!any', ('!call', 'nether_kit_ready', []), ('!not', ('!call', 'in_overworld', [])))), 0.4,
              None, [{'goal': 'milestone', 'args': {'name': 'nether kit'}}]),
         before=[('do', 'portal_beside_player', ['$ctx'], {})],
         check=[('slice_check',
                 ('!now', ('!all', ('!call', 'nether_kit_ready', []), ('!call', 'in_overworld', []))))],
         detail=('&slice_detail',), budget=25, expect=[(('@', 1, 0, -1), ('@', 1, 1, 1), 'stone', 6, 6)],
         expect_entities=[('minecraft:cow', 1)], point='C', chain=2),
    dict(name='cross_lava_8', module='nav',
         doc='A 8-block lava strip between two stone platforms; cobblestone → reach the far side alive.',
         scene=[('fill', ('@', -3, -3, -4), ('@', 14, -3, 4), 'stone'),
                ('fill', ('@', -2, -2, -3), ('@', 13, -1, 3), 'lava'),
                ('fill', ('@', -2, -1, -3), ('@', 1, -1, 3), 'stone'),
                ('fill', ('@', 10, -1, -3), ('@', 13, -1, 3), 'stone'), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'),
                ('give', 'cobblestone', 64), ('give', 'diamond_pickaxe')],
         run=('do', 'bonobo.nav.go_to', [('@', 11, 0, 0), ('$ctx', 'policy')], {'range_': 1.5}),
         check=[('call', 'near', ['$api', ('@', 11, 0, 0), 2.5]), ('state', 'health', '>', 10)], budget=25,
         expect=[(('@', 2, -1, -3), ('@', 9, -1, 3), 'lava', 56, 56),
                 (('@', -2, -1, -3), ('@', 1, -1, 3), 'stone', 28, 28),
                 (('@', -2, 0, -3), ('@', 13, 4, 3), '*', 0, 0)],
         point='B', skills=['travel_to']),
    dict(name='eat_while_walking', module='skills',
         doc=('Hungry, cooked beef carried, 20 blocks to walk → fed on the way without an eat task, still walking '
              "forward while it chewed (ate_on_the_way over the walk's trace)"),
         scene=[('floor',), ('fill', ('@', 8, -3, -3), ('@', 20, -1, 3), 'stone'), ('stand', -2),
                ('give', 'cooked_beef', 4)],
         run=('&walk_once',), before=[('start', 'eat_while_walking'), ('&hungry',)],
         check=[('call', 'ate_on_the_way', [[]]), ('_at', ('@', 18, 0, 0), 3)], budget=25, skills=['goto'],
         tier_fixed='common', combat=False, stochastic=False, tags={'base': 'nav', 'state': 'hungry'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
    dict(name='mine_while_hungry', module='skills',
         doc=('Hungry, cooked beef carried, 3 cobblestone to mine → mined without a pause to eat: the beef '
              'untouched (control for eat_while_walking)'),
         scene=[('floor',), ('stand',), ('give', 'wooden_pickaxe'), ('give', 'cooked_beef', 4)],
         run=('skill', 'mine', 'minecraft:cobblestone', 3, ['stone'], 0),
         before=[('start', 'mine_while_hungry'), ('&hungry',)],
         check=[('gain', 'minecraft:cobblestone', 3), ('count', 'minecraft:cooked_beef', '==', 4)], budget=15,
         skills=['mine'], tier_fixed='common', combat=False, stochastic=False,
         tags={'base': 'mine_stone', 'state': 'hungry'},
         expect=[(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]),
]

NOT_EXPRESSED = {
    'chest_or_tree': "one-off surprise: a memory note on the brain's own memory and a done written as a lambda (no word earns its place)",
    'smelt_job_interrupted': "<lambda>: a lambda; no comparison for INTERRUPTS.get('smelt_job_interrupted',  … 1",
}
