"""Bench table, common tier: every row as plain data in `bench/vocab.py`'s words, run through `bench/table.py`.
Written from the old sheet (scenarios.SCENARIOS) by `bench/tabulate.py`; tests/test_bench_tables.py proves each row
builds back to the old one (setup, queue, budget, tier, and the same words for run, check and hooks). Not wired to
the runner yet. NOT_EXPRESSED: the old rows whose code has no words here yet, with the reason."""


ROWS = [
    {'name': 'cave_escape',
     'module': 'nav',
     'doc': 'Sealed in a dark 1×2 pocket 4 blocks under the platform, pickaxe + blocks → back on the surface '
            'platform.',
     'scene': [('fill', ('@', -6, -12, -6), ('@', 6, -1, 6), 'stone'),
               ('fill', ('@', 0, -5, 0), ('@', 0, -4, 0), 'air'),
               ('tp', ('@', 0.5, -5, 0.5)),
               ('cmd', 'clear @p'),
               ('give', 'stone_pickaxe'),
               ('give', 'cobblestone', 32)],
     'run': ('do', 'bonobo.nav.go_to', [('@', 3, 0, 3), ('$ctx', 'policy')], {'range_': 0.6}),
     'check': [('state', 'y', '>=', 199.5), ('state', 'onGround')],
     'budget': 25,
     'expect': [(('@', -6, -1, -6), ('@', 6, -1, 6), 'stone', 169, 169)],
     'mod': ['travel'],
     'point': 'B',
     'skills': ['travel_to']},
    {'name': 'slice_nether_kit',
     'module': 'brain',
     'doc': 'Slice: at a lit portal, the kit two steps short (one block, the gold helmet) → kit complete (food, '
            'blocks, gold helmet) without stepping into the Nether early, no loops, idle ≤ 15 s.',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', 1, 0, -1), ('@', 1, 1, 1), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('cmd', 'time set day'),
               ('give', 'iron_pickaxe'),
               ('give', 'iron_sword'),
               ('give', 'bucket'),
               ('give', 'flint_and_steel'),
               ('give', 'gold_ingot', 5),
               ('give', 'crafting_table'),
               ('give', 'cooked_beef', 8),
               ('give', 'cobblestone', 31),
               ('summon', 'cow', ('@', -2, 0, 1))],
     'run': ('slice',
             ('!now', ('!any', ('!call', 'nether_kit_ready', []), ('!not', ('!call', 'in_overworld', [])))),
             0.4,
             None,
             [{'goal': 'milestone', 'args': {'name': 'nether kit'}}]),
     'before': [('do', 'portal_beside_player', ['$ctx'], {})],
     'check': [('slice_check',
                ('!now', ('!all', ('!call', 'nether_kit_ready', []), ('!call', 'in_overworld', []))))],
     'detail': ('&slice_detail',),
     'budget': 25,
     'expect': [(('@', 1, 0, -1), ('@', 1, 1, 1), 'stone', 6, 6)],
     'expect_entities': [('minecraft:cow', 1)],
     'point': 'C',
     'chain': 2,
     'skills': []},
    {'name': 'cross_lava_8',
     'module': 'nav',
     'doc': 'A 8-block lava strip between two stone platforms; cobblestone → reach the far side alive.',
     'scene': [('fill', ('@', -3, -3, -4), ('@', 14, -3, 4), 'stone'),
               ('fill', ('@', -2, -2, -3), ('@', 13, -1, 3), 'lava'),
               ('fill', ('@', -2, -1, -3), ('@', 1, -1, 3), 'stone'),
               ('fill', ('@', 10, -1, -3), ('@', 13, -1, 3), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'cobblestone', 64),
               ('give', 'diamond_pickaxe')],
     'run': ('do', 'bonobo.nav.go_to', [('@', 11, 0, 0), ('$ctx', 'policy')], {'range_': 1.5}),
     'check': [('call', 'near', ['$api', ('@', 11, 0, 0), 2.5]), ('state', 'health', '>', 10)],
     'budget': 25,
     'expect': [(('@', 2, -1, -3), ('@', 9, -1, 3), 'lava', 56, 56),
                (('@', -2, -1, -3), ('@', 1, -1, 3), 'stone', 28, 28),
                (('@', -2, 0, -3), ('@', 13, 4, 3), '*', 0, 0)],
     'point': 'B',
     'skills': ['travel_to']},
    {'name': 'nav__canopy',
     'module': 'skills',
     'doc': 'walk 8 blocks east over the arena — under a closed leaf canopy',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 10, -1, 3), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('fill', ('@', -8, 6, -8), ('@', 8, 7, 8), 'oak_leaves[persistent=true]')],
     'run': ('skill', 'travel_to', ('@', 8, 0, 0), 2),
     'before': [('start', 'nav__canopy')],
     'check': [('_at', ('@', 8, 0, 0), 3.5)],
     'budget': 15,
     'skills': ['goto'],
     'point': 'A',
     'tags': {'base': 'nav', 'terrain': 'canopy'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'loot__canopy',
     'module': 'skills',
     'doc': 'a chest of iron and bread 2 blocks away → the iron — under a closed leaf canopy',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 2, 0, 1), 'chest'),
               ('at', 'item replace block {0} container.0 with iron_ingot 5', ('@', 2, 0, 1)),
               ('at', 'item replace block {0} container.1 with bread 4', ('@', 2, 0, 1)),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('fill', ('@', -8, 6, -8), ('@', 8, 7, 8), 'oak_leaves[persistent=true]')],
     'run': ('skill', 'loot_chest'),
     'before': [('start', 'loot__canopy')],
     'check': [('gain', 'minecraft:iron_ingot', 5)],
     'budget': 15,
     'skills': ['loot_chest'],
     'point': 'A',
     'tags': {'base': 'loot', 'terrain': 'canopy'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'mine_stone__cave',
     'module': 'skills',
     'doc': 'stone floor, a wooden pickaxe → 3 cobblestone — in a dark stone room under rock',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wooden_pickaxe'),
               ('at', 'fill {0} {1} stone outline', ('@', -9, -1, -9), ('@', 15, 4, 9)),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'mine', 'minecraft:cobblestone', 3, ['stone'], 0),
     'before': [('start', 'mine_stone__cave')],
     'check': [('gain', 'minecraft:cobblestone', 3)],
     'budget': 15,
     'skills': ['mine'],
     'point': 'A',
     'tags': {'base': 'mine_stone', 'terrain': 'cave'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'chop__night',
     'module': 'skills',
     'doc': 'one oak beside the body → 2 logs — at night',
     'scene': [('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 2, 0),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('time', 18000),
               ('give', 'diamond_axe')],
     'run': ('skill', 'chop', 2),
     'before': [('start', 'chop__night')],
     'check': [('gain', 'log', 2)],
     'budget': 15,
     'skills': ['item:log'],
     'point': 'A',
     'tags': {'base': 'chop', 'terrain': 'night'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'mine_stone__full_bag',
     'module': 'skills',
     'doc': 'stone floor, a wooden pickaxe → 3 cobblestone — every slot full of dirt: nothing new can be picked up',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wooden_pickaxe'),
               ('give', 'dirt', 2304),
               ('give', 'diamond_pickaxe')],
     'run': ('expect_failure',
             'mine_stone__full_bag',
             ('!skill', 'mine', 'minecraft:cobblestone', 3, ['stone'], 0),
             'bag|full|room|slot'),
     'before': [('start', 'mine_stone__full_bag')],
     'check': [('failed_as_expected',), ('alive',), ('same_bag',)],
     'budget': 15,
     'skills': ['mine'],
     'point': 'A',
     'tags': {'base': 'mine_stone', 'inventory': 'full_bag'},
     'fails': 'bag|full|room|slot',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'dig_in_night',
     'module': 'skills',
     'doc': 'night on stone, a pickaxe → three down, sealed',
     'scene': [('fill', ('@', -8, -4, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('give', 'cobblestone', 8),
               ('time', 18000),
               ('give', 'diamond_pickaxe'),
               ('give', 'diamond_shovel')],
     'run': ('skill', 'dig_in'),
     'before': [('start', 'dig_in_night')],
     'check': [('state', 'blockY', '<', 200), ('call', 'enclosed', [])],
     'budget': 25,
     'skills': ['shelter:dig in'],
     'point': 'A',
     'tags': {'base': 'shelter:dig in'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'reach_land_swim',
     'module': 'skills',
     'doc': 'night, treading water 10 blocks from shore → on dry land',
     'scene': [('fill', ('@', -9, -4, -9), ('@', 10, -4, 9), 'stone'),
               ('fill', ('@', -9, -3, -9), ('@', 10, 1, -9), 'glass'),
               ('fill', ('@', -9, -3, 9), ('@', 10, 1, 9), 'glass'),
               ('fill', ('@', -9, -3, -9), ('@', -9, 1, 9), 'glass'),
               ('fill', ('@', 10, -3, -9), ('@', 10, -1, 9), 'glass'),
               ('fill', ('@', -8, -3, -8), ('@', 9, -1, 8), 'water'),
               ('fill', ('@', 10, -3, -8), ('@', 14, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('time', 18000)],
     'run': ('skill', 'reach_land'),
     'before': [('start', 'reach_land_swim')],
     'check': [('state', 'onGround'), ('not', ('!state', 'inWater'))],
     'budget': 25,
     'skills': ['reach:land'],
     'point': 'A',
     'tags': {'base': 'reach:land'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'place_furnace_north',
     'module': 'building',
     'doc': "Place furnace asking facing=north (the jar turns the body by the block's own rule) → the block "
            'reports facing=north',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'furnace', 2)],
     'run': ('place_facing', 'minecraft:furnace', ('@', 3, 0, 0), 'north'),
     'before': [('start', 'place_furnace_north')],
     'check': [('placed_facing', ('@', 3, 0, 0), 'north')],
     'budget': 20,
     'point': 'A',
     'skills': [],
     'tier_fixed': 'common',
     'tags': {'base': 'place'},
     'variant': ('minecraft:furnace', 'north'),
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'place_furnace_south',
     'module': 'building',
     'doc': "Place furnace asking facing=south (the jar turns the body by the block's own rule) → the block "
            'reports facing=south',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'furnace', 2)],
     'run': ('place_facing', 'minecraft:furnace', ('@', 3, 0, 0), 'south'),
     'before': [('start', 'place_furnace_south')],
     'check': [('placed_facing', ('@', 3, 0, 0), 'south')],
     'budget': 20,
     'point': 'A',
     'skills': [],
     'tier_fixed': 'common',
     'tags': {'base': 'place'},
     'variant': ('minecraft:furnace', 'south'),
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'place_furnace_east',
     'module': 'building',
     'doc': "Place furnace asking facing=east (the jar turns the body by the block's own rule) → the block reports "
            'facing=east',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'furnace', 2)],
     'run': ('place_facing', 'minecraft:furnace', ('@', 3, 0, 0), 'east'),
     'before': [('start', 'place_furnace_east')],
     'check': [('placed_facing', ('@', 3, 0, 0), 'east')],
     'budget': 20,
     'point': 'A',
     'skills': [],
     'tier_fixed': 'common',
     'tags': {'base': 'place'},
     'variant': ('minecraft:furnace', 'east'),
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'place_furnace_west',
     'module': 'building',
     'doc': "Place furnace asking facing=west (the jar turns the body by the block's own rule) → the block reports "
            'facing=west',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'furnace', 2)],
     'run': ('place_facing', 'minecraft:furnace', ('@', 3, 0, 0), 'west'),
     'before': [('start', 'place_furnace_west')],
     'check': [('placed_facing', ('@', 3, 0, 0), 'west')],
     'budget': 20,
     'point': 'A',
     'skills': [],
     'tier_fixed': 'common',
     'tags': {'base': 'place'},
     'variant': ('minecraft:furnace', 'west'),
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'nav_from_stairs',
     'module': 'nav',
     'doc': "Walk 10 blocks starting on a stair step (GotoTask's start cell: '1 positions explored' reproduces "
            'here) → at the target',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 12, -1, 3), 'stone'),
               ('setblock', ('@', 0, 0, 0), 'oak_stairs[facing=east]'),
               ('tp', ('@', 0.5, 0.5, 0.5))],
     'run': ('skill', 'travel_to', ('@', 10, 0, 0), 2),
     'before': [('start', 'nav_from_stairs')],
     'check': [('_at', ('@', 10, 0, 0), 3.5)],
     'budget': 25,
     'point': 'A',
     'skills': ['goto'],
     'tier_fixed': 'common',
     'tags': {'base': 'nav', 'start': 'a stair step'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'nav_from_slab',
     'module': 'nav',
     'doc': "Walk 10 blocks starting on a bottom slab (GotoTask's start cell: '1 positions explored' reproduces "
            'here) → at the target',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 12, -1, 3), 'stone'),
               ('setblock', ('@', 0, 0, 0), 'stone_slab'),
               ('tp', ('@', 0.5, 0.5, 0.5))],
     'run': ('skill', 'travel_to', ('@', 10, 0, 0), 2),
     'before': [('start', 'nav_from_slab')],
     'check': [('_at', ('@', 10, 0, 0), 3.5)],
     'budget': 25,
     'point': 'A',
     'skills': ['goto'],
     'tier_fixed': 'common',
     'tags': {'base': 'nav', 'start': 'a bottom slab'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'nav_from_farmland',
     'module': 'nav',
     'doc': "Walk 10 blocks starting on farmland (GotoTask's start cell: '1 positions explored' reproduces here) → "
            'at the target',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 12, -1, 3), 'stone'),
               ('setblock', ('@', 0, -1, 0), 'farmland'),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('skill', 'travel_to', ('@', 10, 0, 0), 2),
     'before': [('start', 'nav_from_farmland')],
     'check': [('_at', ('@', 10, 0, 0), 3.5)],
     'budget': 25,
     'point': 'A',
     'skills': ['goto'],
     'tier_fixed': 'common',
     'tags': {'base': 'nav', 'start': 'farmland'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'nav_from_ladder',
     'module': 'nav',
     'doc': "Walk 10 blocks starting on a ladder on a wall (GotoTask's start cell: '1 positions explored' "
            'reproduces here) → at the target',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 12, -1, 3), 'stone'),
               ('fill', ('@', 1, 0, 0), ('@', 1, 3, 0), 'stone'),
               ('fill', ('@', 0, 0, 0), ('@', 0, 3, 0), 'ladder[facing=west]'),
               ('tp', ('@', 0.5, 2, 0.5))],
     'run': ('skill', 'travel_to', ('@', 10, 0, 0), 2),
     'before': [('start', 'nav_from_ladder')],
     'check': [('_at', ('@', 10, 0, 0), 3.5)],
     'budget': 25,
     'point': 'A',
     'skills': ['goto'],
     'tier_fixed': 'common',
     'tags': {'base': 'nav', 'start': 'a ladder on a wall'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'nav_from_water',
     'module': 'nav',
     'doc': "Walk 10 blocks starting on a pool one deep (GotoTask's start cell: '1 positions explored' reproduces "
            'here) → at the target',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 12, -1, 3), 'stone'),
               ('fill', ('@', -1, 0, -1), ('@', 1, 0, 1), 'water'),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('skill', 'travel_to', ('@', 10, 0, 0), 2),
     'before': [('start', 'nav_from_water')],
     'check': [('_at', ('@', 10, 0, 0), 3.5)],
     'budget': 25,
     'point': 'A',
     'skills': ['goto'],
     'tier_fixed': 'common',
     'tags': {'base': 'nav', 'start': 'a pool one deep'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'eat_while_walking',
     'module': 'skills',
     'doc': 'Hungry, cooked beef carried, 20 blocks to walk → fed on the way without an eat task, still walking '
            "forward while it chewed (ate_on_the_way over the walk's trace)",
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 20, -1, 3), 'stone'),
               ('tp', ('@', -1.5, 0, 0.5)),
               ('give', 'cooked_beef', 4)],
     'run': ('&walk_once',),
     'before': [('start', 'eat_while_walking'), ('&hungry',)],
     'check': [('call', 'ate_on_the_way', [[]]), ('_at', ('@', 18, 0, 0), 3)],
     'budget': 25,
     'point': 'A',
     'skills': ['goto'],
     'tier_fixed': 'common',
     'combat': False,
     'stochastic': False,
     'tags': {'base': 'nav', 'state': 'hungry'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'mine_while_hungry',
     'module': 'skills',
     'doc': 'Hungry, cooked beef carried, 3 cobblestone to mine → mined without a pause to eat: the beef untouched '
            '(control for eat_while_walking)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wooden_pickaxe'),
               ('give', 'cooked_beef', 4),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'mine', 'minecraft:cobblestone', 3, ['stone'], 0),
     'before': [('start', 'mine_while_hungry'), ('&hungry',)],
     'check': [('gain', 'minecraft:cobblestone', 3), ('count', 'minecraft:cooked_beef', '==', 4)],
     'budget': 15,
     'point': 'A',
     'skills': ['mine'],
     'tier_fixed': 'common',
     'combat': False,
     'stochastic': False,
     'tags': {'base': 'mine_stone', 'state': 'hungry'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
]

NOT_EXPRESSED = {
    'mine_stone__interrupt_mid_work': '_on_progress.<locals>.hook: _on_progress: base not kept in its closure',
    'chest_or_tree': "<lambda>: a lambda; a function inside an argument: lambda: _inv_now().count('log') >= 4",
    'smelt_job_interrupted': "<lambda>: a lambda; no comparison for INTERRUPTS.get('smelt_job_interrupted',  … 1",
}
