"""Bench table, exception tier: rows as data in `bench/vocab.py`'s words, built by `bench/table.py`.
FAMILIES: (template, [params, ...]) — one entry, many rows (vocab.TEMPLATES). ROWS: the one-off rows, each in words.
CODE_ROWS: the one-off rows no word earns its place for, written in code with vocab's helpers."""
from ..explore import SEEK_RANGE, TRAVEL_RANGE
from .core import KEPT_HP, ORIGIN
from ..fight_plan import CONFIG as FIGHT_CONFIG

FAMILIES = [
    # S6: the player's hold stops every reflex (the clutch among them); its twin: the agent driving, the clutch runs
    ('fall', [('clutch_breaks_the_fall', False)]),
    ('base', [('sleep', 'sealed_pod'), ('smelt', 'nether'), 
         ('chop', 'pickup_lag'), ('craft', 'inventory_lag'),
         ('smelt', 'interrupt_twice'), ('nav', 'contested'),
         ('nav', 'player_takeover'), ('nav', 'buried_by_sand'), 
         ('chop', 'lava_edge'), 
         
         ('mine_iron', 'tool_one_use'),
         ('chop', 'valuables_full'), ('nav', None, 'nav_sealed_in'), ('craft', None, 'craft_short_of_planks'),
         ('smelt', None, 'smelt_without_fuel'),
         
         
         
         
         
         ('nav', None, 'start_cell_on_a_fence'),
         ('hunt', 'valuables_full'), ('loot', None, 'empty_chest'), ('eat', None, 'eat_with_nothing'), ]),
    ('one', [
         ('tidy_full_bag', ['room:tidy'], 'a full bag of junk → slots free',
          [('floor',), ('stand',), ('give', 'dirt', 2304)], ('skill', 'tidy_inventory'), ('free_slots', 2), 25),
         ('deposit_home_chest', ['room:deposit'], 'a home chest beside the body, a bag of cobblestone → stored',
          [('floor',), ('chest', ('@', 2, 0, 0)), ('stand',), ('give', 'cobblestone', 1280), ('give', 'dirt', 640)],
          ('seq', 1, ('!remember', 'add_site', ['home', ('@', 2, 0, 0), 'minecraft:overworld'], {'name': 'home'}),
           ('!skill', 'deposit')),
          ('all', ('!free_slots', 8), ('!dropped_nothing',)), 25),
         ('pod_open_ground', ['shelter:wall in'], 'night, open ground, 16 blocks → walled in',
          [('floor',), ('stand',), ('give', 'cobblestone', 16), ('time', 18000)], ('skill', 'pod'),
          ('blocks', ('@', -1, 0, -1), ('@', 1, 2, 1), ('cobblestone',), 9), 25),
         ('build_shelter_flat', ['build:shelter'], "flat stone, the hut's materials → a shelter standing",
          [('floor',), ('stand',), ('give', 'cobblestone', 32), ('give', 'oak_door'), ('give', 'torch', 2)],
          ('skill', 'build_shelter'),
          ('all', ('!blocks', ('@', -6, 0, -6), ('@', 6, 3, 6), ('cobblestone',), 14),
           ('!blocks', ('@', -6, 0, -6), ('@', 6, 3, 6), ('oak_door',), 1),
           ('!blocks', ('@', -6, 0, -6), ('@', 6, 3, 6), ('torch', 'wall_torch'), 1)),
          25),
         ('burrow_hillside', ['burrow'], 'night, a stone hillside beside the body → tunnelled in and sealed',
          [('floor',), ('fill', ('@', 2, 0, -4), ('@', 8, 4, 4), 'stone'), ('stand',), ('give', 'stone_pickaxe'),
           ('give', 'cobblestone', 8), ('time', 18000)],
          ('skill', 'burrow'), ('all', ('!alive', 18), ('!call', 'enclosed', [])), 25),
         ('find_air_capped', ['find_air'], 'under water with a stone cap, out of breath → air',
          [('fill', ('@', -4, -4, -4), ('@', 4, 3, 4), 'stone'), ('fill', ('@', -3, -3, -3), ('@', 3, 2, 3), 'water'),
           ('stand', 0, -3), ('give', 'stone_pickaxe')],
          ('skill', 'find_air'), ('all', ('!alive', 10), ('!breathing',)), 25),
         ('footing_in_water', ['reach:footing'], 'treading water, cobblestone carried → a block underfoot',
          [('tank', -4, 4, -4, 4, 0), ('floor', 'water', 4), ('stand',), ('give', 'cobblestone', 8)],
          ('skill', 'stand_on_a_block'), ('all', ('!state', 'onGround'), ('!under_feet', 'cobblestone')), 20),
         ('withdraw_from_chest', ['withdraw'], 'a chest of iron beside the body → 4 ingots taken out',
          [('floor',), ('chest', ('@', 2, 0, 0), 'iron_ingot 9'), ('stand',)],
          ('skill', 'withdraw', 'minecraft:iron_ingot', 4, ('@', 2, 0, 0)), ('gain', 'minecraft:iron_ingot', 4), 25),
         ('take_bed', ['take'], 'a village bed 6 blocks away → carried',
          [('floor',), ('setblock', ('@', 6, 0, 0), 'red_bed'), ('stand',)], ('skill', 'take', 'bed', 1, ['red_bed']),
          ('gain', 'bed', 1), 25),
         ('seek_remembered', ['seek'], 'memory says iron ore 16 blocks away → walked there',
          [('floor', 'stone', 10), ('fill', ('@', 10, -1, -8), ('@', 19, -1, 8), 'stone'),
           ('setblock', ('@', 17, 0, 0), 'iron_ore'), ('stand', -6)],
          ('seq', 1, ('!remember', 'note_seen', ['iron_ore', ('@', 17, 0, 0), 'minecraft:overworld'], {}),
           ('!skill', 'seek', ['iron_ore'])),
          ('arrived', ('@', 17, 0, 0), SEEK_RANGE), 25),
         ('open_space_from_shaft', ['move_to_open_space'],
          'a full bag at the bottom of a 1×1 shaft → out where it is open',
          [('floor', 'stone', 8, 4), ('floor', 'air', 0), ('stand', 0, -3), ('give', 'dirt', 2304),
           ('give', 'stone_pickaxe')],
          ('skill', 'move_to_open_space'), ('room_to_work',), 25),
         ('repair_broken_hut', ['repair_site'], 'a remembered hut with two wall blocks knocked out → rebuilt',
          [('floor',), ('at', 'fill {0} {1} cobblestone hollow', ('@', 2, 0, -2), ('@', 6, 2, 2)),
           ('fill', ('@', 2, 0, 0), ('@', 2, 1, 0), 'air'), ('stand',), ('give', 'cobblestone', 8)],
          ('skill', 'repair_site', ('$call', 'broken_hut', '$ctx')),
          ('blocks', ('@', 2, 0, 0), ('@', 2, 1, 0), ('cobblestone',), 2), 25),
         ('wait_out_the_night', ['wait:day'], 'night in a sealed stone room, no bed → waited until morning',
          [('floor',), ('at', 'fill {0} {1} stone hollow', ('@', -2, 0, -2), ('@', 2, 4, 2)), ('stand', 0, 1),
           ('time', 23500)],
          ('skill', 'wait_for_day'), ('is_day',), 25),
         ('trade_bread', ['trade'], 'a farmer selling bread for an emerald, 3 emeralds → bread',
          [('floor',), ('stand',), ('give', 'emerald', 3),
           ('summon', 'villager', ('@', 3, 0, 0),
            '{NoAI:1b,VillagerData:{profession:"minecraft:farmer",level:2,type:"minecraft:plains"},Offers:{Recipes:[{buy:{id:"minecraft:emerald",count:1},sell:{id:"minecraft:bread",count:6},maxUses:12}]}}')],
          ('skill', 'trade', 'minecraft:bread'), ('gain', 'minecraft:bread', 6), 25),
         ('plant_wheat', ['plant_farm'], 'grass, seeds, a hoe, a water bucket → a wheat plot growing',
          [('floor', 'grass_block'), ('stand',), ('give', 'wheat_seeds', 2), ('give', 'stone_hoe'),
           ('give', 'water_bucket')],
          ('skill', 'plant_farm'), ('blocks', ('@', -4, 0, -4), ('@', 4, 0, 4), ('wheat',), 2), 25),
         ('brew_fire_resistance_stand', ['brew:fire_resistance'],
          'a brewing stand, water bottles, wart, magma cream, blaze powder → fire resistance (the cream spent)',
          [('floor',), ('setblock', ('@', 2, 0, 0), 'brewing_stand'), ('stand',),
           ('give', 'potion[potion_contents={potion:"minecraft:water"}]', 3), ('give', 'nether_wart'),
           ('give', 'magma_cream'), ('give', 'blaze_powder', 2)],
          ('skill', 'brew_fire_resistance'), ('slot_has', 'minecraft:potion', 'fire_resistance'), 25, 60),
         ('collect_auto_smelter', ['collect_machine'],
          'a remembered auto smelter whose output chest holds 8 ingots → taken',
          [('floor',), ('chest', ('@', 3, 0, 0), 'iron_ingot 8'), ('stand',)],
          ('skill', 'collect_machine', ('$call', 'bench_machine', '$ctx', ('@', 3, 0, 0))),
          ('gain', 'minecraft:iron_ingot', 8), 25),
         ('bridge_the_gap', ['bridge_toward'], 'a 6-block gap in the floor toward the target, blocks carried → across',
          [('floor',), ('fill', ('@', 2, -3, -8), ('@', 7, -1, 8), 'air'), ('stand',), ('give', 'cobblestone', 16)],
          ('skill', 'bridge_toward', ('@', 9, 0, 0)), ('arrived', ('@', 9, 0, 0), TRAVEL_RANGE), 25),
         ('breed_cows', ['breed'], 'two cows in a pen, wheat carried → wheat spent on them',
          [('floor', 'grass_block'), ('pen', 'cow', 2), ('stand',), ('give', 'wheat', 4)],
          ('do', 'one_step', ['$ctx', 'breed', 'minecraft:cow', 1, {}], {}),
          ('mobs_near', 'minecraft:cow', 3), 25),
         ('dig_out_morning', ['dig_out'], 'morning, sealed in a 1×1 pocket → out',
          [('floor',), ('fill', ('@', -1, 0, -1), ('@', 1, 2, 1), 'stone'),
           ('fill', ('@', 0, 0, 0), ('@', 0, 1, 0), 'air'), ('stand',), ('give', 'stone_pickaxe')],
          ('skill', 'dig_out'), ('not', ('!call', 'enclosed', [])), 25),
         ('contain_lava_pool', ['contain_lava'], 'an open lava pool beside the body → covered',
          [('floor',), ('fill', ('@', 2, -1, -1), ('@', 3, -1, 1), 'lava'), ('stand',), ('give', 'cobblestone', 16)],
          ('skill', 'contain_lava'), ('blocks', ('@', 2, -1, -1), ('@', 3, -1, 1), ('lava',), 0, 0), 25),
         ('light_the_room', ['light_area'], 'a dark 9×9 room, 8 torches → several placed',
          [('floor',), ('at', 'fill {0} {1} stone hollow', ('@', -6, 0, -6), ('@', 6, 3, 6)),
           ('fill', ('@', -5, 0, -5), ('@', 5, 2, 5), 'air'), ('stand',), ('give', 'torch', 8)],
          ('skill', 'light_area', 6, 4), ('blocks', ('@', -5, 0, -5), ('@', 5, 2, 5), ('torch', 'wall_torch'), 2), 25),
         ('enchant_pickaxe', ['enchant'],
          'an enchanting table, lapis, levels, an iron pickaxe → enchanted (lapis spent)',
          [('floor',), ('setblock', ('@', 2, 0, 0), 'enchanting_table'), ('stand',), ('give', 'iron_pickaxe'),
           ('give', 'lapis_lazuli', 6), ('cmd', 'experience add @p 30 levels')],
          ('skill', 'enchant_item', 'minecraft:iron_pickaxe'),
          ('all', ('!count', 'minecraft:lapis_lazuli', '<', 6), ('!slot_has', 'minecraft:iron_pickaxe', 'enchant')),
          25),
         ('fill_bottles_at_pond', ['fill_bottles'], 'a pond, 3 glass bottles → 3 water bottles',
          [('floor',), ('fill', ('@', 2, -1, -1), ('@', 3, -1, 1), 'water'), ('stand',), ('give', 'glass_bottle', 3)],
          ('skill', 'fill_bottles', 3), ('gain', 'minecraft:potion', 3), 25)
         ]),
    ('real', [
         ('seek_blocks_real', ['seek_blocks'], 'real terrain, a log column 16 blocks off → walked to it',
          ('skill', 'seek_blocks', ['oak_log', 'birch_log', 'spruce_log'], 1, 20),
          ('found_near', ['oak_log', 'birch_log', 'spruce_log'], 8), 25,
          # the real terrain's own trees within 12 cleared first (a 64-radius spread can land in a wood: found
          # within 8 at setup, 0 s), then the column 16 off: the walk to it is the row's
          [('cmd', 'execute at @p run fill ~-12 ~-4 ~-12 ~12 ~12 ~12 air replace #minecraft:logs'),
           ('cmd', 'execute at @p run fill ~16 ~ ~ ~16 ~4 ~ oak_log')], False, (), ['axe']),
         ('strip_mine_real', ['strip_mine_step'], 'real terrain, a stone pickaxe → a mining tunnel started',
          ('skill', 'strip_mine_step', 2), ('gain', 'minecraft:cobblestone', 2), 25,
          [('cmd', 'execute at @p run fill ~-1 17 ~-1 ~1 19 ~1 air'), ('cmd', 'execute at @p run tp @p ~ 17 ~')])]),
    ('place', [('place_observer_up', 'minecraft:observer', 'up', 'up', 'exception'),
         ]),
]
ROWS = [
    # E1/E3 (V4): a drop no walk reaches is left — the jar's approach never digs nor builds to it
    dict(name='collect_unreachable_drop', module='skills',
         doc='A diamond on a 3-high stone pillar, no walk up → the collect fails, the pillar standing, the drop there',
         scene=[('floor',), ('fill', ('@', 3, 0, 0), ('@', 3, 2, 0), 'stone'), ('stand',), ('cmd', 'clear @p'),
                ('give', 'stone_pickaxe'), ('give', 'cobblestone', 16),
                ('summon', 'item', ('@', 3, 3, 0), '{Item:{id:"minecraft:diamond",count:1},PickupDelay:0}')],
         run=('expect_failure', 'collect_unreachable_drop',
              ('!do', 'bonobo.api.run', [{'type': 'collect', 'radius': 6}],
               {'awaits': 'the drop out of every walk: refused', 'wait': 20}), 'reach|path|failed|picking'),
         check=[('unchanged', ('@', 3, 0, 0), ('@', 3, 2, 0), []), ('mobs_near', 'minecraft:item', 1)],
         skills=['travel_to']),
    # S3: inside the home only a table, furnace, chest, bed or light is placed
    dict(name='home_place_refused', module='skills',
         doc='A home box, cobblestone asked into a cell inside it → refused (home), the cell still air',
         scene=[('floor',), ('at', 'fill {0} {1} stone hollow', ('@', 2, 0, -2), ('@', 6, 3, 2)), ('stand',),
                ('cmd', 'clear @p'), ('give', 'cobblestone', 4)],
         before=[('home_box', ('@', 2, 0, -2), ('@', 6, 3, 2))],
         run=('expect_failure', 'home_place_refused', ('!place_into', ('@', 4, 0, 0), 'minecraft:cobblestone'), 'home'),
         check=[('blocks', ('@', 4, 0, 0), ('@', 4, 0, 0), ('cobblestone',), 0, 0)], skills=[]),
    dict(name='recover_items', module='reflexes',
         doc='Died 10 blocks away a minute ago, 3 diamonds lie there → walk back and pick them up.',
         scene=[('fill', ('@', -10, -2, -6), ('@', 12, -1, 6), 'stone'), ('tp', ('@', -6, 0, 0)), ('cmd', 'clear @p')],
         run=('do', 'bonobo.reflexes.recover_items', ['$ctx'], {}),
         before=[('seq', None, ('!remember', 'log_death', [('@', 6, 0, 0), 'minecraft:overworld'], {}),
                  ('!scene_now', [('summon', 'item', ('@', 6, 0, 0),
                                   '{Item:{id:"minecraft:diamond",count:3},Age:-32768}')]))],
         check=[('count', 'minecraft:diamond', '>=', 3)], est=('step', 'goto', '', 1, {'pos': ('@', 6, 0, 0)}),
         expect=[(('@', -10, -1, -6), ('@', 12, -1, 6), 'stone', 299, 299)], skills=['recover_items']),
    dict(name='enter_nether', module='nether',
         doc='A lit 4×5 portal on stone ground → stand in it and arrive in the Nether.',
         scene=[('floor', 'stone', 6, 2), ('fill', ('@', -1, 0, 2), ('@', 2, 4, 2), 'obsidian'),
                ('fill', ('@', 0, 1, 2), ('@', 1, 3, 2), 'nether_portal[axis=x]'), ('tp', ('@', 0, 0, -3)),
                ('cmd', 'clear @p'), ('give', 'flint_and_steel')],
         run=('do', 'bonobo.nether.use_portal', ['$ctx', 'minecraft:the_nether'], {}),
         check=[('state', 'dimension', '==', 'minecraft:the_nether')],
         est=('step', 'portal', 'minecraft:the_nether', 1, {}),
         expect=[(('@', 0, 1, 2), ('@', 1, 3, 2), 'nether_portal', 6, 6),
                 (('@', -1, 0, 2), ('@', 2, 4, 2), 'obsidian', 14, 14)],
         mod_extra=['state'], skills=['use_portal']),
    dict(name='locate_stronghold', module='nether',
         doc=("A flat sky plane under the skill's 200-block sideways leg, speed, 12 eyes → two throws, triangulated "
              'estimate within 64 blocks of /locate.'),
         scene=[('cmd', 'tp @p 10400 201 10400'), ('cmd', 'clear @p'), ('give', 'ender_eye', 12),
                ('give', 'cobblestone', 64), ('give', 'stone_pickaxe'), ('give', 'cooked_beef', 16),
                ('cmd', 'locate structure minecraft:stronghold')],
         run=('do', 'bonobo.nether.locate_stronghold', ['$ctx'], {}), before=[('do', 'stronghold_leg', ['$ctx'], {})],
         check=[('call', 'stronghold_error', [], '<=', 64)], est=('step', 'seek', 'stronghold', 1, {}), raw=True, release=True,
         skills=['locate_stronghold']),
    dict(name='cast_portal', module='building',
         doc=('A 3×3 lava pool beside the body; water bucket, bucket, 16 cobblestone, flint and steel → a portal frame '
              'cast in place and lit (no obsidian carried, no diamond pickaxe).'),
         scene=[('floor',), ('fill', ('@', 2, -1, -1), ('@', 4, -1, 1), 'lava'), ('tp', ('@', 0, 0, 0)),
                ('cmd', 'clear @p'), ('give', 'water_bucket'), ('give', 'bucket'), ('give', 'cobblestone', 16),
                ('give', 'flint_and_steel')],
         run=('do', 'bonobo.building.cast_portal', ['$ctx'], {}),
         check=[('call', 'count_blocks', ['$api', ('@', -8, -1, -8), ('@', 8, 6, 8), 'nether_portal'], '>=', 1)],
         est=('step', 'cast', 'nether_portal', 1, {}),
         expect=[(('@', 2, -1, -1), ('@', 4, -1, 1), 'lava', 9, 9), (('@', -8, 0, -8), ('@', 8, 4, 8), '*', 0, 0)],
         skills=['cast_portal']),
    dict(name='build_light_portal', module='building',
         doc='Flat stone ground, 10 obsidian + 4 cobblestone + flint and steel → a lit nether portal.',
         scene=[('floor', 'stone', 8, 2), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'), ('give', 'obsidian', 10),
                ('give', 'cobblestone', 16), ('give', 'flint_and_steel')],
         run=('do', 'bonobo.building.build_blueprint', ['$ctx', 'nether_portal', ('@', 0, 0, 0)], {}),
         check=[('call', 'count_blocks', ['$api', ('@', -8, 0, -8), ('@', 8, 6, 8), 'nether_portal'], '>=', 6)],
         est=('step', 'build', 'nether_portal', 1, {}),
         expect=[(('@', -8, -1, -8), ('@', 8, -1, 8), 'stone', 289, 289), (('@', -8, 0, -8), ('@', 8, 6, 8), '*', 0, 0)],
         skills=['build_blueprint']),
    dict(name='barter_piglin', module='nether',
         doc='Nether platform, 3 piglins, 2 gold ingots and a carried gold helmet → wear it, barter, collect trades.',
         scene=[('floor', 'netherrack', 8, 2), ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
                ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'), ('tp', ('@', 0, 0, 0)), ('cmd', 'clear @p'),
                ('cmd', 'item replace entity @p armor.feet with golden_boots'), ('give', 'gold_ingot', 2),
                ('give', 'golden_helmet'), ('give', 'iron_sword'),
                ('summon', 'piglin', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
                ('summon', 'piglin', ('@', -4, 0, 2), '{PersistenceRequired:1b}'),
                ('summon', 'piglin', ('@', 2, 0, -4), '{PersistenceRequired:1b}')],
         run=('do', 'bonobo.nether.barter_piglin', ['$ctx', 2], {}),
         check=[('count', 'minecraft:gold_ingot', '<=', 1), ('call', 'trades', ['$inv'], '>=', 1)],
         no_detail='the report line is code: <lambda>: a lambda; a lambda of (inv)',
         est=('step', 'barter', 'minecraft:gold_ingot', 2, {}),
         dimension='minecraft:the_nether', combat=True,
         expect=[(('@', -8, -1, -8), ('@', 8, -1, 8), 'netherrack', 289, 289)],
         expect_entities=[('minecraft:piglin', 3)], tick_rate=60, skills=['barter_piglin']),
    dict(name='await_collect_job', module='farming',
         doc='a remembered furnace job, due, its 3 ingots in the output 2 blocks off → awaited and collected',
         scene=[('floor',), ('setblock', ('@', 2, 0, 0), 'furnace'),
                ('at', 'item replace block {0} container.2 with iron_ingot 3', ('@', 2, 0, 0)), ('stand',)],
         run=('skill', 'await_job', 'minecraft:iron_ingot', 3),
         before=[('start', 'await_collect_job'), ('job_ready_at', ('@', 2, 0, 0), 'minecraft:iron_ingot', 3)],
         check=[('gain', 'minecraft:iron_ingot', 3)],
         est=('step', 'await', 'minecraft:iron_ingot', 3, {}), point='C', skills=['await_job'], tier_fixed='exception', tags={'base': 'sources', 'source': 'job'}),
    dict(name='fill_water_bucket', module='fluids', doc='A 3×3 pond next to the player, empty bucket → water bucket.',
         scene=[('floor', 'stone', 4, 2), ('fill', ('@', 1, -1, -1), ('@', 3, -1, 1), 'water'), ('tp', ('@', -1, 0, 0)),
                ('cmd', 'clear @p'), ('give', 'bucket')],
         run=('do', 'bonobo.fluids.fill_water_bucket', ['$ctx'], {}),
         check=[('count', 'minecraft:water_bucket', '>=', 1)],
         est=('plan', [('minecraft:water_bucket', 1)]),
         expect=[(('@', 1, -1, -1), ('@', 3, -1, 1), 'water', 9, 9),
                 (('@', -4, -1, -4), ('@', 4, -1, 4), 'stone', 72, 72), (('@', -4, 0, -4), ('@', 4, 3, 4), '*', 0, 0)],
         skills=['fill_water_bucket']),
    dict(name='enter_end', module='end', doc='An open end portal in a stronghold room → jump in and arrive in the End.',
         scene=[('floor', 'stone_bricks', 6, 2),
                ('fill', ('@', -1, 0, -2), ('@', 1, 0, -2), 'end_portal_frame[facing=south,eye=true]'),
                ('fill', ('@', -1, 0, 2), ('@', 1, 0, 2), 'end_portal_frame[facing=north,eye=true]'),
                ('fill', ('@', -2, 0, -1), ('@', -2, 0, 1), 'end_portal_frame[facing=east,eye=true]'),
                ('fill', ('@', 2, 0, -1), ('@', 2, 0, 1), 'end_portal_frame[facing=west,eye=true]'),
                ('fill', ('@', -1, 0, -1), ('@', 1, 0, 1), 'end_portal'), ('tp', ('@', 0, 0, -5)), ('cmd', 'clear @p')],
         run=('do', 'bonobo.end.enter_end', ['$ctx'], {}), check=[('state', 'dimension', '==', 'minecraft:the_end')],
         est=('step', 'goto', '', 1, {'pos': ('@', 0, 0, 0)}),
         expect=[(('@', -1, 0, -1), ('@', 1, 0, 1), 'end_portal', 9, 9)], mod=['travel'],
         skills=['enter_end']),
    dict(name='find_portal_room_fresh', module='end',
         doc=('A stronghold piece built every run (a brick corridor, the room 64 blocks on, past the scan), standing '
              'on the estimate → bricks followed, portal frame found and reached.'),
         scene=[('cmd', 'clear @p'), ('give', 'diamond_pickaxe'), ('give', 'cobblestone', 64),
                ('give', 'cooked_beef', 16), ('give', 'torch', 32), ('give', 'water_bucket')],
         run=('&portal_room_run',), before=[('&built_stronghold',)], check=[('call', 'portal_room_found', [])],
         est=('step', 'seek', 'portal_room', 1, {}), raw=True, release=True, skills=['find_portal_room']),
    # measures fight.toml's bed_damage and the blast at the pit (the log's dragon hp per bomb, the body's health)
    dict(name='dragon_perch_window', module='dragon',
         doc=('The real End beside the exit portal, 6 beds, iron kit: the bed pit dug, the dragon made to land '
              '(DragonPhase 3), it perches → the window bombed from the pit, the dragon hurt, alive.'),
         scene=[('cmd', 'clear @p'), ('cmd', 'spreadplayers 0 0 6 10 false @p'), ('give', 'white_bed', 6),
                ('give', 'cooked_beef', 16), ('give', 'diamond_pickaxe'),
                ('cmd', 'item replace entity @p armor.chest with iron_chestplate'),
                ('cmd', 'item replace entity @p armor.head with iron_helmet')],
         before=[('do', 'bonobo.dragon.build_bed_pit', ['$ctx'], {}),
                 ('do', 'chat', ['data merge entity @e[type=minecraft:ender_dragon,limit=1] {DragonPhase:3}'], {}),
                 ('do', 'bonobo.dragon.await_perch', ['$ctx'], {})],
         run=('do', 'bonobo.dragon.bed_bomb_window', ['$ctx'], {}),
         check=[('call', 'dragon_health', [], '<', FIGHT_CONFIG['combat']['dragon_hp']), ('alive',)],
         dimension='minecraft:the_end', combat=True, raw=True, release=True,
         skills=['build_bed_pit', 'await_perch', 'bed_bomb_window']),
    dict(name='craft_chain_one_sitting', module='skills',
         doc=('3 logs and a table carried → planks, sticks and a wooden pickaxe crafted in one sitting (craft_chain: '
              'the table placed and taken back once, not per recipe)'),
         scene=[('floor',), ('stand',), ('cmd', 'clear @p'), ('give', 'oak_log', 3), ('give', 'crafting_table')],
         run=('skill', 'craft_chain', [('planks', 2), ('minecraft:stick', 1), ('minecraft:wooden_pickaxe', 1)]),
         before=[('start', 'craft_chain_one_sitting')], check=[('gain', 'minecraft:wooden_pickaxe', 1, 1)],
         est=('plan', [('minecraft:wooden_pickaxe', 1)]),
         skills=['craft_chain'], tier_fixed='exception', tags={'base': 'craft'})
]
# E4's rows: each runs its step as the brain does (bench.core.one_step), so its price line is judged
E4_ROWS = [dict(r, module=r.get('module', 'skills'), point='C', stochastic=False,
          before=[('start', r['name'])] + r.get('before', []), tags={'base': 'e4'}) for r in [
    dict(name='withdraw_chest', doc='a chest 3 off with 8 sticks, seen open → 4 sticks withdrawn (the withdraw price)',
         scene=[('floor', 'stone', 8, 4), ('chest', ('@', 3, 0, 0), 'stick 8'), ('stand',), ('cmd', 'clear @p')],
         before=[('do', 'chest_known', ['$ctx', ('@', 3, 0, 0), [('minecraft:stick', 8)]], {})],
         run=('do', 'one_step', ['$ctx', 'withdraw', 'minecraft:stick', 4, {'pos': ('@', 3, 0, 0)}], {}),
         check=[('gain', 'minecraft:stick', 4)],
         est=('step', 'withdraw', 'minecraft:stick', 4, {'pos': ('@', 3, 0, 0)}), skills=['withdraw']),
    dict(name='look_chest', doc='a home chest never opened, 24 iron in it → looked into, then the iron withdrawn',
         scene=[('floor', 'stone', 8, 4), ('chest', ('@', 2, 0, 2), 'iron_ingot 24'), ('stand',), ('cmd', 'clear @p')],
         before=[('do', 'home_with_chest', ['$ctx', ('@', 2, 0, 2)], {})],
         run=('seq', None, ('!do', 'one_step', ['$ctx', 'look', 'container', 1, {'pos': ('@', 2, 0, 2)}], {}),
              ('!do', 'one_step', ['$ctx', 'withdraw', 'minecraft:iron_ingot', 24, {'pos': ('@', 2, 0, 2)}], {})),
         check=[('gain', 'minecraft:iron_ingot', 24)],
         est=('sum', ('step', 'look', 'container', 1, {'pos': ('@', 2, 0, 2)}),
              ('step', 'withdraw', 'minecraft:iron_ingot', 24, {'pos': ('@', 2, 0, 2)})), skills=['look', 'withdraw']),
    dict(name='shelter_pod', module='survive', doc='night on stone, blocks carried → walled in a pod',
         scene=[('floor', 'stone', 8, 4), ('stand',), ('cmd', 'clear @p'), ('give', 'cobblestone', 16), ('time', 18000)],
         run=('do', 'one_step', ['$ctx', 'shelter', 'pod', 1, {}], {}), check=[('call', 'enclosed', [])],
         est=('step', 'shelter', 'pod', 1, {}), skills=['pod']),
    dict(name='shelter_hut', module='building', doc="night on stone, the hut's parts carried → the hut standing",
         scene=[('floor', 'stone', 8, 4), ('stand',), ('cmd', 'clear @p'), ('give', 'cobblestone', 16),
                ('give', 'oak_door'), ('give', 'torch'), ('time', 18000)],
         run=('do', 'one_step', ['$ctx', 'shelter', 'hut', 1, {}], {}),
         check=[('blocks', ('@', -8, 0, -8), ('@', 8, 4, 8), ('oak_door',), 1)],
         est=('step', 'shelter', 'hut', 1, {}), skills=['build_shelter']),
    dict(name='store_home', module='store', doc='a full bag at a home with a chest → the bag emptied into it',
         scene=[('floor', 'stone', 8, 4), ('setblock', ('@', 2, 0, 0), 'chest'), ('stand',), ('cmd', 'clear @p'),
                ('give', 'cobblestone', 640), ('give', 'dirt', 640), ('give', 'gravel', 320), ('give', 'chest')],
         before=[('do', 'home_with_chest', ['$ctx', ('@', 2, 0, 0)], {})],
         run=('do', 'one_step', ['$ctx', 'room', 'deposit', 1, {}], {}), check=[('bag', 'used_slots', [], '<', 12)],
         est=('step', 'room', 'deposit', 1, {}), skills=['deposit']),
    dict(name='trade_villager', module='ui', doc='a villager selling bread for an emerald, emeralds carried → bread',
         scene=[('floor', 'stone', 8, 4), ('stand',), ('cmd', 'clear @p'), ('give', 'emerald', 4),
                ('at', 'summon villager {0} {{NoAI:1b,VillagerData:{{profession:"minecraft:farmer",level:2,'
                       'type:"minecraft:plains"}},Offers:{{Recipes:[{{buy:{{id:"minecraft:emerald",count:1}},'
                       'sell:{{id:"minecraft:bread",count:1}},maxUses:12}}]}}}}', ('@', 3, 0, 0))],
         run=('do', 'one_step', ['$ctx', 'trade', 'minecraft:bread', 1, {}], {}),
         check=[('gain', 'minecraft:bread', 1)], est=('step', 'trade', 'minecraft:bread', 1, {}), skills=['trade']),
    dict(name='farm_wheat', module='farming', doc='seeds, a water bucket and a hoe on grass → a plot sown, its wheat '
                                                  'grown under a sprinted clock and reaped (the farm and growth prices, '
                                                  'the growth in game seconds)',
         scene=[('floor', 'grass_block', 8, 4), ('stand',), ('cmd', 'clear @p'), ('give', 'wheat_seeds', 9),
                ('give', 'water_bucket'), ('give', 'wooden_hoe'), ('cmd', 'gamerule random_tick_speed 3')],
         run=('seq', None, ('!do', 'one_step', ['$ctx', 'farm', 'minecraft:wheat', 1, {}], {}),
              ('!do', 'clock_ahead', ['$ctx', 36000], {}),
              ('!do', 'one_step', ['$ctx', 'await', 'minecraft:wheat', 1, {}], {})),
         check=[('gain', 'minecraft:wheat', 1)],
         est=('step', 'farm', 'minecraft:wheat', 1, {}), skills=['plant_farm', 'await_job']),
    dict(name='nav_far', module='nav', doc='a straight stone road across the bench box, 28 blocks east → there (the walk price)',
         scene=[('floor', 'stone', 4, 2), ('fill', ('@', -10, -1, -2), ('@', 20, -1, 2), 'stone'), ('stand', -9)],
         run=('do', 'one_step', ['$ctx', 'goto', '', 1, {'pos': ('@', 19, 0, 0), 'range': 1.5}], {}),
         check=[('arrived', ('@', 19, 0, 0), 1.5)], est=('step', 'goto', '', 1, {'pos': ('@', 19, 0, 0)}),
         skills=['goto']),
    dict(name='nav_hills', module='nav', doc='steps up and down and a wall to go round, 18 blocks on → there (the '
                                             'route factor)',
         scene=[('floor', 'stone', 9, 3), ('fill', ('@', 3, 0, -9), ('@', 5, 0, 9), 'stone'),
                ('fill', ('@', 6, 0, -9), ('@', 8, 1, 9), 'stone'), ('fill', ('@', 9, 0, -9), ('@', 10, 0, 9), 'stone'),
                ('fill', ('@', 13, 0, -6), ('@', 13, 3, 5), 'stone'), ('stand',)],
         run=('do', 'one_step', ['$ctx', 'goto', '', 1, {'pos': ('@', 17, 0, 0), 'range': 1.5}], {}),
         check=[('arrived', ('@', 17, 0, 0), 1.5)], est=('step', 'goto', '', 1, {'pos': ('@', 17, 0, 0)}),
         skills=['goto']),
]]
ROWS += E4_ROWS
# -- one-off rows written in code (no word earns its place): kept as the old sheet wrote them ------------------------
import threading as _threading
import time
from . import core
from .core import NOTES, _c, _chat, _count_blocks, _drain, at
from .vocab import PORTAL_8_OF_10, ROAD_TIMES, _queue, _road_reuse, _worn_head, one_row, real_row
from .words.brain import _container_noted, _fill_bag, _forget_all, _remembered_any
from .words.checks import _alive, _all, _base_count, _free_slots, _gain, _inv_now, _skill, _start
from .words.fight import NETHER_LAVA
from .words.runs import (_achieve_needs, _brain_rounds, _forget_skill_time, _hooks, _interrupt_when, _resume,
    _skill_within, _timed)
from .words.scene import _floor, _grove, _scene_params, _tp, limit, scene



CODE_ROWS = [
    dict(name="dead_flicker_on_respawn",
         doc="Killed at the start of the run: /state reads dead for a moment while the respawn loads — the brain must "
             "respawn, not call every skill dead, and still chop its 4 logs",
         module="brain", point="A", skills=["item:log"], tags={"base": "chop", "surprise": "dead_flicker"},
         setup=_grove((3, 0), (-3, 2)) + [_tp()],
         before=_hooks(_start("dead_flicker_on_respawn"), lambda ctx: _chat("kill @p")),
         run=lambda ctx: (_brain_rounds(15, lambda: not __import__("bonobo.api", fromlist=["get"]).get("/state")["dead"])(ctx),
                          _skill("chop")(ctx, 4))[1],
         check=_all(_alive(10), lambda api, inv: inv.count("log") >= 4), budget=limit()),
    one_row("repair_two_pickaxes", ["repair_tool"], "two worn stone pickaxes → one",
            [("floor",), ("stand",), ("give", "stone_pickaxe[damage=100]"), ("give", "stone_pickaxe[damage=100]")],
            lambda ctx: _skill("repair_tool")(ctx, "pickaxe"),
            lambda api, inv: inv.count("minecraft:stone_pickaxe") == 1 and any(
                s_["id"] == "minecraft:stone_pickaxe" and s_.get("damage", 999) < 100 for s_ in inv.slots), 20),
    one_row("look_in_chest", ["look_in"], "an unopened chest of iron beside the body → what it holds noted, nothing moved",
            [("floor",), ("chest", ("@", 2, 0, 0), "iron_ingot 9"), ("stand",)],
            lambda ctx: _skill("look_in")(ctx, at(2, 0, 0)),
            _container_noted(2, 0, 0, "minecraft:iron_ingot", 9), limit()),
    dict(name="activate_end_portal",
         doc="A stronghold portal ring, 9 frames with eyes and the 3 nearest empty, 3 eyes and a block → a block over "
             "the middle, stood on, the 3 eyes from there: an open end portal ≤ 3 s.",
         module="end", skills=["activate_end_portal"], mod=["travel", "use"], target_s=3.0,
         # 9 frames already hold an eye: the three on our side are the job, so the row fits the limit
         setup=[f"fill {_c(at(-6, -2, -6))} {_c(at(6, -1, 6))} stone_bricks",
                f"fill {_c(at(-1, 0, -2))} {_c(at(1, 0, -2))} end_portal_frame[facing=south]",
                f"fill {_c(at(-1, 0, 2))} {_c(at(1, 0, 2))} end_portal_frame[facing=north,eye=true]",
                f"fill {_c(at(-2, 0, -1))} {_c(at(-2, 0, 1))} end_portal_frame[facing=east,eye=true]",
                f"fill {_c(at(2, 0, -1))} {_c(at(2, 0, 1))} end_portal_frame[facing=west,eye=true]",
                f"fill {_c(at(-1, -1, -1))} {_c(at(1, -1, 1))} lava",
                # beside the ring, a block to put over the middle's lava (end.eye_plan)
                f"tp @p {_c(at(0, 0, -3))}", "clear @p", "give @p ender_eye 3", "give @p cobblestone 1"],
         expect=[(at(-2, 0, -2), at(2, 0, 2), "end_portal_frame", 12, 12)],
         # the speedrun standard from where the job is done: 12 eyes from one spot ≤ 3 s
         run=_timed(lambda ctx: _drain(__import__("bonobo.end", fromlist=["activate_end_portal"]).activate_end_portal(ctx))),
         # open: the 9 portal blocks, or already fallen through them (standing in the middle is the speedrun way)
         check=lambda api, inv: api.get("/state")["dimension"] == "minecraft:the_end"
         or _count_blocks(api, at(-1, 0, -1), at(1, 0, 1), "end_portal") == 9,
         budget=limit()),
    one_row("smelt_in_background", ["start_smelt_job", "collect_job"], "load a furnace, walk off, come back → ingots",
            [("floor",), ("stand",), ("give", "furnace"), ("give", "raw_iron", 2), ("give", "coal", 1)],
            lambda ctx: (_skill("start_smelt_job")(ctx, "minecraft:iron_ingot", "minecraft:raw_iron", 2, "coal"),
                         _chat("tick sprint 400"), time.sleep(2),
                         _skill("collect_job")(ctx, ctx.mem.jobs("minecraft:overworld")[0]))[2],
            _gain("minecraft:iron_ingot", 2), limit()),
    one_row("anvil_repair_pickaxe", ["repair"], "an anvil, a worn diamond pickaxe, diamonds, levels → repaired",
            [("floor",), ("setblock", ("@", 2, 0, 0), "anvil"), ("stand",), ("give", "diamond_pickaxe[damage=1200]"),
             ("give", "diamond", 2), ("cmd", "experience add @p 20 levels")],
            lambda ctx: _skill("anvil_repair")(ctx, "minecraft:diamond_pickaxe", "minecraft:diamond"),
            lambda api, inv: any(s_["id"] == "minecraft:diamond_pickaxe" and s_.get("damage", 0) < 1200
                                 for s_ in inv.slots), limit()),
    dict(name="find_fortress",
         doc="Nether platform, a nether brick hall 18 blocks away → found and remembered as the fortress site.",
         module="nether", dimension="minecraft:the_nether", skills=["find_fortress"],
         setup=[f"fill {_c(at(-6, -2, -6))} {_c(at(20, -1, 6))} netherrack",
                f"fill {_c(at(16, 0, -3))} {_c(at(20, 4, 3))} nether_bricks hollow",
                f"tp @p {_c(at(0, 0, 0))}", "clear @p", "give @p cobblestone 32", "give @p cooked_beef 16"],
         expect=[(at(16, 0, -3), at(20, 4, 3), "nether_bricks", 60, 200)],
         run=lambda ctx: __import__("bonobo.nether", fromlist=["find_fortress"]).find_fortress(ctx),
         check=lambda api, inv: bool(__import__("bonobo.memory", fromlist=["Memory"]).Memory(NOTES)
                                     .sites("minecraft:the_nether", kinds=["fortress"])),
         est=("step", "seek", "fortress", 1, {})),
    real_row("explore_for_animals_real", ["explore_for"], "real terrain, two cows 16 blocks off → found",
             ("skill", "explore_for", ["minecraft:cow", "minecraft:sheep", "minecraft:pig"], 1, 20),
             # judged by what the skill found and noted, never by animals near at setup (the old check, "within 24",
             # held the moment the cows were summoned 16 off: the row passed in 0 s whatever the skill did)
             _remembered_any(["minecraft:cow", "minecraft:sheep", "minecraft:pig"]), limit(),
             [("cmd", "execute at @p run summon cow ~16 ~3 ~"), ("cmd", "execute at @p run summon cow ~16 ~3 ~1")],
             True, before=[_forget_all("minecraft:cow"), _forget_all("minecraft:sheep"), _forget_all("minecraft:pig")])
]
