"""Bench table, core tier: rows as data in `bench/vocab.py`'s words, built by `bench/table.py`.
FAMILIES: (template, [params, ...]) — one entry, many rows (vocab.TEMPLATES). ROWS: the one-off rows, each in words.
Built into the one SCENARIOS by table.py."""
from .core import KEPT_HP

FAMILIES = [
    ('base', [('nav',), ('chop',), ('mine_stone',), ('mine_iron',), ('craft',), ('smelt',), ('hunt',), ('eat',), ('sleep',),
         ('loot',), ('sleep', None, 'bed_in_nether')]),
]
ROWS = [
    dict(name='iron_ingots', module='skills',
         doc=('Stone room, 3 furnaces placed side by side, 3 raw iron + 3 coal carried → 3 iron ingots, one per '
              'furnace in parallel (load, start, wait, collect).'),
         scene=[('floor', 'stone', 8, 4), ('fill', ('@', 2, 0, -1), ('@', 2, 0, 1), 'furnace'), ('tp', ('@', 0, 0, 0)),
                ('cmd', 'clear @p'), ('give', 'raw_iron', 3), ('give', 'coal', 3)],
         run=('do', 'achieve', ['$ctx', [('minecraft:iron_ingot', 3)], ('!now', ('!count', 'minecraft:iron_ingot', '>=', 3))],
              {'rounds': 10}),
         before=[('start', 'iron_ingots'), ('sprint_after', 4, 700), ('sprint_after', 10, 700)],
         check=[('count', 'minecraft:iron_ingot', '>=', 3), ('count', 'minecraft:raw_iron', '==', 0)],
         est=('plan', [('minecraft:iron_ingot', 3)]),
         expect=[(('@', 2, 0, -1), ('@', 2, 0, 1), 'furnace', 3, 3)], tick_rate=60, point='C', chain=1,
         skills=['load_smelter', 'start_smelt_job', 'smelt']),
    dict(name='water_clutch', module='perception',
         doc=('Dropped 30 blocks above stone, a water bucket in the main bag (not the hotbar) → water poured in time '
              '(health ≥ 16) and scooped back (the bucket full again)'),
         scene=[('sheet', '_FALL_FLOOR'), ('give', 'water_bucket')], run=('&wait_landed',),
         before=[('scene_now', [('stand', 0, 30)])],
         check=[('alive', KEPT_HP),
                ('count', 'minecraft:water_bucket', '>=', 1)],
stochastic=False, expect=[(('@', -6, -1, -6), ('@', 6, -1, 6), 'stone', 169, 169)],
         mod=['nets', 'use'], point='B'),
    dict(name='slice_start_tools', module='brain',
         doc=('Slice: the whole cerebellum, a crafting table beside it, planks, sticks and 3 cobblestone carried, a '
              'pickaxe asked → the wooden-then-stone chain by crafting alone, a stone pickaxe in the bag, no loops '
              "(core: what gathering costs is the other rows' job)."),
         scene=[('floor', 'stone', 6, 2), ('setblock', ('@', 1, 0, 1), 'crafting_table'), ('tp', ('@', 0, 0, 0)),
                ('cmd', 'clear @p'), ('cmd', 'time set day'), ('give', 'oak_planks', 6), ('give', 'stick', 4),
                ('give', 'cobblestone', 3)],
         run=('slice', ('&has_stone_pickaxe',), 0.5, None,
              [{'goal': 'have', 'args': {'needs': [['tool', 'pickaxe', 1]]}}]),
         check=[('slice_check', ('&has_stone_pickaxe',))], detail=('&slice_detail',),
         expect=[(('@', 1, 0, 1), ('@', 1, 0, 1), 'crafting_table', 1, 1)], point='C', chain=0),
    dict(name='lava_edge_walk', module='nav',
         doc='A 1-wide stone path between two lava pools to a target 12 blocks on → there, not burnt',
         scene=[('fill', ('@', -3, -3, -4), ('@', 15, -1, 4), 'stone'),
                ('fill', ('@', 0, -1, -3), ('@', 13, -1, -1), 'lava'),
                ('fill', ('@', 0, -1, 1), ('@', 13, -1, 3), 'lava'), ('stand', -1), ('give', 'cobblestone', 32)],
         run=('skill', 'travel_to', ('@', 14, 0, 0), 1.5), before=[('start', 'lava_edge_walk')],
         check=[('arrived', ('@', 14, 0, 0), 1.5), ('alive', 16)],
         est=('step', 'goto', '', 1, {'pos': ('@', 14, 0, 0)}), point='B', skills=['goto'],
         tags={'base': 'nav', 'hazard': 'lava'}),
    dict(name='buried_by_sand', module='brain',
         doc="Sand dropped on the body mid-task → L0 rescues (unbury) through the brain's own round, then alive",
         scene=[('floor',), ('stand',), ('give', 'stone_pickaxe')], run=('brain_rounds', 15, ('&head_clear',)),
         before=[('start', 'buried_by_sand'),
                 # a stone ring round feet and head, so the sand cannot push the body out sideways
                 ('scene_now', [('fill', ('@', -1, 0, -1), ('@', 1, 1, 1), 'stone'),
                                ('fill', ('@', 0, 0, 0), ('@', 0, 3, 0), 'sand')]),
                 ('&buried_first',)],
         check=[('call', 'head_clear', []), ('alive', KEPT_HP)], point='B', skills=['unbury'],
         tags={'base': 'l0', 'hazard': 'suffocating'}),
    dict(name='drowning_in_a_pit', module='brain',
         doc=('Deep in a flooded shaft with little air → L0 surfaces (find_air / surface) before anything else: on the '
              'rim, or breathing with the head out for 2 s'),
         scene=[('tank', -1, 1, -1, 1, 3, None, -4, 'stone'), ('fill', ('@', -1, -3, -1), ('@', 1, 3, 1), 'water'),
                ('fill', ('@', -4, 4, -4), ('@', 4, 4, 4), 'stone'),
                ('fill', ('@', -1, 4, -1), ('@', 1, 4, 1), 'water'), ('fill', ('@', -4, 5, -4), ('@', 4, 7, 4), 'air'),
                ('stand', 0, -3)],
         run=('brain_rounds', 28, ('!now_api', ('!surfaced', 4, 0))), before=[('start', 'drowning_in_a_pit'), ('&drowning_first',)],
         check=[('alive', KEPT_HP), ('surfaced', 4)], point='B', skills=['reach:air'],
         tags={'base': 'l0', 'hazard': 'drowning'}),
] + [dict(r, module=r.get('module', 'skills'), point='C', tier_fixed='exception', stochastic=False,
          before=[('start', r['name'])] + r.get('before', []), tags={'base': 'e4'}) for r in [
    # E4's rows: each runs its step as the brain does, so its price line is judged
    dict(name='withdraw_chest', doc='a chest 3 off with 8 sticks, seen open → 4 sticks withdrawn (the withdraw price)',
         scene=[('floor', 'stone', 8, 4), ('chest', ('@', 3, 0, 0), 'stick 8'), ('stand',), ('cmd', 'clear @p')],
         before=[('do', 'chest_known', ['$ctx', ('@', 3, 0, 0), [('minecraft:stick', 8)]], {})],
         run=('do', 'one_step', ['$ctx', 'withdraw', 'minecraft:stick', 4, {'pos': ('@', 3, 0, 0)}], {}),
         check=[('gain', 'minecraft:stick', 4)],
         est=('step', 'withdraw', 'minecraft:stick', 4, {'pos': ('@', 3, 0, 0)}), skills=['withdraw']),
    dict(name='look_chest', doc='a home chest never opened, 24 iron in it → looked into, then the iron withdrawn',
         scene=[('floor', 'stone', 8, 4), ('chest', ('@', 2, 0, 2), 'iron_ingot 24'), ('stand',), ('cmd', 'clear @p')],
         before=[('do', 'home_with_chest', ['$ctx', ('@', 2, 0, 2)], {})],
         run=('seq', None, ('!do', 'one_step', ['$ctx', 'look', 'container', 1, {'pos': ('@', 2, 0, 2)}], {}),
              ('!do', 'one_step', ['$ctx', 'withdraw', 'minecraft:iron_ingot', 24, {'pos': ('@', 2, 0, 2)}], {})),
         check=[('gain', 'minecraft:iron_ingot', 24)],
         est=('sum', ('step', 'look', 'container', 1, {'pos': ('@', 2, 0, 2)}),
              ('step', 'withdraw', 'minecraft:iron_ingot', 24, {'pos': ('@', 2, 0, 2)})), skills=['look', 'withdraw']),
    dict(name='shelter_pod', module='survive', doc='night on stone, blocks carried → walled in a pod',
         scene=[('floor', 'stone', 8, 4), ('stand',), ('cmd', 'clear @p'), ('give', 'cobblestone', 16), ('time', 18000)],
         run=('do', 'one_step', ['$ctx', 'shelter', 'pod', 1, {}], {}), check=[('call', 'enclosed', [])],
         est=('step', 'shelter', 'pod', 1, {}), skills=['pod']),
    dict(name='shelter_hut', module='building', doc="night on stone, the hut's parts carried → the hut standing",
         scene=[('floor', 'stone', 8, 4), ('stand',), ('cmd', 'clear @p'), ('give', 'cobblestone', 16),
                ('give', 'oak_door'), ('give', 'torch'), ('time', 18000)],
         run=('do', 'one_step', ['$ctx', 'shelter', 'hut', 1, {}], {}),
         check=[('blocks', ('@', -8, 0, -8), ('@', 8, 4, 8), ('oak_door',), 1)],
         est=('step', 'shelter', 'hut', 1, {}), skills=['build_shelter']),
    dict(name='store_home', module='store', doc='a full bag at a home with a chest → the bag emptied into it',
         scene=[('floor', 'stone', 8, 4), ('setblock', ('@', 2, 0, 0), 'chest'), ('stand',), ('cmd', 'clear @p'),
                ('give', 'cobblestone', 640), ('give', 'dirt', 640), ('give', 'gravel', 320), ('give', 'chest')],
         before=[('do', 'home_with_chest', ['$ctx', ('@', 2, 0, 0)], {})],
         run=('do', 'one_step', ['$ctx', 'room', 'deposit', 1, {}], {}), check=[('bag', 'used_slots', [], '<', 12)],
         est=('step', 'room', 'deposit', 1, {}), skills=['deposit']),
    dict(name='trade_villager', module='ui', doc='a villager selling bread for an emerald, emeralds carried → bread',
         scene=[('floor', 'stone', 8, 4), ('stand',), ('cmd', 'clear @p'), ('give', 'emerald', 4),
                ('at', 'summon villager {0} {{NoAI:1b,VillagerData:{{profession:"minecraft:farmer",level:2,'
                       'type:"minecraft:plains"}},Offers:{{Recipes:[{{buy:{{id:"minecraft:emerald",count:1}},'
                       'sell:{{id:"minecraft:bread",count:1}},maxUses:12}}]}}}}', ('@', 3, 0, 0))],
         run=('do', 'one_step', ['$ctx', 'trade', 'minecraft:bread', 1, {}], {}),
         check=[('gain', 'minecraft:bread', 1)], est=('step', 'trade', 'minecraft:bread', 1, {}), skills=['trade']),
    dict(name='farm_wheat', module='farming', doc='seeds, a water bucket and a hoe on grass → a 3×3 plot dug, watered '
                                                  'and sown (the farm price; the growth is longer than a row)',
         scene=[('floor', 'grass_block', 8, 4), ('stand',), ('cmd', 'clear @p'), ('give', 'wheat_seeds', 9),
                ('give', 'water_bucket'), ('give', 'wooden_hoe')],
         run=('do', 'one_step', ['$ctx', 'farm', 'minecraft:wheat', 1, {}], {}),
         check=[('blocks', ('@', -8, 0, -8), ('@', 8, 0, 8), ('wheat',), 4)],
         est=('step', 'farm', 'minecraft:wheat', 1, {}), skills=['plant_farm']),
    dict(name='nav_far', module='nav', doc='a straight stone road 60 blocks east → there (the walk price)',
         scene=[('floor', 'stone', 4, 2), ('fill', ('@', -2, -1, -2), ('@', 62, -1, 2), 'stone'), ('stand',)],
         run=('do', 'one_step', ['$ctx', 'goto', '', 1, {'pos': ('@', 60, 0, 0), 'range': 1.5}], {}),
         check=[('arrived', ('@', 60, 0, 0), 1.5)], est=('step', 'goto', '', 1, {'pos': ('@', 60, 0, 0)}),
         skills=['goto']),
    dict(name='nav_hills', module='nav', doc='steps up and down and a wall to go round, 18 blocks on → there (the '
                                             'route factor)',
         scene=[('floor', 'stone', 9, 3), ('fill', ('@', 3, 0, -9), ('@', 5, 0, 9), 'stone'),
                ('fill', ('@', 6, 0, -9), ('@', 8, 1, 9), 'stone'), ('fill', ('@', 9, 0, -9), ('@', 10, 0, 9), 'stone'),
                ('fill', ('@', 13, 0, -6), ('@', 13, 3, 5), 'stone'), ('stand',)],
         run=('do', 'one_step', ['$ctx', 'goto', '', 1, {'pos': ('@', 17, 0, 0), 'range': 1.5}], {}),
         check=[('arrived', ('@', 17, 0, 0), 1.5)], est=('step', 'goto', '', 1, {'pos': ('@', 17, 0, 0)}),
         skills=['goto']),
]]
