"""Bench table, brain tier: rows as data in `bench/vocab.py`'s words, built by `bench/table.py`.
FAMILIES: (template, [params, ...]) — one entry, many rows (vocab.TEMPLATES). ROWS: the one-off rows, each in words.
NOT_EXPRESSED: old rows kept in the old sheet, with the reason. Not wired to the runner yet."""


FAMILIES = [
    ('brain', [('plan_repair_on_event',
          'Planks + cobblestone + a wooden pickaxe carried (upkeep quiet), a stone pickaxe asked; the table the '
          'plan puts down is taken away → that step is redone, the plan is not started over (≤ 2 plans)',
          [('floor',), ('stand',), ('give', 'oak_planks', 12), ('give', 'cobblestone', 3),
           ('give', 'wooden_pickaxe')],
          [{'goal': 'have', 'args': {'needs': [['tool', 'pickaxe', 1]]}}],
          ('now', ('!count', 'minecraft:stone_pickaxe', '>=', 1)), 0.75,
          ('all', ('!count', 'minecraft:stone_pickaxe', '>=', 1), ('!replans_at_most', 2)),
          [('&count_replans',), ('&remove_table_when_placed',)], ['_count_replans', '_remove_table_when_placed']),
         ('plan_without_events', 'The same with nothing taken away → one plan (control)',
          [('floor',), ('stand',), ('give', 'oak_planks', 12), ('give', 'cobblestone', 3),
           ('give', 'wooden_pickaxe')],
          [{'goal': 'have', 'args': {'needs': [['tool', 'pickaxe', 1]]}}],
          ('now', ('!count', 'minecraft:stone_pickaxe', '>=', 1)), 0.5,
          ('all', ('!count', 'minecraft:stone_pickaxe', '>=', 1), ('!replans_at_most', 1)), [('&count_replans',)],
          ['_count_replans']),
         ('ban_then_other_source', 'Two iron ores, one sealed in barrier → that cell is banned, the other is mined',
          [('floor',), ('fill', ('@', -5, -1, -1), ('@', -3, 1, 1), 'barrier'),
           ('setblock', ('@', -4, 0, 0), 'iron_ore'), ('setblock', ('@', 4, 0, 0), 'iron_ore'), ('stand',),
           ('give', 'stone_pickaxe')],
          [{'goal': 'have', 'args': {'needs': [['minecraft:raw_iron', 1]]}}], ('_count', 'minecraft:raw_iron', 1),
          1,
          ('all', ('!gain', 'minecraft:raw_iron', 1),
           ('!blocks', ('@', -4, 0, 0), ('@', -4, 0, 0), ('iron_ore',), 1, 1),
           ('!blocks', ('@', 4, 0, 0), ('@', 4, 0, 0), ('iron_ore',), 0, 0)),
          [('&clear_bans',)], ['_clear_bans']),
         ('chop_without_interrupt', 'The same with no zombie → no fight is logged, the same 4 logs (control)',
          [('grove', (3, 0)), ('stand',), ('give', 'iron_sword'), ('give', 'diamond_axe'), ('give', 'oak_log', 2)],
          [{'goal': 'have', 'args': {'needs': [['log', 4]]}}], ('now', ('!count', 'log', '>=', 4)), 0.75,
          ('all', ('!count', 'log', '>=', 4), ('!hp_kept', 20), ('!gone', ['minecraft:zombie'])), [], []),
         ('l3_two_goals_in_order', 'Two goals queued (logs, then cobblestone) → both done, in queue order',
          [('grove', (3, 0)), ('fill', ('@', -3, 0, 2), ('@', -2, 1, 3), 'stone'), ('stand',),
           ('give', 'wooden_pickaxe')],
          [{'goal': 'have', 'args': {'needs': [['log', 2]]}},
           {'goal': 'have', 'args': {'needs': [['minecraft:cobblestone', 2]]}}],
          ('now', ('!all', ('!thunk', ('!_count', 'log', 2)), ('!thunk', ('!_count', 'minecraft:cobblestone', 2)))),
          1,
          ('all', ('!before_in_bag', 'log', 'minecraft:cobblestone'), ('!gain', 'log', 2),
           ('!gain', 'minecraft:cobblestone', 2)),
          [('&first_times',)], ['_first_times']),
         ('l3_order_swapped',
          'The same goals queued the other way → done the other way (control: the queue decides, not the cost)',
          [('grove', (3, 0)), ('fill', ('@', -3, 0, 2), ('@', -2, 1, 3), 'stone'), ('stand',),
           ('give', 'wooden_pickaxe')],
          [{'goal': 'have', 'args': {'needs': [['minecraft:cobblestone', 2]]}},
           {'goal': 'have', 'args': {'needs': [['log', 2]]}}],
          ('now', ('!all', ('!thunk', ('!_count', 'log', 2)), ('!thunk', ('!_count', 'minecraft:cobblestone', 2)))),
          1,
          ('all', ('!before_in_bag', 'minecraft:cobblestone', 'log'), ('!gain', 'log', 2),
           ('!gain', 'minecraft:cobblestone', 2)),
          [('&first_times',)], ['_first_times'])]),
    ('cell', [('plenty', 'full', 'fresh', 'surface', 'none', 'room'),
         ('tight', 'full', 'fresh', 'surface', 'none', 'room'),
         ('night', 'full', 'fresh', 'surface', 'none', 'room'),
         ('plenty', 'low', 'fresh', 'surface', 'none', 'room'),
         ('plenty', 'full', 'one_use', 'surface', 'none', 'room'),
         ('plenty', 'full', 'fresh', 'underground', 'none', 'room'),
         ('plenty', 'full', 'fresh', 'surface', 'none', 'junk_full'),
         ('plenty', 'full', 'fresh', 'surface', 'none', 'valuables_full'),
         ('plenty', 'full', 'fresh', 'surface', 'noted', 'room')]),
    ('upkeep', [('reach_land', 'treading water 6 blocks from a shore → on dry land',
          [('tank', -6, 5, -4, 4, 1), ('fill', ('@', -6, -3, -4), ('@', 5, -1, 4), 'water'),
           ('fill', ('@', 6, -3, -4), ('@', 9, -1, 4), 'stone'), ('stand',)],
          [], ('now', ('!all', ('!state', 'onGround'), ('!not', ('!state', 'inWater')))),
          ('all', ('!state', 'onGround'), ('!not', ('!state', 'inWater')))),
         ('dig_out', 'daytime, sealed in stone with a pickaxe → out, not enclosed',
          [('fill', ('@', -4, -2, -4), ('@', 4, 3, 4), 'stone'), ('fill', ('@', 0, 0, 0), ('@', 0, 1, 0), 'air'),
           ('tp', ('@', 1.0, 0, 1.0)), ('give', 'stone_pickaxe')],
          [], ('now', ('!not', ('!call', 'enclosed', []))), ('not', ('!call', 'enclosed', []))),
         ('collect_job', 'a finished background smelt remembered at a furnace 2 blocks off → the ingots in the bag',
          [('floor',), ('setblock', ('@', 2, 0, 0), 'furnace'),
           ('at', 'item replace block {0} container.2 with iron_ingot 3', ('@', 2, 0, 0)), ('stand',)],
          [('job_ready_at', ('@', 2, 0, 0), 'minecraft:iron_ingot', 3)], ('_count', 'minecraft:iron_ingot', 3),
          ('gain', 'minecraft:iron_ingot', 3)),
         ('empty_the_bag', 'a full bag (dirt in every slot) → room made',
          [('floor',), ('stand',), ('give', 'dirt', 2304), ('give', 'stone_pickaxe')], [],
          ('now', ('!bag', 'used_slots', [], '<', 34)), ('bag', 'used_slots', [], '<', 34)),
         ('no_pickaxe', 'no pickaxe, planks + sticks + a table carried → a pickaxe made',
          [('floor',), ('stand',), ('give', 'oak_planks', 6), ('give', 'stick', 4), ('give', 'crafting_table')], [],
          ('now', ('!bag', 'tools', ['pickaxe'])), ('bag', 'tools', ['pickaxe'])),
         ('path_blocked',
          'the last walk failed toward the far side of a 6-block gap, 16 blocks carried → bridged across',
          [('floor',), ('fill', ('@', 2, -3, -8), ('@', 7, -1, 8), 'air'), ('stand',), ('give', 'cobblestone', 16)],
          [('blocked_toward', ('@', 9, 0, 0))], ('now_api', ('!_at', ('@', 9, 0, 0), 4)),
          ('_at', ('@', 9, 0, 0), 4)),
         ('bridge_stock',
          'the same gap with 2 blocks carried (under BRIDGE_MIN), stone underfoot, a pickaxe → blocks fetched '
          'first, to what the way across takes (bridge_stock), then across',
          [('floor',), ('fill', ('@', 2, -3, -8), ('@', 7, -1, 8), 'air'), ('stand',), ('give', 'cobblestone', 2),
           ('give', 'diamond_pickaxe')],
          [('blocked_toward', ('@', 9, 0, 0))],
          ('now',
           ('!any', ('!api_only', ('!_at', ('@', 9, 0, 0), 4)), ('!count', 'minecraft:cobblestone', '>=', 9))),
          ('any', ('!_at', ('@', 9, 0, 0), 4), ('!count', 'minecraft:cobblestone', '>=', 9))),
         ('unstuck',
          'a minute in the same block with the same bag (history set), open ground → moved off (≥ 5 blocks)',
          [('floor',), ('stand',)], [('stuck_for', 70)],
          ('now', ('!not', ('!call', 'near', ['$api', ('@', 0, 0, 0), 5]))),
          ('not', ('!call', 'near', ['$api', ('@', 0, 0, 0), 5]))),
         ('collect_machine', 'a remembered auto smelter whose order is due, 8 ingots in its output chest → taken',
          [('floor',), ('chest', ('@', 3, 0, 0), 'iron_ingot 8'), ('stand',)], [('machine_due', ('@', 3, 0, 0), 8)],
          ('_count', 'minecraft:iron_ingot', 8), ('gain', 'minecraft:iron_ingot', 8)),
         ('eat_when_full', 'fed (food 20), bread carried → not eaten: the bread count unchanged (must not)',
          [('floor',), ('stand',), ('give', 'bread', 4)], [], ('now', ('!constant', False)),
          ('count', 'minecraft:bread', '==', 4)),
         ('shelter_dig_in', 'night, a pickaxe → dug in: below the floor, enclosed',
          [('sheet', '_NIGHT_FLOOR'), ('give', 'stone_pickaxe'), ('give', 'cobblestone', 8)], [], ('&enclosed',),
          ('all', ('!call', 'enclosed', []), ('!state', 'y', '<', 199.5))),
         ('shelter_hut',
          "night, no pickaxe, the hut's materials (cobblestone, a door, a torch) → sheltered by the way the "
          "night's pricing chose",
          [('sheet', '_NIGHT_FLOOR'), ('give', 'cobblestone', 32), ('give', 'oak_door'), ('give', 'torch', 2)], [],
          ('&enclosed',), ('call', 'enclosed', [])),
         ('shelter_wall_in', 'night, no pickaxe, cobblestone only → walled in where it stands',
          [('sheet', '_NIGHT_FLOOR'), ('give', 'cobblestone', 16)], [], ('&enclosed',),
          ('all', ('!call', 'enclosed', []), ('!blocks', ('@', -1, 0, -1), ('@', 1, 2, 1), ('cobblestone',), 9))),
         ('shelter_not_with_a_bed', 'night, a bed and cobblestone carried → slept, no shelter built (must not)',
          [('sheet', '_NIGHT_FLOOR'), ('give', 'white_bed'), ('give', 'cobblestone', 16)], [], ('&is_day_now',),
          ('all', ('!is_day',), ('!blocks', ('@', -3, 0, -3), ('@', 3, 2, 3), ('cobblestone',), 0, 0)))]),
    ('dirt', [('night_dig_in_dirt',
          'dusk on stone, an empty bag, dirt three deep 8 blocks along the platform → walked there, dug in by '
          'hand: two or more down in the dirt, sealed overhead',
          [], ('now', ('!call', 'in_the_patch_underground', ['$api', None])), ('&in_the_patch_underground',)),
         ('night_dig_in_dirt_unreachable',
          "the same dirt across a drop to nothing, a pod's blocks carried → never walked to (must not): walled in "
          'on its own side of the gap',
          [('fill', ('@', 4, -3, -8), ('@', 5, -1, 8), 'air'), ('give', 'cobblestone', 10)], ('&enclosed',),
          ('state', 'blockX', '<', 10004))]),
]

ROWS = [
]

NOT_EXPRESSED = {
    'ban_needs_a_failure': 'a zombie summoned on a 2 s timer: a timed interruption (the rule: by progress only) — fix in the old sheet first',
    'resume_after_combat': 'a zombie summoned on a 1.5 s timer: a timed interruption (the rule: by progress only) — fix in the old sheet first',
    'upkeep__eat': '<lambda>: a lambda; no run target in BASE.update',
    'upkeep__eat_to_regen': '<lambda>: a lambda; no run target in BASE.update',
    'search_night_resume': '_when.<locals>.hook: <lambda>: a lambda; no predicate for (SEARCH_FLAGS.update(sheltered=True), _set_time(0)())',
}
