"""The bases, their conditions and surprises: one small job each, changed one way at a time (vocab.base_row
makes a row of (base, condition | surprise)). Plain data in `vocab`'s words; the tiers' tables name the pairs."""

BASES = {
    'nav': dict(skills=['goto'], doc='walk 8 blocks east over the arena', point='A',
              scene=[('floor',), ('fill', ('@', 8, -3, -3), ('@', 10, -1, 3), 'stone'), ('stand',)],
              run=('skill', 'travel_to', ('@', 8, 0, 0), 2), check=('_at', ('@', 8, 0, 0), 3.5), budget=15,
              arena=16, target=('@', 8, 0, 0)),
    'chop': dict(skills=['item:log'], bound=('log', 2, 10), doc='one oak beside the body → 2 logs', point='A',
               scene=[('grove', (2, 0)), ('stand',)], run=('skill', 'chop', 2), check=('gain', 'log', 2),
               needs=[('log', 2)], effect=('log', 1), budget=15),
    'mine_stone': dict(skills=['mine'], bound=('minecraft:cobblestone', 3, 5),
                     doc='stone floor, a wooden pickaxe → 3 cobblestone', point='A',
                     scene=[('floor',), ('stand',), ('give', 'wooden_pickaxe')],
                     run=('skill', 'mine', 'minecraft:cobblestone', 3, ['stone'], 0),
                     check=('gain', 'minecraft:cobblestone', 3), needs=[('minecraft:cobblestone', 3)],
                     effect=('minecraft:cobblestone', 1), budget=15),
    'mine_iron': dict(skills=['mine'],
                    doc="one iron ore in a stone wall at arm's length, a stone pickaxe → 1 raw iron", point='A',
                    scene=[('floor',), ('fill', ('@', 2, 0, -1), ('@', 3, 2, 1), 'stone'),
                           ('setblock', ('@', 2, 0, 0), 'iron_ore'), ('stand',), ('give', 'stone_pickaxe')],
                    run=('skill', 'mine', 'minecraft:raw_iron', 1, ['iron_ore'], 1),
                    check=('gain', 'minecraft:raw_iron', 1), needs=[('minecraft:raw_iron', 1)],
                    effect=('minecraft:raw_iron', 1), budget=15),
    'craft': dict(skills=['craft'], bound=('minecraft:wooden_pickaxe', 1, 1),
                doc='planks, sticks, a table carried → a wooden pickaxe', point='A',
                scene=[('floor',), ('stand',), ('give', 'oak_planks', 8), ('give', 'stick', 4),
                       ('give', 'crafting_table')],
                run=('skill', 'craft', 'minecraft:wooden_pickaxe', 1),
                check=('gain', 'minecraft:wooden_pickaxe', 1, 1), needs=[('minecraft:wooden_pickaxe', 1)],
                effect=('minecraft:wooden_pickaxe', 1), progress=('planks', 1), budget=15),
    'smelt': dict(skills=['smelt'], bound=('minecraft:iron_ingot', 1, 1),
                doc='a furnace, 1 raw iron, coal → 1 iron ingot', point='A',
                scene=[('floor',), ('stand',), ('give', 'furnace'), ('give', 'raw_iron', 1), ('give', 'coal', 1)],
                run=('skill', 'smelt', 'minecraft:iron_ingot', 'minecraft:raw_iron', 1, 'coal'),
                check=('gain', 'minecraft:iron_ingot', 1, 1), needs=[('minecraft:iron_ingot', 1)],
                effect=('minecraft:iron_ingot', 1), budget=15, pre=('sprint_after', 3, 400)),
    'hunt': dict(skills=['hunt'], doc='a pen of three cows, a sword → 1 beef', point='A',
               scene=[('floor', 'grass_block'), ('pen', 'cow', 3, 5), ('stand',), ('give', 'iron_sword')],
               run=('skill', 'hunt', 'minecraft:beef', 1, ['minecraft:cow'], False),
               check=('gain', 'minecraft:beef', 1), needs=[('minecraft:beef', 1)], effect=('minecraft:beef', 1),
               budget=15, entities=[('minecraft:cow', 3)]),
    'eat': dict(skills=['eat'], doc='hungry, bread carried → the food bar rises', point='A',
              scene=[('floor',), ('stand',), ('give', 'bread', 4)], pre=('hungry',), run=('skill_bare', 'eat'),
              check=('food_up',), budget=15, combat=True),
    'sleep': dict(skills=['sleep'], doc='night, a bed carried → morning', point='A',
                scene=[('floor',), ('stand',), ('give', 'white_bed'), ('time', 18000)],
                run=('skill', 'sleep', ('$ctx', 'policy')), check=('is_day',), budget=15),
    'loot': dict(skills=['loot_chest'], bound=('minecraft:iron_ingot', 5, 5),
               doc='a chest of iron and bread 2 blocks away → the iron', point='A',
               scene=[('floor',), ('chest', ('@', 2, 0, 1), 'iron_ingot 5', 'bread 4'), ('stand',)],
               run=('skill', 'loot_chest'), check=('gain', 'minecraft:iron_ingot', 5),
               effect=('minecraft:iron_ingot', 1), budget=15),
}

CONDITIONS = {
    'canopy': dict(axis='terrain', doc='under a closed leaf canopy', bases=['chop', 'hunt', 'loot', 'nav', 'sleep'],
                 scene=[('fill', ('@', -8, 6, -8), ('@', 8, 7, 8), 'oak_leaves[persistent=true]')]),
    'cave': dict(axis='terrain', doc='in a dark stone room under rock',
               bases=['craft', 'loot', 'mine_stone', 'nav', 'sleep', 'smelt'],
               scene=[('at', 'fill {0} {1} stone outline', ('@', -9, -1, -9), ('@', 15, 4, 9))]),
    'underwater': dict(axis='terrain', doc='the arena flooded two blocks deep', bases=['eat', 'loot', 'nav'],
                     scene=[('at', 'fill {0} {1} glass outline', ('@', -9, -1, -9), ('@', 15, 3, 9)),
                            ('at', 'fill {0} {1} water replace air', ('@', -8, 0, -8), ('@', 14, 1, 8))]),
    'pillar': dict(axis='terrain', doc='starting on top of a 1×1 pillar 10 high', bases=['chop', 'hunt', 'nav'],
                 scene=[('fill', ('@', 0, 0, 0), ('@', 0, 9, 0), 'dirt'), ('stand', 0, 10)]),
    'cliff_edge': dict(axis='terrain', doc='the arena ends in a 20-block drop two blocks behind the body',
                     bases=['chop', 'craft', 'mine_stone', 'nav'],
                     scene=[('fill', ('@', -8, -3, -8), ('@', -3, -1, 8), 'air'), ('stand', -1)]),
    'nether': dict(axis='terrain', doc='the same job in the Nether', bases=['craft', 'mine_stone', 'nav', 'smelt'],
                 dimension='minecraft:the_nether'),
    'night': dict(axis='terrain', doc='at night', bases=['chop', 'hunt', 'loot', 'mine_stone', 'nav'],
                scene=[('time', 18000)]),
    'rain': dict(axis='terrain', doc='in the rain', bases=['chop', 'hunt', 'nav', 'sleep'],
               scene=[('cmd', 'weather rain')]),
    'pickup_lag': dict(axis='timing', doc='the server at 8 ticks/s: drops and slots update late',
                     bases=['chop', 'craft', 'hunt', 'loot', 'mine_iron', 'mine_stone'], tick_rate=8),
    'inventory_lag': dict(axis='timing', doc='the server at 4 ticks/s: the bag reads a craft, a take, a meal late',
                        bases=['craft', 'eat', 'loot', 'smelt'], tick_rate=4),
    'interrupt_mid_work': dict(axis='timing', doc='interrupted mid-work, then resumed by what is still missing',
                             bases=['chop', 'craft', 'hunt', 'mine_iron', 'mine_stone', 'smelt'], interrupt='mid'),
    'interrupt_twice': dict(axis='timing', doc='interrupted twice, resumed twice',
                          bases=['chop', 'hunt', 'mine_stone', 'smelt'], interrupt='twice'),
    'interrupt_at_success': dict(axis='timing', doc='interrupted the moment the effect shows in the bag',
                               bases=['chop', 'craft', 'loot', 'mine_stone', 'smelt'], interrupt='success'),
    'contested': dict(axis='timing', doc='another commander posts a task mid-run (BodyContested), then resume',
                    bases=['chop', 'mine_stone', 'nav'], interrupt='contested'),
    'player_takeover': dict(axis='timing', doc='the player takes control mid-run: stand down, no failure counted',
                          bases=['chop', 'nav'], interrupt='player'),
    'buried_by_sand': dict(axis='hazard', doc='sand drops on the head mid-job', hazard='sand',
                         bases=['chop', 'craft', 'mine_stone', 'nav', 'smelt']),
    'lava_edge': dict(axis='hazard', doc='a lava channel runs along the arena, one block beside the work',
                    hazard='lava', bases=['chop', 'hunt', 'loot', 'mine_stone', 'nav'],
                    scene=[('fill', ('@', -8, -1, 2), ('@', 15, -1, 2), 'lava')]),
    'one_slot': dict(axis='inventory', doc='one free slot left: the product still fits, the job is done',
                   bases=['chop', 'hunt', 'loot', 'mine_stone'], before=('fill_bag', 1)),
    'stack_room': dict(axis='inventory',
                     doc=("no free slot, but the product's own stack has room for all of it → done as usual, no "
                          "'bag full'"),
                     bases=['chop', 'mine_stone'],
                     scene_for={'chop': [('give', 'oak_log', 62)], 'mine_stone': [('give', 'cobblestone', 61)]},
                     before=('fill_bag', 0)),
    'valuables_full': dict(axis='inventory',
                         doc=('every slot full of diamonds: nothing new fits and nothing in the bag may be thrown '
                              '→ failed with the bag named, no diamond lost'),
                         bases=['chop', 'hunt', 'loot', 'mine_stone'], before=('fill_bag', 0, 'diamond'),
                         fails='bag|full|room|slot',
                         fails_check={'chop': ('kept', 'minecraft:diamond'),
                                      'hunt': ('kept', 'minecraft:diamond'),
                                      'loot': ('kept', 'minecraft:diamond'),
                                      'mine_stone': ('kept', 'minecraft:diamond')}),
    'full_bag': dict(axis='inventory', doc='every slot full of dirt: nothing new can be picked up',
                   bases=['chop', 'hunt', 'loot', 'mine_stone'], scene=[('give', 'dirt', 2304)],
                   fails='bag|full|room|slot',
                   fails_check={'chop': ('same_bag',),
                                'hunt': ('same_bag',),
                                'loot': ('same_bag',),
                                'mine_stone': ('same_bag',)}),
    'tool_one_use': dict(axis='inventory', doc='the pickaxe has one use left', bases=['mine_iron', 'mine_stone'],
                       scene=[('cmd', 'clear @p'), ('give', 'wooden_pickaxe[damage=58]'),
                              ('give', 'stone_pickaxe[damage=130]')],
                       fails='pickaxe|tier',
                       fails_check={'mine_iron': ('blocks', ('@', 4, 0, 0), ('@', 4, 1, 0), ('iron_ore',), 1),
                                    'mine_stone': ('gain', 'minecraft:cobblestone', 0, 2)}),
    'wrong_tool': dict(axis='inventory', doc='only a wooden pickaxe for iron ore', bases=['mine_iron'],
                     scene=[('cmd', 'clear @p'), ('give', 'wooden_pickaxe')], fails='tier-1 pickaxe|tier 1|pickaxe',
                     fails_check={'mine_iron': ('all', ('!same_bag',),
                                                ('!blocks', ('@', 4, 0, 0), ('@', 4, 1, 0), ('iron_ore',), 2))}),
    'goal_met': dict(axis='inventory', doc='the bag already holds the goal: plan nothing, do nothing',
                   bases=['chop', 'craft', 'hunt', 'mine_iron', 'mine_stone', 'smelt'], goal_met=True),
}

SURPRISES = {
    'leaves_block_trunk': dict(base='chop', doc='leaves packed round the trunk at head height',
                             scene=[('fill', ('@', 3, 0, -1), ('@', 5, 2, 1), 'oak_leaves[persistent=true]'),
                                    ('fill', ('@', 4, 0, 0), ('@', 4, 4, 0), 'oak_log')]),
    'floating_logs': dict(base='chop', doc='three logs floating 3 blocks up, no trunk under them',
                        scene=[('grove',), ('fill', ('@', 4, 3, 0), ('@', 4, 5, 0), 'oak_log'), ('stand',),
                               ('give', 'dirt', 16)],
                        replace_setup=True, check=('gain', 'log', 2), run_n=2),
    'empty_chest': dict(base='loot', doc='the only chest is empty', replace_setup=True,
                      scene=[('floor',), ('chest', ('@', 5, 0, 1)), ('stand', -1)],
                      fails='empty|nothing|worth|no unlooted',
                      check=('all', ('!same_bag',), ('!blocks', ('@', 5, 0, 1), ('@', 5, 0, 1), ('chest',), 1, 1))),
    'bed_obstructed': dict(base='sleep', doc='a bed carried, the body boxed in a 1×1 cell', replace_setup=True,
                         scene=[('floor',), ('fill', ('@', -1, 0, -1), ('@', 1, 2, 1), 'stone'),
                                ('fill', ('@', 0, 0, 0), ('@', 0, 1, 0), 'air'), ('stand',), ('give', 'white_bed'),
                                ('time', 18000)],
                         fails='no flat 2-block spot|no room|obstruct',
                         check=('all', ('!same_bag',), ('!_not', ('!is_day',)),
                                ('!no_block_suffix', ('@', -3, -1, -3), ('@', 3, 3, 3), '_bed'))),
    'bed_in_nether': dict(base='sleep', doc='night in the Nether, a bed carried: must refuse (it explodes)',
                        dimension='minecraft:the_nether', replace_setup=True,
                        scene=[('floor', 'netherrack'), ('stand',), ('give', 'white_bed'), ('time', 18000)],
                        fails='nether|dimension|explod',
                        check=('all', ('!alive', 18),
                               ('!no_block_suffix', ('@', -4, -1, -4), ('@', 4, 2, 4), '_bed'))),
    'nav_sealed_in': dict(base='nav', doc='the body sealed in bedrock: no way out, and it says so',
                        replace_setup=True,
                        scene=[('floor',), ('fill', ('@', -1, -1, -1), ('@', 1, 2, 1), 'bedrock'),
                               ('fill', ('@', 0, 0, 0), ('@', 0, 1, 0), 'air'), ('stand',)],
                        fails='no route|no path|unreachable|could not get|not reach',
                        check=('all', ('!same_bag',), ('!_at', ('@', 0, 0, 0), 1.5))),
    'craft_short_of_planks': dict(base='craft', doc='two planks and no sticks for a pickaxe: missing, named',
                                replace_setup=True,
                                scene=[('floor',), ('stand',), ('give', 'oak_planks', 2),
                                       ('give', 'crafting_table')],
                                fails='missing|short|not enough', check=('same_bag',)),
    'smelt_without_fuel': dict(base='smelt', doc='a furnace and raw iron, nothing to burn: no fuel, named',
                             replace_setup=True,
                             scene=[('floor',), ('stand',), ('give', 'furnace'), ('give', 'raw_iron', 1)],
                             fails='no coal|fuel|burn', check=('gain', 'minecraft:iron_ingot', 0, 0)),
    'eat_with_nothing': dict(base='eat', doc='hungry, nothing edible carried: nothing to eat, named',
                           replace_setup=True, scene=[('floor',), ('stand',)], fails='nothing edible',
                           check=('same_bag',)),
    'lava_under_ore': dict(base='mine_iron', doc='lava right under the iron ore, blocks carried → sealed, then mined',
                         scene=[('setblock', ('@', 2, -1, 0), 'lava'), ('give', 'cobblestone', 4)],
                         check=('all', ('!gain', 'minecraft:raw_iron', 1), ('!alive', 14))),
    'falling_gravel': dict(base='mine_stone', doc='gravel stacked over the stone to be mined',
                         scene=[('fill', ('@', -3, 0, -3), ('@', 3, 3, 3), 'gravel'),
                                ('fill', ('@', -1, 0, -1), ('@', 1, 3, 1), 'air')],
                         check=('all', ('!gain', 'minecraft:cobblestone', 6), ('!alive', 14))),
    'start_cell_on_a_fence': dict(base='nav',
                                doc=('the walk starts standing on a fence post (the mod judged such a start cell '
                                     "unstandable: '1 positions explored')"),
                                scene=[('setblock', ('@', 0, 0, 0), 'oak_fence'), ('stand', 0, 1.5)]),
    'start_cell_in_a_nook': dict(base='nav', doc='the walk starts in a one-block nook under a slab',
                               scene=[('fill', ('@', -1, 0, -1), ('@', 1, 1, 1), 'stone'),
                                      ('fill', ('@', 0, 0, 0), ('@', 1, 1, 0), 'air'),
                                      ('setblock', ('@', 0, 2, 0), 'stone_slab')]),
}

TARGET_S = {'chop': 10.0, 'mine_stone': 8.0, 'craft': 8.0, 'eat': 2.0, 'find_air': 5.0}     # a base's own speed target (s), × TARGET_SLACK
TARGET_SLACK = 1.5

# The kit rule (bench.core.BEST_TOOLS / weapon_for): the rows whose work uses a tool, by the tools it uses.
KIT = {n: list(jobs) for jobs, names in {
    ('axe',): ['brain__night', 'brain__tight', 'chest_or_tree', 'chop__base', 'chop__lava_edge', 'chop__night',
         'chop__pickup_lag', 'chop__stack_room', 'chop__valuables_full', 'chop_without_interrupt',
         'dead_flicker_on_respawn', 'floating_logs', 'gather_logs', 'gather_logs_birch',
         'interrupted_rescue_is_not_a_failure', 'leaves_block_trunk', 'night_first__low', 'resume_after_combat',
         'seek_blocks_real', 'tidy_then_task__junk_full', 'tidy_then_task__valuables_full'],
    ('axe', 'pickaxe'): ['brain__base', 'l3_order_swapped', 'l3_two_goals_in_order'],
    ('pickaxe',): ['ban_needs_a_failure', 'ban_then_other_source', 'brain__underground', 'bridge_the_gap', 'burrow_hillside',
         'cast_portal', 'dig_out_morning', 'falling_gravel', 'find_air_capped', 'lava_under_ore', 'mine_iron__base',
         'mine_iron__pickup_lag', 'mine_stone__base', 'mine_stone__buried_by_sand', 'mine_stone__cave',
         'mine_stone__full_bag', 'mine_stone__interrupt_mid_work', 'mine_while_hungry', 'night_mines_under_cover',
         'seen_store__noted', 'strip_mine_real'],
    ('pickaxe', 'shovel'): ['dig_in_night'],
    ('shovel',): ['buried_by_sand', 'unbury_sand'],
    ('sword',): ['bed_bomb_kill', 'break_caged_crystal', 'combat__block_gap', 'combat__dig_in', 'combat__fight_and_block',
         'combat__fight_without_shield', 'combat__knocked_off_edge', 'combat__low_hp_eat', 'combat__pillar',
         'combat__shield_arrows', 'combat__surrounded_low', 'combat__wall_in', 'fight_blaze_3', 'fight_creeper_1',
         'fight_creeper_by_home', 'fight_creeper_sword', 'fight_enderman_1', 'fight_skeleton_1', 'fight_zombie_1',
         'fight_zombie_1_full_bag', 'fight_zombie_3', 'hunt__base', 'hunt__lava_edge', 'hunt__one_slot',
         'hunt__pickup_lag', 'hunt__pillar', 'hunt__valuables_full', 'hunt_food', 'siege__w1', 'siege__w2',
         'siege__w3', 'siege__w4', 'siege__w5', 'siege__w6', 'siege__w7'],
}.items() for n in names}
