"""Bench table, exception tier: every row as plain data in `bench/vocab.py`'s words, run through `bench/table.py`.
Written from the old sheet (scenarios.SCENARIOS) by `bench/tabulate.py`; tests/test_bench_tables.py proves each row
builds back to the old one (setup, queue, budget, tier, and the same words for run, check and hooks). Not wired to
the runner yet. NOT_EXPRESSED: the old rows whose code has no words here yet, with the reason."""


ROWS = [
    {'name': 'cast_portal',
     'module': 'building',
     'doc': 'A 3×3 lava pool beside the body; water bucket, bucket, 16 cobblestone, flint and steel → a portal '
            'frame cast in place and lit (no obsidian carried, no diamond pickaxe).',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, -1, -1), ('@', 4, -1, 1), 'lava'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'water_bucket'),
               ('give', 'bucket'),
               ('give', 'cobblestone', 16),
               ('give', 'flint_and_steel'),
               ('give', 'diamond_pickaxe')],
     'run': ('do', 'bonobo.building.cast_portal', ['$ctx'], {}),
     'check': [('call', 'count_blocks', ['$api', ('@', -8, -1, -8), ('@', 8, 6, 8), 'nether_portal'], '>=', 1)],
     'budget': 25,
     'expect': [(('@', 2, -1, -1), ('@', 4, -1, 1), 'lava', 9, 9), (('@', -8, 0, -8), ('@', 8, 4, 8), '*', 0, 0)],
     'skills': ['cast_portal'],
     'point': 'A'},
    {'name': 'build_light_portal',
     'module': 'building',
     'doc': 'Flat stone ground, 10 obsidian + 4 cobblestone + flint and steel → a lit nether portal.',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'obsidian', 10),
               ('give', 'cobblestone', 16),
               ('give', 'flint_and_steel')],
     'run': ('do', 'bonobo.building.build_blueprint', ['$ctx', 'nether_portal', ('@', 0, 0, 0)], {}),
     'check': [('call', 'count_blocks', ['$api', ('@', -8, 0, -8), ('@', 8, 6, 8), 'nether_portal'], '>=', 6)],
     'budget': 25,
     'expect': [(('@', -8, -1, -8), ('@', 8, -1, 8), 'stone', 289, 289),
                (('@', -8, 0, -8), ('@', 8, 6, 8), '*', 0, 0)],
     'skills': ['build_blueprint'],
     'point': 'A'},
    {'name': 'fill_water_bucket',
     'module': 'fluids',
     'doc': 'A 3×3 pond next to the player, empty bucket → water bucket.',
     'scene': [('fill', ('@', -4, -2, -4), ('@', 4, -1, 4), 'stone'),
               ('fill', ('@', 1, -1, -1), ('@', 3, -1, 1), 'water'),
               ('tp', ('@', -1, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'bucket')],
     'run': ('do', 'bonobo.fluids.fill_water_bucket', ['$ctx'], {}),
     'check': [('count', 'minecraft:water_bucket', '>=', 1)],
     'budget': 25,
     'expect': [(('@', 1, -1, -1), ('@', 3, -1, 1), 'water', 9, 9),
                (('@', -4, -1, -4), ('@', 4, -1, 4), 'stone', 72, 72),
                (('@', -4, 0, -4), ('@', 4, 3, 4), '*', 0, 0)],
     'skills': ['fill_water_bucket'],
     'point': 'A'},
    {'name': 'cross_lava_lake',
     'module': 'nav',
     'doc': 'A 12-block lava strip between two stone platforms; cobblestone → reach the far side alive.',
     'scene': [('fill', ('@', -3, -3, -4), ('@', 18, -3, 4), 'stone'),
               ('fill', ('@', -2, -2, -3), ('@', 17, -1, 3), 'lava'),
               ('fill', ('@', -2, -1, -3), ('@', 1, -1, 3), 'stone'),
               ('fill', ('@', 14, -1, -3), ('@', 17, -1, 3), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'cobblestone', 64),
               ('give', 'diamond_pickaxe')],
     'run': ('do', 'bonobo.nav.go_to', [('@', 15, 0, 0), ('$ctx', 'policy')], {'range_': 1.5}),
     'check': [('call', 'near', ['$api', ('@', 15, 0, 0), 2.5]), ('state', 'health', '>', 10)],
     'budget': 25,
     'expect': [(('@', 2, -1, -3), ('@', 13, -1, 3), 'lava', 84, 84),
                (('@', -2, -1, -3), ('@', 1, -1, 3), 'stone', 28, 28),
                (('@', -2, 0, -3), ('@', 17, 4, 3), '*', 0, 0)],
     'skills': ['travel_to'],
     'point': 'A'},
    {'name': 'gather_logs',
     'module': 'wood',
     'doc': 'A small grove; empty bag → 4 logs (speed wood).',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -2, 8), 'dirt'),
               ('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('at', 'place feature minecraft:oak {0}', ('@', 4, 0, 0)),
               ('at', 'place feature minecraft:oak {0}', ('@', -4, 0, 3)),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'diamond_axe')],
     'run': ('do', 'bonobo.wood.chop', ['$ctx', 4], {}),
     'check': [('count', 'log', '>=', 4)],
     'budget': 25,
     'expect': [(('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block', 285, 289),
                (('@', -8, 0, -8), ('@', 8, 8, 8), 'oak_log', 6, 20)],
     'skills': ['chop'],
     'point': 'A'},
    {'name': 'enter_nether',
     'module': 'nether',
     'doc': 'A lit 4×5 portal on stone ground → stand in it and arrive in the Nether.',
     'scene': [('fill', ('@', -6, -2, -6), ('@', 6, -1, 6), 'stone'),
               ('fill', ('@', -1, 0, 2), ('@', 2, 4, 2), 'obsidian'),
               ('fill', ('@', 0, 1, 2), ('@', 1, 3, 2), 'nether_portal[axis=x]'),
               ('tp', ('@', 0, 0, -3)),
               ('cmd', 'clear @p'),
               ('give', 'flint_and_steel')],
     'run': ('do', 'bonobo.nether.use_portal', ['$ctx', 'minecraft:the_nether'], {}),
     'check': [('state', 'dimension', '==', 'minecraft:the_nether')],
     'budget': 20,
     'expect': [(('@', 0, 1, 2), ('@', 1, 3, 2), 'nether_portal', 6, 6),
                (('@', -1, 0, 2), ('@', 2, 4, 2), 'obsidian', 14, 14)],
     'mod_extra': ['state'],
     'skills': ['use_portal'],
     'point': 'A'},
    {'name': 'barter_piglin',
     'module': 'nether',
     'doc': 'Nether platform, 3 piglins, 2 gold ingots and a carried gold helmet → wear it, barter, collect '
            'trades.',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'netherrack'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('cmd', 'item replace entity @p armor.feet with golden_boots'),
               ('give', 'gold_ingot', 2),
               ('give', 'golden_helmet'),
               ('give', 'iron_sword'),
               ('summon', 'piglin', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
               ('summon', 'piglin', ('@', -4, 0, 2), '{PersistenceRequired:1b}'),
               ('summon', 'piglin', ('@', 2, 0, -4), '{PersistenceRequired:1b}')],
     'run': ('do', 'bonobo.nether.barter_piglin', ['$ctx', 2], {}),
     'check': [('count', 'minecraft:gold_ingot', '<=', 1), ('call', 'trades', ['$inv'], '>=', 1)],
     'no_detail': 'the report line is code: <lambda>: a lambda; a lambda of (inv)',
     'budget': 25,
     'dimension': 'minecraft:the_nether',
     'combat': True,
     'expect': [(('@', -8, -1, -8), ('@', 8, -1, 8), 'netherrack', 289, 289)],
     'expect_entities': [('minecraft:piglin', 3)],
     'tick_rate': 60,
     'skills': ['barter_piglin'],
     'point': 'A'},
    {'name': 'enter_end',
     'module': 'end',
     'doc': 'An open end portal in a stronghold room → jump in and arrive in the End.',
     'scene': [('fill', ('@', -6, -2, -6), ('@', 6, -1, 6), 'stone_bricks'),
               ('fill', ('@', -1, 0, -2), ('@', 1, 0, -2), 'end_portal_frame[facing=south,eye=true]'),
               ('fill', ('@', -1, 0, 2), ('@', 1, 0, 2), 'end_portal_frame[facing=north,eye=true]'),
               ('fill', ('@', -2, 0, -1), ('@', -2, 0, 1), 'end_portal_frame[facing=east,eye=true]'),
               ('fill', ('@', 2, 0, -1), ('@', 2, 0, 1), 'end_portal_frame[facing=west,eye=true]'),
               ('fill', ('@', -1, 0, -1), ('@', 1, 0, 1), 'end_portal'),
               ('tp', ('@', 0, 0, -5)),
               ('cmd', 'clear @p')],
     'run': ('do', 'bonobo.end.enter_end', ['$ctx'], {}),
     'check': [('state', 'dimension', '==', 'minecraft:the_end')],
     'budget': 20,
     'expect': [(('@', -1, 0, -1), ('@', 1, 0, 1), 'end_portal', 9, 9)],
     'mod': ['travel'],
     'skills': ['enter_end'],
     'point': 'A'},
    {'name': 'craft_stone_tools',
     'module': 'skills',
     'doc': 'Stone floor, 6 oak logs → crafting table, wooden then stone pickaxe (plan-driven).',
     'scene': [('fill', ('@', -8, -4, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'oak_log', 6)],
     'run': ('do', 'achieve', ['$ctx', [('tool', 'pickaxe', 1)], ('!inv_has', 'minecraft:stone_pickaxe', 1)], {}),
     'check': [('count', 'minecraft:stone_pickaxe', '>=', 1)],
     'budget': 25,
     'expect': [(('@', -8, -1, -8), ('@', 8, -1, 8), 'stone', 289, 289)],
     'skills': ['craft', 'mine', 'chop'],
     'point': 'A'},
    {'name': 'hunt_food',
     'module': 'skills',
     'doc': 'Grass pen with 4 cows, iron sword → 3 raw beef.',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', -9, 0, -9), ('@', 9, 0, -9), 'oak_fence'),
               ('fill', ('@', -9, 0, 9), ('@', 9, 0, 9), 'oak_fence'),
               ('fill', ('@', -9, 0, -8), ('@', -9, 0, 8), 'oak_fence'),
               ('fill', ('@', 9, 0, -8), ('@', 9, 0, 8), 'oak_fence'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'iron_sword'),
               ('summon', 'cow', ('@', 4, 0, 3)),
               ('summon', 'cow', ('@', -4, 0, 2)),
               ('summon', 'cow', ('@', 3, 0, -5)),
               ('summon', 'cow', ('@', -5, 0, -4)),
               ('give', 'iron_sword')],
     'run': ('do', 'bonobo.skills.hunt', ['$ctx', 'minecraft:beef', 3, ['minecraft:cow'], False], {}),
     'check': [('count', 'minecraft:beef', '>=', 3)],
     'budget': 25,
     'combat': False,
     'expect': [(('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block', 289, 289)],
     'expect_entities': [('minecraft:cow', 4)],
     'skills': ['hunt'],
     'point': 'A'},
    {'name': 'craft_eyes',
     'module': 'skills',
     'doc': '6 blaze rods + 12 ender pearls → 12 eyes of ender (plan-driven, table placed on the way).',
     'scene': [('fill', ('@', -6, -2, -6), ('@', 6, -1, 6), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'blaze_rod', 6),
               ('give', 'ender_pearl', 12),
               ('give', 'crafting_table')],
     'run': ('do', 'achieve', ['$ctx', [('minecraft:ender_eye', 12)], ('!inv_has', 'minecraft:ender_eye', 12)], {}),
     'check': [('count', 'minecraft:ender_eye', '>=', 12)],
     'budget': 25,
     'expect': [(('@', -6, -1, -6), ('@', 6, -1, 6), 'stone', 169, 169)],
     'mod': ['craft', 'use', 'travel'],
     'skills': ['craft'],
     'point': 'A'},
    {'name': 'return_from_nether',
     'module': 'nether',
     'doc': 'Nether side: a lit portal 6 blocks away → walk in and arrive in the Overworld.',
     'scene': [('fill', ('@', -6, -2, -6), ('@', 6, -1, 6), 'netherrack'),
               ('fill', ('@', -1, 0, 4), ('@', 2, 4, 4), 'obsidian'),
               ('fill', ('@', 0, 1, 4), ('@', 1, 3, 4), 'nether_portal[axis=x]'),
               ('tp', ('@', 0, 0, -2)),
               ('cmd', 'clear @p'),
               ('give', 'flint_and_steel'),
               ('give', 'cobblestone', 16)],
     'run': ('do', 'bonobo.nether.use_portal', ['$ctx', 'minecraft:overworld'], {}),
     'check': [('state', 'dimension', '==', 'minecraft:overworld')],
     'budget': 20,
     'dimension': 'minecraft:the_nether',
     'expect': [(('@', 0, 1, 4), ('@', 1, 3, 4), 'nether_portal', 6, 6)],
     'mod_extra': ['state'],
     'skills': ['use_portal'],
     'point': 'A'},
    {'name': 'locate_stronghold',
     'module': 'nether',
     'doc': "A flat sky plane under the skill's 200-block sideways leg, speed, 12 eyes → two throws, triangulated "
            'estimate within 64 blocks of /locate.',
     'scene': [('cmd', 'tp @p 10400 201 10400'),
               ('cmd', 'clear @p'),
               ('give', 'ender_eye', 12),
               ('give', 'cobblestone', 64),
               ('give', 'stone_pickaxe'),
               ('give', 'cooked_beef', 16),
               ('cmd', 'locate structure minecraft:stronghold')],
     'run': ('do', 'bonobo.nether.locate_stronghold', ['$ctx'], {}),
     'before': [('do', 'stronghold_leg', ['$ctx'], {})],
     'check': [('call', 'stronghold_error', [], '<=', 64)],
     'budget': 25,
     'raw': True,
     'release': True,
     'skills': ['locate_stronghold'],
     'point': 'A'},
    {'name': 'find_portal_room_fresh',
     'module': 'end',
     'doc': 'A stronghold piece built every run (a brick corridor, the room 64 blocks on, past the scan), standing '
            'on the estimate → bricks followed, portal frame found and reached.',
     'scene': [('cmd', 'clear @p'),
               ('give', 'diamond_pickaxe'),
               ('give', 'cobblestone', 64),
               ('give', 'cooked_beef', 16),
               ('give', 'torch', 32),
               ('give', 'water_bucket')],
     'run': ('&portal_room_run',),
     'before': [('&built_stronghold',)],
     'check': [('call', 'portal_room_found', [])],
     'budget': 25,
     'raw': True,
     'release': True,
     'skills': ['find_portal_room'],
     'point': 'A'},
    {'name': 'loot_chest',
     'module': 'loot',
     'doc': 'A chest with 5 iron ingots and bread 6 blocks away → take the valuable stacks.',
     'scene': [('fill', ('@', -6, -2, -6), ('@', 6, -1, 6), 'stone'),
               ('setblock', ('@', 5, 0, 1), 'chest'),
               ('at', 'item replace block {0} container.0 with iron_ingot 5', ('@', 5, 0, 1)),
               ('at', 'item replace block {0} container.1 with bread 4', ('@', 5, 0, 1)),
               ('tp', ('@', -1, 0, 0)),
               ('cmd', 'clear @p')],
     'run': ('do', 'bonobo.loot.loot_chest', ['$ctx'], {}),
     'check': [('count', 'minecraft:iron_ingot', '>=', 5)],
     'budget': 20,
     'expect': [(('@', 5, 0, 1), ('@', 5, 0, 1), 'chest', 1, 1)],
     'mod': ['travel', 'use'],
     'skills': ['loot_chest'],
     'point': 'A'},
    {'name': 'fall_without_bucket',
     'module': 'perception',
     'doc': "The same fall with no bucket (control): the fall hurts — dead, or health ≤ 10 — so water_clutch's "
            "pass is the bucket's doing",
     'scene': [('fill', ('@', -6, -2, -6), ('@', 6, -1, 6), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'dirt', 576)],
     'run': ('&wait_landed',),
     'before': [('do', 'chat', ['tp @p 10000.5 230 10000.5'], {})],
     'check': [('any', ('!state', 'dead'), ('!state', 'health', '<=', 10))],
     'budget': 15,
     'stochastic': False,
     'expect': [(('@', -6, -1, -6), ('@', 6, -1, 6), 'stone', 169, 169)],
     'skills': [],
     'point': 'A'},
    {'name': 'retreat_from_nether',
     'module': 'brain',
     'doc': 'Nether, hurt to 6 hp with one food, the arrival portal 8 blocks away → upkeep retreats through it.',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'netherrack'),
               ('fill', ('@', -1, 0, 6), ('@', 2, 4, 6), 'obsidian'),
               ('fill', ('@', 0, 1, 6), ('@', 1, 3, 6), 'nether_portal[axis=x]'),
               ('tp', ('@', 0, 0, -2)),
               ('cmd', 'clear @p'),
               ('give', 'cooked_beef', 1),
               ('give', 'cobblestone', 16)],
     'run': ('&snap_survival',),
     'before': [('do', 'chat', ['damage @p 14 minecraft:generic'], {})],
     'check': [('state', 'dimension', '==', 'minecraft:overworld')],
     'budget': 25,
     'dimension': 'minecraft:the_nether',
     'expect': [(('@', 0, 1, 6), ('@', 1, 3, 6), 'nether_portal', 6, 6)],
     'mod_extra': ['state'],
     'skills': ['use_portal'],
     'point': 'A'},
    {'name': 'find_fortress_far',
     'module': 'nether',
     'doc': 'The real Nether: ~20 blocks from a fortress (lava sea likely between), blocks + food → fortress '
            'found.',
     'scene': [('cmd', 'spreadplayers 0 0 0 8 under 90 false @p'),
               ('cmd', 'locate structure minecraft:fortress'),
               ('cmd', 'clear @p'),
               ('give', 'cobblestone', 128),
               ('give', 'diamond_pickaxe'),
               ('give', 'cooked_beef', 32),
               ('give', 'flint_and_steel'),
               ('cmd', 'item replace entity @p armor.head with golden_helmet'),
               ('cmd', 'item replace entity @p armor.chest with iron_chestplate')],
     'run': ('do', 'bonobo.nether.find_fortress', ['$ctx'], {}),
     'before': [('&far_from_fortress',)],
     'check': [('call', 'found_fortress_now', [])],
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:the_nether',
     'release': True,
     'skills': ['find_fortress'],
     'point': 'A'},
    {'name': 'trek_overworld_30',
     'module': 'nav',
     'doc': 'Real Overworld terrain (hills, forest, water), 30 blocks east (18 walked: arrival is 12 off), basic '
            'kit → arrive; seconds per 100 blocks.',
     'scene': [('cmd', 'spreadplayers 10600 10600 0 4 false @p'),
               ('cmd', 'clear @p'),
               ('give', 'stone_pickaxe'),
               ('give', 'stone_axe'),
               ('give', 'cobblestone', 64),
               ('give', 'cooked_beef', 16),
               ('give', 'oak_boat')],
     'run': ('trek', 30, 0),
     'check': [('call', 'trek_check', ['$api'])],
     'detail': ('&trek_detail',),
     'budget': 25,
     'raw': True,
     'release': True,
     'mod': ['travel'],
     'skills': [],
     'point': 'A'},
    {'name': 'trek_nether_25',
     'module': 'nav',
     'doc': 'Real Nether terrain below the roof, 25 blocks (13 walked), kit with gold helmet → arrive; seconds per '
            '100 blocks.',
     'scene': [('cmd', 'spreadplayers 300 300 0 8 under 90 false @p'),
               ('cmd', 'clear @p'),
               ('give', 'diamond_pickaxe'),
               ('give', 'cobblestone', 128),
               ('give', 'cooked_beef', 16),
               ('cmd', 'item replace entity @p armor.head with golden_helmet')],
     'run': ('trek', 25, 0),
     'check': [('call', 'trek_check', ['$api'])],
     'detail': ('&trek_detail',),
     'budget': 25,
     'raw': True,
     'combat': True,
     'dimension': 'minecraft:the_nether',
     'release': True,
     'mod': ['travel'],
     'skills': [],
     'point': 'A'},
    {'name': 'cross_lava_3',
     'module': 'nav',
     'doc': 'A 3-block lava strip between two stone platforms; cobblestone → reach the far side alive.',
     'scene': [('fill', ('@', -3, -3, -4), ('@', 9, -3, 4), 'stone'),
               ('fill', ('@', -2, -2, -3), ('@', 8, -1, 3), 'lava'),
               ('fill', ('@', -2, -1, -3), ('@', 1, -1, 3), 'stone'),
               ('fill', ('@', 5, -1, -3), ('@', 8, -1, 3), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'cobblestone', 64),
               ('give', 'diamond_pickaxe')],
     'run': ('do', 'bonobo.nav.go_to', [('@', 6, 0, 0), ('$ctx', 'policy')], {'range_': 1.5}),
     'check': [('call', 'near', ['$api', ('@', 6, 0, 0), 2.5]), ('state', 'health', '>', 10)],
     'budget': 22,
     'expect': [(('@', 2, -1, -3), ('@', 4, -1, 3), 'lava', 21, 21),
                (('@', -2, -1, -3), ('@', 1, -1, 3), 'stone', 28, 28),
                (('@', -2, 0, -3), ('@', 8, 4, 3), '*', 0, 0)],
     'skills': ['travel_to'],
     'point': 'A'},
    {'name': 'gather_logs_birch',
     'module': 'wood',
     'doc': 'Two birches (taller, thin crowns); empty bag → 4 logs.',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -2, 8), 'dirt'),
               ('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('at', 'place feature minecraft:birch {0}', ('@', 4, 0, 0)),
               ('at', 'place feature minecraft:birch {0}', ('@', -4, 0, 3)),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'diamond_axe')],
     'run': ('do', 'bonobo.wood.chop', ['$ctx', 4], {}),
     'check': [('count', 'log', '>=', 4)],
     'budget': 25,
     'expect': [(('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block', 285, 289),
                (('@', -8, 0, -8), ('@', 8, 8, 8), 'birch_log', 8, 20)],
     'skills': ['chop'],
     'point': 'A'},
    {'name': 'break_caged_crystal',
     'module': 'end',
     'doc': 'A caged end crystal on a 6-high obsidian pillar, blocks + water bucket + sword → towered up, bars '
            'broken, crystal destroyed, alive.',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 5, 0, 0), ('@', 5, 5, 0), 'obsidian'),
               ('at', 'fill {0} {1} iron_bars hollow', ('@', 4, 6, -1), ('@', 6, 8, 1)),
               ('fill', ('@', 5, 6, 0), ('@', 5, 7, 0), 'air'),
               ('summon', 'end_crystal', ('@', 5, 6, 0), '{ShowBottom:0b}'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 32),
               ('give', 'water_bucket'),
               ('give', 'iron_sword'),
               ('give', 'stone_pickaxe'),
               ('give', 'diamond_sword')],
     'run': ('skill', 'break_caged_crystal', ('$call', 'one_crystal', '$ctx')),
     'check': [('not', ('!call', 'crystals_left', ['$api', '$inv'])), ('not', ('!state', 'dead'))],
     'budget': 25,
     'skills': ['break_caged_crystal'],
     'expect': [(('@', 5, 0, 0), ('@', 5, 5, 0), 'obsidian', 6, 6)],
     'expect_entities': [('minecraft:end_crystal', 1)],
     'point': 'A'},
    {'name': 'hunt__pillar',
     'module': 'skills',
     'doc': 'a pen of three cows, a sword → 1 beef — starting on top of a 1×1 pillar 10 high',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', -5, 0, -5), ('@', 5, 0, -5), 'oak_fence'),
               ('fill', ('@', -5, 0, 5), ('@', 5, 0, 5), 'oak_fence'),
               ('fill', ('@', -5, 0, -4), ('@', -5, 0, 4), 'oak_fence'),
               ('fill', ('@', 5, 0, -4), ('@', 5, 0, 4), 'oak_fence'),
               ('summon', 'cow', ('@', 3, 0, 2)),
               ('summon', 'cow', ('@', -3, 0, 2)),
               ('summon', 'cow', ('@', 2, 0, -4)),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('fill', ('@', 0, 0, 0), ('@', 0, 9, 0), 'dirt'),
               ('tp', ('@', 0.5, 10, 0.5)),
               ('give', 'iron_sword')],
     'run': ('skill', 'hunt', 'minecraft:beef', 1, ['minecraft:cow'], False),
     'before': [('start', 'hunt__pillar')],
     'check': [('gain', 'minecraft:beef', 1)],
     'budget': 15,
     'skills': ['hunt'],
     'point': 'A',
     'tags': {'base': 'hunt', 'terrain': 'pillar'},
     'expect_entities': [('minecraft:cow', 3)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'craft__cliff_edge',
     'module': 'skills',
     'doc': 'planks, sticks, a table carried → a wooden pickaxe — the arena ends in a 20-block drop two blocks '
            'behind the body',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_planks', 8),
               ('give', 'stick', 4),
               ('give', 'crafting_table'),
               ('fill', ('@', -8, -3, -8), ('@', -3, -1, 8), 'air'),
               ('tp', ('@', -0.5, 0, 0.5))],
     'run': ('skill', 'craft', 'minecraft:wooden_pickaxe', 1),
     'before': [('start', 'craft__cliff_edge')],
     'check': [('gain', 'minecraft:wooden_pickaxe', 1, 1)],
     'budget': 15,
     'skills': ['craft'],
     'point': 'A',
     'tags': {'base': 'craft', 'terrain': 'cliff_edge'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'smelt__nether',
     'module': 'skills',
     'doc': 'a furnace, 1 raw iron, coal → 1 iron ingot — the same job in the Nether',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'furnace'),
               ('give', 'raw_iron', 1),
               ('give', 'coal', 1)],
     'run': ('skill', 'smelt', 'minecraft:iron_ingot', 'minecraft:raw_iron', 1, 'coal'),
     'before': [('start', 'smelt__nether'), ('sprint_after', 3, 400)],
     'check': [('gain', 'minecraft:iron_ingot', 1, 1)],
     'budget': 15,
     'skills': ['smelt'],
     'point': 'A',
     'tags': {'base': 'smelt', 'terrain': 'nether'},
     'dimension': 'minecraft:the_nether',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'sleep__rain',
     'module': 'skills',
     'doc': 'night, a bed carried → morning — in the rain',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'white_bed'),
               ('time', 18000),
               ('cmd', 'weather rain')],
     'run': ('skill', 'sleep', ('$ctx', 'policy')),
     'before': [('start', 'sleep__rain')],
     'check': [('is_day',)],
     'budget': 15,
     'skills': ['sleep'],
     'point': 'A',
     'tags': {'base': 'sleep', 'terrain': 'rain'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'chop__pickup_lag',
     'module': 'skills',
     'doc': 'one oak beside the body → 2 logs — the server at 8 ticks/s: drops and slots update late',
     'scene': [('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 2, 0),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'diamond_axe')],
     'run': ('skill', 'chop', 2),
     'before': [('start', 'chop__pickup_lag')],
     'check': [('gain', 'log', 2)],
     'budget': 25,
     'skills': ['item:log'],
     'point': 'A',
     'tags': {'base': 'chop', 'timing': 'pickup_lag'},
     'tick_rate': 8,
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'mine_iron__pickup_lag',
     'module': 'skills',
     'doc': "one iron ore in a stone wall at arm's length, a stone pickaxe → 1 raw iron — the server at 8 ticks/s: "
            'drops and slots update late',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, 0, -1), ('@', 3, 2, 1), 'stone'),
               ('setblock', ('@', 2, 0, 0), 'iron_ore'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'mine', 'minecraft:raw_iron', 1, ['iron_ore'], 1),
     'before': [('start', 'mine_iron__pickup_lag')],
     'check': [('gain', 'minecraft:raw_iron', 1)],
     'budget': 25,
     'skills': ['mine'],
     'point': 'A',
     'tags': {'base': 'mine_iron', 'timing': 'pickup_lag'},
     'tick_rate': 8,
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'hunt__pickup_lag',
     'module': 'skills',
     'doc': 'a pen of three cows, a sword → 1 beef — the server at 8 ticks/s: drops and slots update late',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', -5, 0, -5), ('@', 5, 0, -5), 'oak_fence'),
               ('fill', ('@', -5, 0, 5), ('@', 5, 0, 5), 'oak_fence'),
               ('fill', ('@', -5, 0, -4), ('@', -5, 0, 4), 'oak_fence'),
               ('fill', ('@', 5, 0, -4), ('@', 5, 0, 4), 'oak_fence'),
               ('summon', 'cow', ('@', 3, 0, 2)),
               ('summon', 'cow', ('@', -3, 0, 2)),
               ('summon', 'cow', ('@', 2, 0, -4)),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'iron_sword')],
     'run': ('skill', 'hunt', 'minecraft:beef', 1, ['minecraft:cow'], False),
     'before': [('start', 'hunt__pickup_lag')],
     'check': [('gain', 'minecraft:beef', 1)],
     'budget': 25,
     'skills': ['hunt'],
     'point': 'A',
     'tags': {'base': 'hunt', 'timing': 'pickup_lag'},
     'tick_rate': 8,
     'expect_entities': [('minecraft:cow', 3)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'craft__inventory_lag',
     'module': 'skills',
     'doc': 'planks, sticks, a table carried → a wooden pickaxe — the server at 4 ticks/s: the bag reads a craft, '
            'a take, a meal late',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_planks', 8),
               ('give', 'stick', 4),
               ('give', 'crafting_table')],
     'run': ('skill', 'craft', 'minecraft:wooden_pickaxe', 1),
     'before': [('start', 'craft__inventory_lag')],
     'check': [('gain', 'minecraft:wooden_pickaxe', 1, 1)],
     'budget': 25,
     'skills': ['craft'],
     'point': 'A',
     'tags': {'base': 'craft', 'timing': 'inventory_lag'},
     'tick_rate': 4,
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'loot__interrupt_at_success',
     'module': 'skills',
     'doc': 'a chest of iron and bread 2 blocks away → the iron — interrupted the moment the effect shows in the '
            'bag',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 2, 0, 1), 'chest'),
               ('at', 'item replace block {0} container.0 with iron_ingot 5', ('@', 2, 0, 1)),
               ('at', 'item replace block {0} container.1 with bread 4', ('@', 2, 0, 1)),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('resume',
             'loot__interrupt_at_success',
             ('!skill', 'loot_chest'),
             ('!unless_done', ('!gain', 'minecraft:iron_ingot', 5), ('!skill', 'loot_chest'))),
     'before': [('start', 'loot__interrupt_at_success'),
                ('interrupt_when',
                 ('!gained_at_least', 'minecraft:iron_ingot', 1),
                 None,
                 'bench: interrupt at the moment of success')],
     'check': [('gain', 'minecraft:iron_ingot', 5, 5), ('interrupted',)],
     'budget': 15,
     'skills': ['loot_chest'],
     'point': 'A',
     'tags': {'base': 'loot', 'timing': 'interrupt_at_success'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'chop__lava_edge',
     'module': 'skills',
     'doc': 'one oak beside the body → 2 logs — a lava channel runs along the arena, one block beside the work',
     'scene': [('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 2, 0),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('fill', ('@', -8, -1, 2), ('@', 15, -1, 2), 'lava'),
               ('give', 'diamond_axe')],
     'run': ('after_l0',
             'chop__lava_edge',
             ('!skill', 'chop', 2),
             ('!unless_done', ('!gain', 'log', 2), ('!achieve_needs', [('log', 2)]))),
     'before': [('start', 'chop__lava_edge')],
     'check': [('gain', 'log', 2), ('alive', 8), ('call', 'head_clear', []), ('not', ('!state', 'inLava'))],
     'budget': 15,
     'skills': ['item:log'],
     'point': 'A',
     'tags': {'base': 'chop', 'hazard': 'lava_edge'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'hunt__lava_edge',
     'module': 'skills',
     'doc': 'a pen of three cows, a sword → 1 beef — a lava channel runs along the arena, one block beside the '
            'work',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', -5, 0, -5), ('@', 5, 0, -5), 'oak_fence'),
               ('fill', ('@', -5, 0, 5), ('@', 5, 0, 5), 'oak_fence'),
               ('fill', ('@', -5, 0, -4), ('@', -5, 0, 4), 'oak_fence'),
               ('fill', ('@', 5, 0, -4), ('@', 5, 0, 4), 'oak_fence'),
               ('summon', 'cow', ('@', 3, 0, 2)),
               ('summon', 'cow', ('@', -3, 0, 2)),
               ('summon', 'cow', ('@', 2, 0, -4)),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('fill', ('@', -8, -1, 2), ('@', 15, -1, 2), 'lava'),
               ('give', 'iron_sword')],
     'run': ('after_l0',
             'hunt__lava_edge',
             ('!skill', 'hunt', 'minecraft:beef', 1, ['minecraft:cow'], False),
             ('!unless_done', ('!gain', 'minecraft:beef', 1), ('!achieve_needs', [('minecraft:beef', 1)]))),
     'before': [('start', 'hunt__lava_edge')],
     'check': [('gain', 'minecraft:beef', 1),
               ('alive', 8),
               ('call', 'head_clear', []),
               ('not', ('!state', 'inLava'))],
     'budget': 15,
     'skills': ['hunt'],
     'point': 'A',
     'tags': {'base': 'hunt', 'hazard': 'lava_edge'},
     'expect_entities': [('minecraft:cow', 3)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'loot__lava_edge',
     'module': 'skills',
     'doc': 'a chest of iron and bread 2 blocks away → the iron — a lava channel runs along the arena, one block '
            'beside the work',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 2, 0, 1), 'chest'),
               ('at', 'item replace block {0} container.0 with iron_ingot 5', ('@', 2, 0, 1)),
               ('at', 'item replace block {0} container.1 with bread 4', ('@', 2, 0, 1)),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('fill', ('@', -8, -1, 2), ('@', 15, -1, 2), 'lava')],
     'run': ('after_l0',
             'loot__lava_edge',
             ('!skill', 'loot_chest'),
             ('!unless_done', ('!gain', 'minecraft:iron_ingot', 5), ('!skill', 'loot_chest'))),
     'before': [('start', 'loot__lava_edge')],
     'check': [('gain', 'minecraft:iron_ingot', 5),
               ('alive', 8),
               ('call', 'head_clear', []),
               ('not', ('!state', 'inLava'))],
     'budget': 15,
     'skills': ['loot_chest'],
     'point': 'A',
     'tags': {'base': 'loot', 'hazard': 'lava_edge'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'hunt__one_slot',
     'module': 'skills',
     'doc': 'a pen of three cows, a sword → 1 beef — one free slot left: the product still fits, the job is done',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', -5, 0, -5), ('@', 5, 0, -5), 'oak_fence'),
               ('fill', ('@', -5, 0, 5), ('@', 5, 0, 5), 'oak_fence'),
               ('fill', ('@', -5, 0, -4), ('@', -5, 0, 4), 'oak_fence'),
               ('fill', ('@', 5, 0, -4), ('@', 5, 0, 4), 'oak_fence'),
               ('summon', 'cow', ('@', 3, 0, 2)),
               ('summon', 'cow', ('@', -3, 0, 2)),
               ('summon', 'cow', ('@', 2, 0, -4)),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'iron_sword')],
     'run': ('skill', 'hunt', 'minecraft:beef', 1, ['minecraft:cow'], False),
     'before': [('start', 'hunt__one_slot'), ('fill_bag', 1)],
     'check': [('gain', 'minecraft:beef', 1)],
     'budget': 15,
     'skills': ['hunt'],
     'point': 'A',
     'tags': {'base': 'hunt', 'inventory': 'one_slot'},
     'expect_entities': [('minecraft:cow', 3)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'chop__stack_room',
     'module': 'skills',
     'doc': "one oak beside the body → 2 logs — no free slot, but the product's own stack has room for all of it → "
            "done as usual, no 'bag full'",
     'scene': [('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 2, 0),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_log', 62),
               ('give', 'diamond_axe')],
     'run': ('skill', 'chop', 2),
     'before': [('start', 'chop__stack_room'), ('fill_bag', 0)],
     'check': [('gain', 'log', 2)],
     'budget': 15,
     'skills': ['item:log'],
     'point': 'A',
     'tags': {'base': 'chop', 'inventory': 'stack_room'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'chop__valuables_full',
     'module': 'skills',
     'doc': 'one oak beside the body → 2 logs — every slot full of diamonds: nothing new fits and nothing in the '
            'bag may be thrown → failed with the bag named, no diamond lost',
     'scene': [('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 2, 0),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'diamond_axe')],
     'run': ('expect_failure', 'chop__valuables_full', ('!skill', 'chop', 2), 'bag|full|room|slot'),
     'before': [('start', 'chop__valuables_full'), ('fill_bag', 0, 'diamond')],
     'check': [('failed_as_expected',), ('alive',), ('kept', 'minecraft:diamond')],
     'budget': 15,
     'skills': ['item:log'],
     'point': 'A',
     'tags': {'base': 'chop', 'inventory': 'valuables_full'},
     'fails': 'bag|full|room|slot',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'hunt__valuables_full',
     'module': 'skills',
     'doc': 'a pen of three cows, a sword → 1 beef — every slot full of diamonds: nothing new fits and nothing in '
            'the bag may be thrown → failed with the bag named, no diamond lost',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', -5, 0, -5), ('@', 5, 0, -5), 'oak_fence'),
               ('fill', ('@', -5, 0, 5), ('@', 5, 0, 5), 'oak_fence'),
               ('fill', ('@', -5, 0, -4), ('@', -5, 0, 4), 'oak_fence'),
               ('fill', ('@', 5, 0, -4), ('@', 5, 0, 4), 'oak_fence'),
               ('summon', 'cow', ('@', 3, 0, 2)),
               ('summon', 'cow', ('@', -3, 0, 2)),
               ('summon', 'cow', ('@', 2, 0, -4)),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_sword'),
               ('give', 'iron_sword')],
     'run': ('expect_failure',
             'hunt__valuables_full',
             ('!skill', 'hunt', 'minecraft:beef', 1, ['minecraft:cow'], False),
             'bag|full|room|slot'),
     'before': [('start', 'hunt__valuables_full'), ('fill_bag', 0, 'diamond')],
     'check': [('failed_as_expected',), ('alive',), ('kept', 'minecraft:diamond')],
     'budget': 15,
     'skills': ['hunt'],
     'point': 'A',
     'tags': {'base': 'hunt', 'inventory': 'valuables_full'},
     'fails': 'bag|full|room|slot',
     'expect_entities': [('minecraft:cow', 3)],
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'loot__valuables_full',
     'module': 'skills',
     'doc': 'a chest of iron and bread 2 blocks away → the iron — every slot full of diamonds: nothing new fits '
            'and nothing in the bag may be thrown → failed with the bag named, no diamond lost',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 2, 0, 1), 'chest'),
               ('at', 'item replace block {0} container.0 with iron_ingot 5', ('@', 2, 0, 1)),
               ('at', 'item replace block {0} container.1 with bread 4', ('@', 2, 0, 1)),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('expect_failure', 'loot__valuables_full', ('!skill', 'loot_chest'), 'bag|full|room|slot'),
     'before': [('start', 'loot__valuables_full'), ('fill_bag', 0, 'diamond')],
     'check': [('failed_as_expected',), ('alive',), ('kept', 'minecraft:diamond')],
     'budget': 15,
     'skills': ['loot_chest'],
     'point': 'A',
     'tags': {'base': 'loot', 'inventory': 'valuables_full'},
     'fails': 'bag|full|room|slot',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'mine_iron__tool_one_use',
     'module': 'skills',
     'doc': "one iron ore in a stone wall at arm's length, a stone pickaxe → 1 raw iron — the pickaxe has one use "
            'left',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, 0, -1), ('@', 3, 2, 1), 'stone'),
               ('setblock', ('@', 2, 0, 0), 'iron_ore'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('cmd', 'clear @p'),
               ('give', 'wooden_pickaxe[damage=58]'),
               ('give', 'stone_pickaxe[damage=130]')],
     'run': ('expect_failure',
             'mine_iron__tool_one_use',
             ('!skill', 'mine', 'minecraft:raw_iron', 1, ['iron_ore'], 1),
             'pickaxe|tier'),
     'before': [('start', 'mine_iron__tool_one_use')],
     'check': [('failed_as_expected',), ('alive',), ('blocks', ('@', 4, 0, 0), ('@', 4, 1, 0), ('iron_ore',), 1)],
     'budget': 15,
     'skills': ['mine'],
     'point': 'A',
     'tags': {'base': 'mine_iron', 'inventory': 'tool_one_use'},
     'fails': 'pickaxe|tier',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'mine_iron__wrong_tool',
     'module': 'skills',
     'doc': "one iron ore in a stone wall at arm's length, a stone pickaxe → 1 raw iron — only a wooden pickaxe "
            'for iron ore',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, 0, -1), ('@', 3, 2, 1), 'stone'),
               ('setblock', ('@', 2, 0, 0), 'iron_ore'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('cmd', 'clear @p'),
               ('give', 'wooden_pickaxe')],
     'run': ('expect_failure',
             'mine_iron__wrong_tool',
             ('!skill', 'mine', 'minecraft:raw_iron', 1, ['iron_ore'], 1),
             'tier-1 pickaxe|tier 1|pickaxe'),
     'before': [('start', 'mine_iron__wrong_tool')],
     'check': [('failed_as_expected',),
               ('alive',),
               ('all', ('!same_bag',), ('!blocks', ('@', 4, 0, 0), ('@', 4, 1, 0), ('iron_ore',), 2))],
     'budget': 15,
     'skills': ['mine'],
     'point': 'A',
     'tags': {'base': 'mine_iron', 'inventory': 'wrong_tool'},
     'fails': 'tier-1 pickaxe|tier 1|pickaxe',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'craft__goal_met',
     'module': 'skills',
     'doc': 'planks, sticks, a table carried → a wooden pickaxe — the bag already holds the goal: plan nothing, do '
            'nothing',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_planks', 8),
               ('give', 'stick', 4),
               ('give', 'crafting_table'),
               ('give', 'wooden_pickaxe', 1)],
     'run': ('plan_is_empty', [('minecraft:wooden_pickaxe', 1)]),
     'before': [('start', 'craft__goal_met')],
     'check': [('same_bag_and_place',)],
     'budget': 15,
     'skills': ['craft'],
     'point': 'A',
     'tags': {'base': 'craft', 'inventory': 'goal_met'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'smelt__goal_met',
     'module': 'skills',
     'doc': 'a furnace, 1 raw iron, coal → 1 iron ingot — the bag already holds the goal: plan nothing, do nothing',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'furnace'),
               ('give', 'raw_iron', 1),
               ('give', 'coal', 1),
               ('give', 'iron_ingot', 1)],
     'run': ('plan_is_empty', [('minecraft:iron_ingot', 1)]),
     'before': [('start', 'smelt__goal_met'), ('sprint_after', 3, 400)],
     'check': [('same_bag_and_place',)],
     'budget': 15,
     'skills': ['smelt'],
     'point': 'A',
     'tags': {'base': 'smelt', 'inventory': 'goal_met'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'leaves_block_trunk',
     'module': 'skills',
     'doc': 'one oak beside the body → 2 logs — leaves packed round the trunk at head height',
     'scene': [('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tree', 2, 0),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('fill', ('@', 3, 0, -1), ('@', 5, 2, 1), 'oak_leaves[persistent=true]'),
               ('fill', ('@', 4, 0, 0), ('@', 4, 4, 0), 'oak_log'),
               ('give', 'diamond_axe')],
     'run': ('skill', 'chop', 2),
     'before': [('start', 'leaves_block_trunk')],
     'check': [('gain', 'log', 2)],
     'budget': 15,
     'skills': ['item:log'],
     'point': 'A',
     'tags': {'base': 'chop', 'surprise': 'leaves_block_trunk'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'floating_logs',
     'module': 'skills',
     'doc': 'one oak beside the body → 2 logs — three logs floating 3 blocks up, no trunk under them',
     'scene': [('fill', ('@', -8, -1, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', 4, 3, 0), ('@', 4, 5, 0), 'oak_log'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'dirt', 16),
               ('give', 'diamond_axe')],
     'run': ('skill', 'chop', 2),
     'before': [('start', 'floating_logs')],
     'check': [('gain', 'log', 2)],
     'budget': 15,
     'skills': ['item:log'],
     'point': 'A',
     'tags': {'base': 'chop', 'surprise': 'floating_logs'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'empty_chest',
     'module': 'skills',
     'doc': 'a chest of iron and bread 2 blocks away → the iron — the only chest is empty',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 5, 0, 1), 'chest'),
               ('tp', ('@', -0.5, 0, 0.5))],
     'run': ('expect_failure', 'empty_chest', ('!skill', 'loot_chest'), 'empty|nothing|worth|no unlooted'),
     'before': [('start', 'empty_chest')],
     'check': [('failed_as_expected',),
               ('alive',),
               ('all', ('!same_bag',), ('!blocks', ('@', 5, 0, 1), ('@', 5, 0, 1), ('chest',), 1, 1))],
     'budget': 15,
     'skills': ['loot_chest'],
     'point': 'A',
     'tags': {'base': 'loot', 'surprise': 'empty_chest'},
     'fails': 'empty|nothing|worth|no unlooted',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'bed_obstructed',
     'module': 'skills',
     'doc': 'night, a bed carried → morning — a bed carried, the body boxed in a 1×1 cell',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', -1, 0, -1), ('@', 1, 2, 1), 'stone'),
               ('fill', ('@', 0, 0, 0), ('@', 0, 1, 0), 'air'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'white_bed'),
               ('time', 18000)],
     'run': ('expect_failure',
             'bed_obstructed',
             ('!skill', 'sleep', ('$ctx', 'policy')),
             'no flat 2-block spot|no room|obstruct'),
     'before': [('start', 'bed_obstructed')],
     'check': [('failed_as_expected',),
               ('alive',),
               ('all',
                ('!same_bag',),
                ('!_not', ('!is_day',)),
                ('!no_block_suffix', ('@', -3, -1, -3), ('@', 3, 3, 3), '_bed'))],
     'budget': 15,
     'skills': ['sleep'],
     'point': 'A',
     'tags': {'base': 'sleep', 'surprise': 'bed_obstructed'},
     'fails': 'no flat 2-block spot|no room|obstruct',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'nav_sealed_in',
     'module': 'skills',
     'doc': 'walk 8 blocks east over the arena — the body sealed in bedrock: no way out, and it says so',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', -1, -1, -1), ('@', 1, 2, 1), 'bedrock'),
               ('fill', ('@', 0, 0, 0), ('@', 0, 1, 0), 'air'),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('expect_failure',
             'nav_sealed_in',
             ('!skill', 'travel_to', ('@', 8, 0, 0), 2),
             'no route|no path|unreachable|could not get|not reach'),
     'before': [('start', 'nav_sealed_in')],
     'check': [('failed_as_expected',), ('alive',), ('all', ('!same_bag',), ('!_at', ('@', 0, 0, 0), 1.5))],
     'budget': 15,
     'skills': ['goto'],
     'point': 'A',
     'tags': {'base': 'nav', 'surprise': 'nav_sealed_in'},
     'fails': 'no route|no path|unreachable|could not get|not reach',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'craft_short_of_planks',
     'module': 'skills',
     'doc': 'planks, sticks, a table carried → a wooden pickaxe — two planks and no sticks for a pickaxe: missing, '
            'named',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_planks', 2),
               ('give', 'crafting_table')],
     'run': ('expect_failure',
             'craft_short_of_planks',
             ('!skill', 'craft', 'minecraft:wooden_pickaxe', 1),
             'missing|short|not enough'),
     'before': [('start', 'craft_short_of_planks')],
     'check': [('failed_as_expected',), ('alive',), ('same_bag',)],
     'budget': 15,
     'skills': ['craft'],
     'point': 'A',
     'tags': {'base': 'craft', 'surprise': 'craft_short_of_planks'},
     'fails': 'missing|short|not enough',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'smelt_without_fuel',
     'module': 'skills',
     'doc': 'a furnace, 1 raw iron, coal → 1 iron ingot — a furnace and raw iron, nothing to burn: no fuel, named',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'furnace'),
               ('give', 'raw_iron', 1)],
     'run': ('expect_failure',
             'smelt_without_fuel',
             ('!skill', 'smelt', 'minecraft:iron_ingot', 'minecraft:raw_iron', 1, 'coal'),
             'no coal|fuel|burn'),
     'before': [('start', 'smelt_without_fuel'), ('sprint_after', 3, 400)],
     'check': [('failed_as_expected',), ('alive',), ('gain', 'minecraft:iron_ingot', 0, 0)],
     'budget': 15,
     'skills': ['smelt'],
     'point': 'A',
     'tags': {'base': 'smelt', 'surprise': 'smelt_without_fuel'},
     'fails': 'no coal|fuel|burn',
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'lava_under_ore',
     'module': 'skills',
     'doc': "one iron ore in a stone wall at arm's length, a stone pickaxe → 1 raw iron — lava right under the "
            'iron ore, blocks carried → sealed, then mined',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, 0, -1), ('@', 3, 2, 1), 'stone'),
               ('setblock', ('@', 2, 0, 0), 'iron_ore'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('setblock', ('@', 2, -1, 0), 'lava'),
               ('give', 'cobblestone', 4),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'mine', 'minecraft:raw_iron', 1, ['iron_ore'], 1),
     'before': [('start', 'lava_under_ore')],
     'check': [('gain', 'minecraft:raw_iron', 1), ('alive', 14)],
     'budget': 15,
     'skills': ['mine'],
     'point': 'A',
     'tags': {'base': 'mine_iron', 'surprise': 'lava_under_ore'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'falling_gravel',
     'module': 'skills',
     'doc': 'stone floor, a wooden pickaxe → 3 cobblestone — gravel stacked over the stone to be mined',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wooden_pickaxe'),
               ('fill', ('@', -3, 0, -3), ('@', 3, 3, 3), 'gravel'),
               ('fill', ('@', -1, 0, -1), ('@', 1, 3, 1), 'air'),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'mine', 'minecraft:cobblestone', 3, ['stone'], 0),
     'before': [('start', 'falling_gravel')],
     'check': [('gain', 'minecraft:cobblestone', 6), ('alive', 14)],
     'budget': 15,
     'skills': ['mine'],
     'point': 'A',
     'tags': {'base': 'mine_stone', 'surprise': 'falling_gravel'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'start_cell_on_a_fence',
     'module': 'skills',
     'doc': 'walk 8 blocks east over the arena — the walk starts standing on a fence post (the mod judged such a '
            "start cell unstandable: '1 positions explored')",
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 10, -1, 3), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('setblock', ('@', 0, 0, 0), 'oak_fence'),
               ('tp', ('@', 0.5, 1.5, 0.5))],
     'run': ('skill', 'travel_to', ('@', 8, 0, 0), 2),
     'before': [('start', 'start_cell_on_a_fence')],
     'check': [('_at', ('@', 8, 0, 0), 3.5)],
     'budget': 15,
     'skills': ['goto'],
     'point': 'A',
     'tags': {'base': 'nav', 'surprise': 'start_cell_on_a_fence'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'start_cell_in_a_nook',
     'module': 'skills',
     'doc': 'walk 8 blocks east over the arena — the walk starts in a one-block nook under a slab',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 8, -3, -3), ('@', 10, -1, 3), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('fill', ('@', -1, 0, -1), ('@', 1, 1, 1), 'stone'),
               ('fill', ('@', 0, 0, 0), ('@', 1, 1, 0), 'air'),
               ('setblock', ('@', 0, 2, 0), 'stone_slab')],
     'run': ('skill', 'travel_to', ('@', 8, 0, 0), 2),
     'before': [('start', 'start_cell_in_a_nook')],
     'check': [('_at', ('@', 8, 0, 0), 3.5)],
     'budget': 15,
     'skills': ['goto'],
     'point': 'A',
     'tags': {'base': 'nav', 'surprise': 'start_cell_in_a_nook'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'take_bed',
     'module': 'skills',
     'doc': 'a village bed 6 blocks away → carried',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 6, 0, 0), 'red_bed'),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('skill', 'take', 'bed', 1, ['red_bed']),
     'before': [('start', 'take_bed')],
     'check': [('gain', 'bed', 1)],
     'budget': 25,
     'skills': ['take'],
     'point': 'A',
     'tags': {'base': 'take'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'tidy_full_bag',
     'module': 'skills',
     'doc': 'a full bag of junk → slots free',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'dirt', 2304)],
     'run': ('skill', 'tidy_inventory'),
     'before': [('start', 'tidy_full_bag')],
     'check': [('free_slots', 2)],
     'budget': 25,
     'skills': ['room:tidy'],
     'point': 'A',
     'tags': {'base': 'room:tidy'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'dig_out_morning',
     'module': 'skills',
     'doc': 'morning, sealed in a 1×1 pocket → out',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', -1, 0, -1), ('@', 1, 2, 1), 'stone'),
               ('fill', ('@', 0, 0, 0), ('@', 0, 1, 0), 'air'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'dig_out'),
     'before': [('start', 'dig_out_morning')],
     'check': [('not', ('!call', 'enclosed', []))],
     'budget': 25,
     'skills': ['dig_out'],
     'point': 'A',
     'tags': {'base': 'dig_out'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'pod_open_ground',
     'module': 'skills',
     'doc': 'night, open ground, 16 blocks → walled in',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 16),
               ('time', 18000)],
     'run': ('skill', 'pod'),
     'before': [('start', 'pod_open_ground')],
     'check': [('blocks', ('@', -1, 0, -1), ('@', 1, 2, 1), ('cobblestone',), 9)],
     'budget': 25,
     'skills': ['shelter:wall in'],
     'point': 'A',
     'tags': {'base': 'shelter:wall in'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'pod_in_water',
     'module': 'skills',
     'doc': 'night, standing on a pillar in deep water → walled in anyway',
     'scene': [('fill', ('@', -7, -4, -7), ('@', 7, -4, 7), 'stone'),
               ('fill', ('@', -7, -3, -7), ('@', 7, 0, -7), 'glass'),
               ('fill', ('@', -7, -3, 7), ('@', 7, 0, 7), 'glass'),
               ('fill', ('@', -7, -3, -7), ('@', -7, 0, 7), 'glass'),
               ('fill', ('@', 7, -3, -7), ('@', 7, 0, 7), 'glass'),
               ('fill', ('@', -6, -3, -6), ('@', 6, -1, 6), 'water'),
               ('fill', ('@', 0, -3, 0), ('@', 0, -1, 0), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 32),
               ('time', 18000)],
     'run': ('skill', 'pod'),
     'before': [('start', 'pod_in_water')],
     'check': [('blocks', ('@', -1, 0, -1), ('@', 1, 2, 1), ('cobblestone',), 9)],
     'budget': 25,
     'skills': ['shelter:wall in'],
     'point': 'A',
     'tags': {'base': 'shelter:wall in'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'build_shelter_flat',
     'module': 'skills',
     'doc': "flat stone, the hut's materials → a shelter standing",
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 32),
               ('give', 'oak_door'),
               ('give', 'torch', 2)],
     'run': ('skill', 'build_shelter'),
     'before': [('start', 'build_shelter_flat')],
     'check': [('blocks', ('@', -6, 0, -6), ('@', 6, 3, 6), ('cobblestone',), 14),
               ('blocks', ('@', -6, 0, -6), ('@', 6, 3, 6), ('oak_door',), 1),
               ('blocks', ('@', -6, 0, -6), ('@', 6, 3, 6), ('torch', 'wall_torch'), 1)],
     'budget': 25,
     'skills': ['build:shelter'],
     'point': 'A',
     'tags': {'base': 'build:shelter'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'burrow_hillside',
     'module': 'skills',
     'doc': 'night, a stone hillside beside the body → tunnelled in and sealed',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, 0, -4), ('@', 8, 4, 4), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'stone_pickaxe'),
               ('give', 'cobblestone', 8),
               ('time', 18000),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'burrow'),
     'before': [('start', 'burrow_hillside')],
     'check': [('alive', 18), ('call', 'enclosed', [])],
     'budget': 25,
     'skills': ['burrow'],
     'point': 'A',
     'tags': {'base': 'burrow'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'contain_lava_pool',
     'module': 'skills',
     'doc': 'an open lava pool beside the body → covered',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, -1, -1), ('@', 3, -1, 1), 'lava'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 16)],
     'run': ('skill', 'contain_lava'),
     'before': [('start', 'contain_lava_pool')],
     'check': [('blocks', ('@', 2, -1, -1), ('@', 3, -1, 1), ('lava',), 0, 0)],
     'budget': 25,
     'skills': ['contain_lava'],
     'point': 'A',
     'tags': {'base': 'contain_lava'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'torch_in_the_dark',
     'module': 'skills',
     'doc': 'a dark room, torches carried → one torch placed',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('at', 'fill {0} {1} stone hollow', ('@', -4, 0, -4), ('@', 4, 3, 4)),
               ('fill', ('@', -3, 0, -3), ('@', 3, 2, 3), 'air'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'torch', 4)],
     'run': ('skill', 'light_area', 4, 1),
     'before': [('start', 'torch_in_the_dark')],
     'check': [('blocks', ('@', -3, 0, -3), ('@', 3, 2, 3), ('torch', 'wall_torch'), 1)],
     'budget': 20,
     'skills': ['light'],
     'point': 'A',
     'tags': {'base': 'light'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'light_the_room',
     'module': 'skills',
     'doc': 'a dark 9×9 room, 8 torches → several placed',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('at', 'fill {0} {1} stone hollow', ('@', -6, 0, -6), ('@', 6, 3, 6)),
               ('fill', ('@', -5, 0, -5), ('@', 5, 2, 5), 'air'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'torch', 8)],
     'run': ('skill', 'light_area', 6, 4),
     'before': [('start', 'light_the_room')],
     'check': [('blocks', ('@', -5, 0, -5), ('@', 5, 2, 5), ('torch', 'wall_torch'), 2)],
     'budget': 25,
     'skills': ['light_area'],
     'point': 'A',
     'tags': {'base': 'light_area'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'find_air_capped',
     'module': 'skills',
     'doc': 'under water with a stone cap, out of breath → air',
     'scene': [('fill', ('@', -4, -4, -4), ('@', 4, 3, 4), 'stone'),
               ('fill', ('@', -3, -3, -3), ('@', 3, 2, 3), 'water'),
               ('tp', ('@', 0.5, -3, 0.5)),
               ('give', 'stone_pickaxe'),
               ('give', 'diamond_pickaxe')],
     'run': ('timed', ('!skill', 'find_air')),
     'before': [('start', 'find_air_capped')],
     'check': [('alive', 10), ('breathing',)],
     'budget': 25,
     'skills': ['find_air'],
     'point': 'A',
     'tags': {'base': 'find_air'},
     'target_s': 7.5,
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'surface_from_lake',
     'module': 'skills',
     'doc': '4 blocks down in open water → up to breathe',
     'scene': [('fill', ('@', -6, -4, -6), ('@', 6, -4, 6), 'stone'),
               ('fill', ('@', -6, -3, -6), ('@', 6, 8, -6), 'glass'),
               ('fill', ('@', -6, -3, 6), ('@', 6, 8, 6), 'glass'),
               ('fill', ('@', -6, -3, -6), ('@', -6, 8, 6), 'glass'),
               ('fill', ('@', 6, -3, -6), ('@', 6, 8, 6), 'glass'),
               ('fill', ('@', -5, -3, -5), ('@', 5, 7, 5), 'water'),
               ('tp', ('@', 0.5, -3, 0.5))],
     'run': ('skill', 'find_air'),
     'before': [('start', 'surface_from_lake')],
     'check': [('breathing',)],
     'budget': 25,
     'skills': ['reach:air'],
     'point': 'A',
     'tags': {'base': 'reach:air'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'footing_in_water',
     'module': 'skills',
     'doc': 'treading water, cobblestone carried → a block underfoot',
     'scene': [('fill', ('@', -5, -4, -5), ('@', 5, -4, 5), 'stone'),
               ('fill', ('@', -5, -3, -5), ('@', 5, 0, -5), 'glass'),
               ('fill', ('@', -5, -3, 5), ('@', 5, 0, 5), 'glass'),
               ('fill', ('@', -5, -3, -5), ('@', -5, 0, 5), 'glass'),
               ('fill', ('@', 5, -3, -5), ('@', 5, 0, 5), 'glass'),
               ('fill', ('@', -4, -3, -4), ('@', 4, -1, 4), 'water'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 8)],
     'run': ('skill', 'stand_on_a_block'),
     'before': [('start', 'footing_in_water')],
     'check': [('state', 'onGround'), ('under_feet', 'cobblestone')],
     'budget': 20,
     'skills': ['reach:footing'],
     'point': 'A',
     'tags': {'base': 'reach:footing'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'open_space_from_shaft',
     'module': 'skills',
     'doc': 'a full bag at the bottom of a 1×1 shaft → out where it is open',
     'scene': [('fill', ('@', -8, -4, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 0, -3, 0), ('@', 0, -1, 0), 'air'),
               ('tp', ('@', 0.5, -3, 0.5)),
               ('give', 'dirt', 2304),
               ('give', 'stone_pickaxe')],
     'run': ('skill', 'move_to_open_space'),
     'before': [('start', 'open_space_from_shaft')],
     'check': [('room_to_work',)],
     'budget': 25,
     'skills': ['move_to_open_space'],
     'point': 'A',
     'tags': {'base': 'move_to_open_space'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'repair_broken_hut',
     'module': 'skills',
     'doc': 'a remembered hut with two wall blocks knocked out → rebuilt',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('at', 'fill {0} {1} cobblestone hollow', ('@', 2, 0, -2), ('@', 6, 2, 2)),
               ('fill', ('@', 2, 0, 0), ('@', 2, 1, 0), 'air'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 8)],
     'run': ('skill', 'repair_site', ('$call', 'broken_hut', '$ctx')),
     'before': [('start', 'repair_broken_hut')],
     'check': [('blocks', ('@', 2, 0, 0), ('@', 2, 1, 0), ('cobblestone',), 2)],
     'budget': 25,
     'skills': ['repair_site'],
     'point': 'A',
     'tags': {'base': 'repair_site'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'wait_out_the_night',
     'module': 'skills',
     'doc': 'night in a sealed stone room, no bed → waited until morning',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('at', 'fill {0} {1} stone hollow', ('@', -2, 0, -2), ('@', 2, 4, 2)),
               ('tp', ('@', 0.5, 1, 0.5)),
               ('time', 23500)],
     'run': ('skill', 'wait_for_day'),
     'before': [('start', 'wait_out_the_night')],
     'check': [('is_day',)],
     'budget': 25,
     'skills': ['wait:day'],
     'point': 'A',
     'tags': {'base': 'wait:day'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'withdraw_from_chest',
     'module': 'skills',
     'doc': 'a chest of iron beside the body → 4 ingots taken out',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 2, 0, 0), 'chest'),
               ('at', 'item replace block {0} container.0 with iron_ingot 9', ('@', 2, 0, 0)),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('skill', 'withdraw', 'minecraft:iron_ingot', 4, ('@', 2, 0, 0)),
     'before': [('start', 'withdraw_from_chest')],
     'check': [('gain', 'minecraft:iron_ingot', 4)],
     'budget': 25,
     'skills': ['withdraw'],
     'point': 'A',
     'tags': {'base': 'withdraw'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'enchant_pickaxe',
     'module': 'skills',
     'doc': 'an enchanting table, lapis, levels, an iron pickaxe → enchanted (lapis spent)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 2, 0, 0), 'enchanting_table'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'iron_pickaxe'),
               ('give', 'lapis_lazuli', 6),
               ('cmd', 'experience add @p 30 levels')],
     'run': ('skill', 'enchant_item', 'minecraft:iron_pickaxe'),
     'before': [('start', 'enchant_pickaxe')],
     'check': [('count', 'minecraft:lapis_lazuli', '<', 6), ('slot_has', 'minecraft:iron_pickaxe', 'enchant')],
     'budget': 25,
     'skills': ['enchant'],
     'point': 'A',
     'tags': {'base': 'enchant'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'trade_bread',
     'module': 'skills',
     'doc': 'a farmer selling bread for an emerald, 3 emeralds → bread',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'emerald', 3),
               ('summon',
                'villager',
                ('@', 3, 0, 0),
                '{NoAI:1b,VillagerData:{profession:"minecraft:farmer",level:2,type:"minecraft:plains"},Offers:{Recipes:[{buy:{id:"minecraft:emerald",count:1},sell:{id:"minecraft:bread",count:6},maxUses:12}]}}')],
     'run': ('skill', 'trade', 'minecraft:bread'),
     'before': [('start', 'trade_bread')],
     'check': [('gain', 'minecraft:bread', 6)],
     'budget': 25,
     'skills': ['trade'],
     'point': 'A',
     'tags': {'base': 'trade'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'brew_fire_resistance_stand',
     'module': 'skills',
     'doc': 'a brewing stand, water bottles, wart, magma cream, blaze powder → fire resistance (the cream spent)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 2, 0, 0), 'brewing_stand'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'potion[potion_contents={potion:"minecraft:water"}]', 3),
               ('give', 'nether_wart'),
               ('give', 'magma_cream'),
               ('give', 'blaze_powder', 2)],
     'run': ('skill', 'brew_fire_resistance'),
     'before': [('start', 'brew_fire_resistance_stand')],
     'check': [('slot_has', 'minecraft:potion', 'fire_resistance')],
     'budget': 25,
     'skills': ['brew:fire_resistance'],
     'point': 'A',
     'tags': {'base': 'brew:fire_resistance'},
     'tick_rate': 60,
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'collect_auto_smelter',
     'module': 'skills',
     'doc': 'a remembered auto smelter whose output chest holds 8 ingots → taken',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('setblock', ('@', 3, 0, 0), 'chest'),
               ('at', 'item replace block {0} container.0 with iron_ingot 8', ('@', 3, 0, 0)),
               ('tp', ('@', 0.5, 0, 0.5))],
     'run': ('skill', 'collect_machine', ('$call', 'bench_machine', '$ctx', ('@', 3, 0, 0))),
     'before': [('start', 'collect_auto_smelter')],
     'check': [('gain', 'minecraft:iron_ingot', 8)],
     'budget': 25,
     'skills': ['collect_machine'],
     'point': 'A',
     'tags': {'base': 'collect_machine'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'bridge_the_gap',
     'module': 'skills',
     'doc': 'a 6-block gap in the floor toward the target, blocks carried → across',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, -3, -8), ('@', 7, -1, 8), 'air'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 16),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'bridge_toward', ('@', 9, 0, 0)),
     'before': [('start', 'bridge_the_gap')],
     'check': [('_at', ('@', 9, 0, 0), 4)],
     'budget': 25,
     'skills': ['bridge_toward'],
     'point': 'A',
     'tags': {'base': 'bridge_toward'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'plant_wheat',
     'module': 'skills',
     'doc': 'grass, seeds, a hoe, a water bucket → a wheat plot growing',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wheat_seeds', 2),
               ('give', 'stone_hoe'),
               ('give', 'water_bucket')],
     'run': ('skill', 'plant_farm'),
     'before': [('start', 'plant_wheat')],
     'check': [('blocks', ('@', -4, 0, -4), ('@', 4, 0, 4), ('wheat',), 2)],
     'budget': 25,
     'skills': ['plant_farm'],
     'point': 'A',
     'tags': {'base': 'plant_farm'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'breed_cows',
     'module': 'skills',
     'doc': 'two cows in a pen, wheat carried → wheat spent on them',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', -7, 0, -7), ('@', 7, 0, -7), 'oak_fence'),
               ('fill', ('@', -7, 0, 7), ('@', 7, 0, 7), 'oak_fence'),
               ('fill', ('@', -7, 0, -6), ('@', -7, 0, 6), 'oak_fence'),
               ('fill', ('@', 7, 0, -6), ('@', 7, 0, 6), 'oak_fence'),
               ('summon', 'cow', ('@', 3, 0, 2)),
               ('summon', 'cow', ('@', -3, 0, 2)),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wheat', 4)],
     'run': ('skill', 'breed'),
     'before': [('start', 'breed_cows')],
     'check': [('mobs_near', 'minecraft:cow', 3)],
     'budget': 25,
     'skills': ['breed'],
     'point': 'A',
     'tags': {'base': 'breed'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'fill_bottles_at_pond',
     'module': 'skills',
     'doc': 'a pond, 3 glass bottles → 3 water bottles',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 2, -1, -1), ('@', 3, -1, 1), 'water'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'glass_bottle', 3)],
     'run': ('skill', 'fill_bottles', 3),
     'before': [('start', 'fill_bottles_at_pond')],
     'check': [('gain', 'minecraft:potion', 3)],
     'budget': 25,
     'skills': ['fill_bottles'],
     'point': 'A',
     'tags': {'base': 'fill_bottles'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'seek_blocks_real',
     'module': 'skills',
     'doc': 'real terrain, a log column 16 blocks off → walked to it',
     'scene': [('cmd', 'spreadplayers 14200 14200 0 4 false @p'),
               ('cmd', 'clear @p'),
               ('give', 'stone_pickaxe'),
               ('give', 'torch', 8),
               ('give', 'cobblestone', 32),
               ('give', 'cooked_beef', 8),
               ('cmd', 'execute at @p run fill ~16 ~ ~ ~16 ~4 ~ oak_log'),
               ('give', 'diamond_axe')],
     'run': ('skill', 'seek_blocks', ['oak_log', 'birch_log', 'spruce_log'], 1, 20),
     'before': [('start', 'seek_blocks_real')],
     'check': [('found_near', ['oak_log', 'birch_log', 'spruce_log'], 8)],
     'budget': 25,
     'raw': True,
     'release': True,
     'skills': ['seek_blocks'],
     'point': 'A',
     'tags': {'base': 'seek_blocks', 'terrain': 'real'}},
    {'name': 'strip_mine_real',
     'module': 'skills',
     'doc': 'real terrain, a stone pickaxe → a mining tunnel started',
     'scene': [('cmd', 'spreadplayers 14200 14200 0 4 false @p'),
               ('cmd', 'clear @p'),
               ('give', 'stone_pickaxe'),
               ('give', 'torch', 8),
               ('give', 'cobblestone', 32),
               ('give', 'cooked_beef', 8),
               ('cmd', 'execute at @p run fill ~-1 17 ~-1 ~1 19 ~1 air'),
               ('cmd', 'execute at @p run tp @p ~ 17 ~'),
               ('give', 'diamond_pickaxe')],
     'run': ('skill', 'strip_mine_step', 2),
     'before': [('start', 'strip_mine_real')],
     'check': [('gain', 'minecraft:cobblestone', 2)],
     'budget': 25,
     'raw': True,
     'release': True,
     'skills': ['strip_mine_step'],
     'point': 'A',
     'tags': {'base': 'strip_mine_step', 'terrain': 'real'}},
    {'name': 'build_light_portal_interrupted',
     'module': 'building',
     'doc': 'flat stone, 10 obsidian, interrupted with 4 placed → resumed from the world: 10 in the frame, none in '
            'the bag, lit',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('give', 'obsidian', 10),
               ('give', 'cobblestone', 16),
               ('give', 'flint_and_steel')],
     'run': ('resume',
             'build_light_portal_interrupted',
             ('!do', 'bonobo.building.build_blueprint', ['$ctx', 'nether_portal', ('@', 0, 0, 0)], {}),
             ('!do', 'bonobo.building.build_blueprint', ['$ctx', 'nether_portal', ('@', 0, 0, 0)], {})),
     'before': [('start', 'build_light_portal_interrupted'),
                ('interrupt_when',
                 ('!placed_at_least', ('@', -8, 0, -8), ('@', 8, 6, 8), 'obsidian', 4),
                 None,
                 'bench: interrupt at the moment of success')],
     'check': [('call', 'count_blocks', ['$api', ('@', -8, 0, -8), ('@', 8, 6, 8), 'nether_portal'], '>=', 6),
               ('blocks', ('@', -8, 0, -8), ('@', 8, 6, 8), ('obsidian',), 10, 10),
               ('count', 'minecraft:obsidian', '==', 0),
               ('interrupted',)],
     'budget': 25,
     'point': 'A',
     'skills': ['build_blueprint'],
     'tags': {'base': 'build_blueprint', 'surprise': 'interrupt_mid_chain'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'place_observer_up',
     'module': 'building',
     'doc': "Place observer asking facing=up (the jar turns the body by the block's own rule) → the block reports "
            'facing=up',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'observer', 2)],
     'run': ('place_facing', 'minecraft:observer', ('@', 3, 0, 0), 'up'),
     'before': [('start', 'place_observer_up')],
     'check': [('placed_facing', ('@', 3, 0, 0), 'up')],
     'budget': 20,
     'point': 'A',
     'skills': [],
     'tier_fixed': 'exception',
     'tags': {'base': 'place'},
     'variant': ('minecraft:observer', 'up'),
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'place_observer_down',
     'module': 'building',
     'doc': "Place observer asking facing=down (the jar turns the body by the block's own rule) → the block "
            'reports facing=down',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'observer', 2)],
     'run': ('place_facing', 'minecraft:observer', ('@', 3, 0, 0), 'down'),
     'before': [('start', 'place_observer_down')],
     'check': [('placed_facing', ('@', 3, 0, 0), 'down')],
     'budget': 20,
     'point': 'A',
     'skills': [],
     'tier_fixed': 'exception',
     'tags': {'base': 'place'},
     'variant': ('minecraft:observer', 'down'),
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'place_stairs_east',
     'module': 'building',
     'doc': "Place oak_stairs asking facing=east (the jar turns the body by the block's own rule) → the block "
            'reports facing=east',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'oak_stairs', 2)],
     'run': ('place_facing', 'minecraft:oak_stairs', ('@', 3, 0, 0), 'east'),
     'before': [('start', 'place_stairs_east')],
     'check': [('placed_facing', ('@', 3, 0, 0), 'east')],
     'budget': 20,
     'point': 'A',
     'skills': [],
     'tier_fixed': 'exception',
     'tags': {'base': 'place'},
     'variant': ('minecraft:oak_stairs', 'east'),
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'place_cobblestone_facing_ignored',
     'module': 'building',
     'doc': "Place cobblestone asking facing=north (the jar turns the body by the block's own rule) → the block "
            'reports facing=None',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'cobblestone', 2)],
     'run': ('place_facing', 'minecraft:cobblestone', ('@', 3, 0, 0), 'north'),
     'before': [('start', 'place_cobblestone_facing_ignored')],
     'check': [('placed_facing', ('@', 3, 0, 0), None)],
     'budget': 20,
     'point': 'A',
     'skills': [],
     'tier_fixed': 'exception',
     'tags': {'base': 'place'},
     'variant': ('minecraft:cobblestone', 'north'),
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'boat_across_the_lake',
     'module': 'nav',
     'doc': "A 6-block lake between two shores, a boat carried → across to the far shore (the jar's BoatDriver)",
     'scene': [('fill', ('@', -4, -4, -6), ('@', 12, -4, 6), 'stone'),
               ('fill', ('@', -4, -3, -6), ('@', -1, -1, 6), 'stone'),
               ('fill', ('@', 6, -3, -6), ('@', 12, -1, 6), 'stone'),
               ('fill', ('@', 0, -3, -6), ('@', 5, -1, 6), 'water'),
               ('tp', ('@', -1.5, 0, 0.5)),
               ('give', 'oak_boat')],
     'run': ('skill', 'travel_to', ('@', 7, 0, 0), 2),
     'before': [('start', 'boat_across_the_lake')],
     'check': [('_at', ('@', 7, 0, 0), 3), ('not', ('!state', 'inWater'))],
     'budget': 25,
     'point': 'A',
     'skills': ['goto'],
     'tier_fixed': 'exception',
     'tags': {'base': 'nav', 'terrain': 'lake'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'pearls_from_barter',
     'module': 'decompose',
     'doc': 'In the Nether, 2 gold ingots and a gold helmet, piglins 4 blocks off, no enderman → the plan barters',
     'scene': [('fill', ('@', -8, -2, -8), ('@', 8, -1, 8), 'netherrack'),
               ('at', 'fill {0} {1} glass hollow', ('@', -9, 0, -9), ('@', 9, 4, 9)),
               ('fill', ('@', -8, 0, -8), ('@', 8, 3, 8), 'air'),
               ('tp', ('@', 0, 0, 0)),
               ('cmd', 'clear @p'),
               ('cmd', 'item replace entity @p armor.feet with golden_boots'),
               ('give', 'gold_ingot', 2),
               ('give', 'golden_helmet'),
               ('give', 'iron_sword'),
               ('summon', 'piglin', ('@', 4, 0, 0), '{PersistenceRequired:1b}'),
               ('summon', 'piglin', ('@', -4, 0, 2), '{PersistenceRequired:1b}'),
               ('summon', 'piglin', ('@', 2, 0, -4), '{PersistenceRequired:1b}')],
     'run': ('achieve_needs', [('minecraft:ender_pearl', 1)], 4),
     'before': [('start', 'pearls_from_barter')],
     'check': [('count', 'minecraft:gold_ingot', '<', 2), ('call', 'trades', ['$inv'], '>=', 1)],
     'budget': 25,
     'point': 'C',
     'skills': ['barter'],
     'tier_fixed': 'exception',
     'tags': {'base': 'sources'},
     'dimension': 'minecraft:the_nether',
     'combat': True,
     'tick_rate': 60,
     'expect': [(('@', -8, -1, -8), ('@', 8, -1, 8), 'netherrack', 289, 289)],
     'expect_entities': [('minecraft:piglin', 3)]},
    {'name': 'bread_from_a_farm',
     'module': 'decompose',
     'doc': 'grass, a hoe, 8 seeds, a water bucket, nothing else → the plan plants a plot (its farm step), the '
            'crop grows (random ticks fast), harvested, bread baked',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'diamond_hoe'),
               ('give', 'wheat_seeds', 8),
               ('give', 'water_bucket')],
     'run': ('growing', ('!achieve_needs', [('minecraft:bread', 1)], 6)),
     'before': [('start', 'bread_from_a_farm')],
     'check': [('gain', 'minecraft:bread', 1), ('blocks', ('@', -4, -1, -4), ('@', 4, -1, 4), ('farmland',), 1)],
     'budget': 25,
     'point': 'C',
     'skills': ['farm'],
     'tier_fixed': 'exception',
     'tags': {'base': 'sources', 'source': 'farm'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'bread_from_a_farm_two_wheat_carried',
     'module': 'decompose',
     'doc': "2 wheat carried, a ripe plot beside the body → the plan's farm step reaps it (the look at execution, "
            'not in the estimate; no new plot sown) and bakes: bread',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'grass_block'),
               ('fill', ('@', 4, -1, -1), ('@', 6, -1, 1), 'farmland'),
               ('fill', ('@', 4, 0, -1), ('@', 6, 0, 1), 'wheat[age=7]'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wheat', 2),
               ('give', 'diamond_hoe'),
               ('give', 'wheat_seeds', 8),
               ('give', 'water_bucket')],
     'run': ('achieve_needs', [('minecraft:bread', 1)], 4),
     'before': [('start', 'bread_from_a_farm_two_wheat_carried')],
     'check': [('gain', 'minecraft:bread', 1),
               ('blocks', ('@', 4, 0, -1), ('@', 6, 0, 1), ('wheat',), 0, 8),
               ('blocks', ('@', -8, -1, -8), ('@', 3, -1, 8), ('farmland',), 0, 0)],
     'budget': 25,
     'point': 'C',
     'skills': ['farm'],
     'tier_fixed': 'exception',
     'tags': {'base': 'sources', 'source': 'farm'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'bread_from_a_farm_no_soil',
     'module': 'decompose',
     'doc': 'stone floor, the same kit → no plot can be made: the plan fails naming the soil (must fail, never a '
            'hang)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'diamond_hoe'),
               ('give', 'wheat_seeds', 8),
               ('give', 'water_bucket')],
     'run': ('expect_failure',
             'bread_from_a_farm_no_soil',
             ('!achieve_needs', [('minecraft:bread', 1)], 3),
             'soil|no flat|farm'),
     'before': [('start', 'bread_from_a_farm_no_soil')],
     'check': [('same_bag',)],
     'budget': 25,
     'point': 'C',
     'skills': ['farm'],
     'tier_fixed': 'exception',
     'tags': {'base': 'sources', 'source': 'farm'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'emerald_from_a_villager',
     'module': 'decompose',
     'doc': 'a farmer buying 20 wheat for an emerald, 20 wheat carried → the plan sells: an emerald gained, the '
            'wheat gone',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wheat', 20),
               ('summon',
                'villager',
                ('@', 3, 0, 0),
                '{NoAI:1b,VillagerData:{profession:"minecraft:farmer",level:2,type:"minecraft:plains"},Offers:{Recipes:[{buy:{id:"minecraft:wheat",count:20},sell:{id:"minecraft:emerald",count:1},maxUses:12}]}}')],
     'run': ('achieve_needs', [('minecraft:emerald', 1)], 3),
     'before': [('start', 'emerald_from_a_villager')],
     'check': [('gain', 'minecraft:emerald', 1), ('count', 'minecraft:wheat', '==', 0)],
     'budget': 25,
     'point': 'C',
     'skills': ['trade'],
     'tier_fixed': 'exception',
     'tags': {'base': 'sources', 'source': 'trade'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'emerald_villager_without_the_trade',
     'module': 'decompose',
     'doc': 'a villager who only sells bread → no emerald offer: the trade ends naming it (must fail, never a '
            'hang)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wheat', 20),
               ('summon',
                'villager',
                ('@', 3, 0, 0),
                '{NoAI:1b,VillagerData:{profession:"minecraft:farmer",level:2,type:"minecraft:plains"},Offers:{Recipes:[{buy:{id:"minecraft:emerald",count:1},sell:{id:"minecraft:bread",count:6},maxUses:12}]}}')],
     'run': ('expect_failure',
             'emerald_villager_without_the_trade',
             ('!skill', 'trade', 'minecraft:emerald'),
             'no affordable|emerald trade'),
     'before': [('start', 'emerald_villager_without_the_trade')],
     'check': [('same_bag',)],
     'budget': 25,
     'point': 'C',
     'skills': ['trade'],
     'tier_fixed': 'exception',
     'tags': {'base': 'sources', 'source': 'trade'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'emerald_no_villager',
     'module': 'decompose',
     'doc': 'no villager anywhere, wheat carried → the trade fails naming it (must fail)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'wheat', 20)],
     'run': ('expect_failure', 'emerald_no_villager', ('!skill', 'trade', 'minecraft:emerald'), 'no villager'),
     'before': [('start', 'emerald_no_villager')],
     'check': [('same_bag',)],
     'budget': 25,
     'point': 'C',
     'skills': ['trade'],
     'tier_fixed': 'exception',
     'tags': {'base': 'sources', 'source': 'trade'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'water_bucket_from_the_plan',
     'module': 'decompose',
     'doc': 'An empty bucket, a pond 3 blocks off → the plan fills it (the fill producer): a water bucket held',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('fill', ('@', 3, -1, -1), ('@', 4, -1, 1), 'water'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('give', 'bucket')],
     'run': ('achieve_needs', [('minecraft:water_bucket', 1)], 3),
     'before': [('start', 'water_bucket_from_the_plan')],
     'check': [('gain', 'minecraft:water_bucket', 1)],
     'budget': 25,
     'point': 'C',
     'skills': ['fill'],
     'tier_fixed': 'exception',
     'tags': {'base': 'sources', 'source': 'fill'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
    {'name': 'night_mines_under_cover',
     'module': 'brain',
     'doc': 'Night, sealed in a 1×2 hole 9 below the platform, a stone pickaxe, iron ore 3 below and 2 aside, '
            "nothing queued → the night's work is ore dug down to (brain.night_pick → descend), not waiting for "
            'day and not a climb to the surface',
     'scene': [('fill', ('@', -6, -16, -6), ('@', 6, -1, 6), 'stone'),
               ('fill', ('@', 0, -9, 0), ('@', 0, -8, 0), 'air'),
               ('fill', ('@', 1, -13, 1), ('@', 2, -12, 2), 'iron_ore'),
               ('tp', ('@', 0.5, -9, 0.5)),
               ('cmd', 'clear @p'),
               ('give', 'stone_pickaxe'),
               ('give', 'cooked_beef', 8),
               ('give', 'cobblestone', 16),
               ('time', 13000),
               ('give', 'diamond_pickaxe')],
     'run': ('brain_rounds', 30, ('!now', ('!count', 'minecraft:raw_iron', '>=', 1))),
     'before': [('start', 'night_mines_under_cover')],
     'check': [('count', 'minecraft:raw_iron', '>=', 1), ('state', 'blockY', '<', 198)],
     'budget': 25,
     'point': 'C',
     'skills': ['mine'],
     'tier_fixed': 'exception',
     'tags': {'base': 'night'},
     'expect': [(('@', 1, -13, 1), ('@', 2, -12, 2), 'iron_ore', 8, 8)]},
    {'name': 'craft_chain_one_sitting',
     'module': 'skills',
     'doc': '3 logs and a table carried → planks, sticks and a wooden pickaxe crafted in one sitting (craft_chain: '
            'the table placed and taken back once, not per recipe)',
     'scene': [('fill', ('@', -8, -3, -8), ('@', 8, -1, 8), 'stone'),
               ('tp', ('@', 0.5, 0, 0.5)),
               ('cmd', 'clear @p'),
               ('give', 'oak_log', 3),
               ('give', 'crafting_table')],
     'run': ('skill', 'craft_chain', [('planks', 2), ('minecraft:stick', 1), ('minecraft:wooden_pickaxe', 1)]),
     'before': [('start', 'craft_chain_one_sitting')],
     'check': [('gain', 'minecraft:wooden_pickaxe', 1, 1)],
     'budget': 15,
     'point': 'A',
     'skills': ['craft_chain'],
     'tier_fixed': 'exception',
     'tags': {'base': 'craft'},
     'expect': [(('@', -10, -17, -10), ('@', 20, 9, 10), '*', 1, 1000000)]},
]

NOT_EXPRESSED = {
    'activate_end_portal': "_timed.<locals>.go: <lambda>: a lambda; reads the call's arguments: __import__('bonobo.end', fromlist=['activate_end_p",
    'recover_items': "<lambda>: a lambda; a run that is not one call: (ctx.mem.log_death(at(6, 0, 0), 'minecraft:overworld'), _cha",
    'relight_portal': '<lambda>: a lambda; no run target in ctx.mem.add_site',
    'gold_helmet_swap': '<lambda>: a lambda; no run target in core.BRAIN.invariants',
    'find_fortress': "<lambda>: a lambda; no predicate for __import__('bonobo.memory', fromlist=['Memory']).Memory(NOTE",
    'return_to_portal': '<lambda>: a lambda; no run target in ctx.mem.add_site',
    'road_reuse': '<lambda>: a lambda; no comparison for len(ROAD_TIMES) … 3',
    'slice_retreat': "<lambda>: a lambda; a run that is not one call: (ctx.mem.add_site('portal', at(2, 1, 0), 'minecraft:the_neth",
    'eat__underwater': "<lambda>: a lambda; a run that is not one call: (_chat('effect give @p minecraft:hunger 5 255 true'), time.s",
    'eat__inventory_lag': "<lambda>: a lambda; a run that is not one call: (_chat('effect give @p minecraft:hunger 5 255 true'), time.s",
    'smelt__interrupt_twice': '_on_progress.<locals>.hook: _on_progress: base not kept in its closure',
    'nav__contested': '_on_progress.<locals>.hook: _on_progress: base not kept in its closure',
    'nav__player_takeover': '_on_progress.<locals>.hook: _on_progress: base not kept in its closure',
    'nav__buried_by_sand': '_on_progress.<locals>.hook: _on_progress: base not kept in its closure',
    'mine_stone__buried_by_sand': '_on_progress.<locals>.hook: _on_progress: base not kept in its closure',
    'craft__buried_by_sand': '_on_progress.<locals>.hook: _on_progress: base not kept in its closure',
    'smelt__buried_by_sand': '_on_progress.<locals>.hook: _on_progress: base not kept in its closure',
    'eat_with_nothing': "<lambda>: a lambda; a run that is not one call: (_chat('effect give @p minecraft:hunger 5 255 true'), time.s",
    'deposit_home_chest': "<lambda>: a lambda; a run that is not one call: (ctx.mem.add_site('home', at(2, 0, 0), 'minecraft:overworld'",
    'unbury_sand': "<lambda>: a lambda; a run that is not one call: (_chat(f'fill {_c(at(0, 1, 0))} {_c(at(0, 3, 0))} sand'), ti",
    'seek_remembered': "<lambda>: a lambda; a run that is not one call: (ctx.mem.note_seen('iron_ore', at(17, 0, 0), 'minecraft:over",
    'smelt_in_background': "<lambda>: a lambda; a run that is not one call: (_skill('start_smelt_job')(ctx, 'minecraft:iron_ingot', 'min",
    'repair_two_pickaxes': "<lambda>: a lambda; no predicate for any((s_['id'] == 'minecraft:stone_pickaxe' and s_.get('damag",
    'anvil_repair_pickaxe': "<lambda>: a lambda; no predicate for any((s_['id'] == 'minecraft:diamond_pickaxe' and s_.get('dam",
    'explore_for_animals_real': "<lambda>: a lambda; no predicate for __import__('bonobo.world', fromlist=['entities']).entities(2",
    'fill_bottles_interrupted': "_resume.<locals>.go: <lambda>: a lambda; not evaluable offline: 3 - (_inv_now().count('minecraft:potion') - _base_ (McError)",
    'dead_flicker_on_respawn': "<lambda>: a lambda; a run that is not one call: (_brain_rounds(15, lambda: not __import__('bonobo.api', from",
    'interrupted_rescue_is_not_a_failure': "<lambda>: a lambda; no run target in _threading.Timer(3.0, lambda: _chat(f'setblock {_c",
    'nether_full_bag': "<lambda>: a lambda; no predicate for __import__('bonobo.world', fromlist=['entities']).entities(1",
    'portal_from_cast': '<lambda>: a lambda; no run target in ctx.mem.note_seen',
    'bucket_before_the_shaft': '_queue.<locals>.hook: no factory _queue in bonobo.scenarios',
}
